// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

type ActionPlansListResponse struct {
}

type ActionPlansPeopleCreateResponse struct {
}

type ActionPlansPeopleListResponse struct {
}

type ActionPlansPeopleUpdateResponse struct {
}

type AppointmentOutcomesCreateResponse struct {
}

type AppointmentOutcomesDeleteResponse struct {
}

type AppointmentOutcomesGetResponse struct {
}

type AppointmentOutcomesListResponse struct {
}

type AppointmentOutcomesUpdateResponse struct {
}

type AppointmentTypesCreateResponse struct {
}

type AppointmentTypesDeleteResponse struct {
}

type AppointmentTypesGetResponse struct {
}

type AppointmentTypesListResponse struct {
}

type AppointmentTypesUpdateResponse struct {
}

type AppointmentsCreateResponse struct {
}

type AppointmentsDeleteResponse struct {
}

type AppointmentsGetResponse struct {
}

type AppointmentsListResponse struct {
}

type AppointmentsUpdateResponse struct {
}

type AutomationsGetResponse struct {
}

type AutomationsListResponse struct {
}

type AutomationsPeopleCreateResponse struct {
}

type AutomationsPeopleGetResponse struct {
}

type AutomationsPeopleListResponse struct {
}

type AutomationsPeopleUpdateResponse struct {
}

type CallsCreateResponse struct {
}

type CallsGetResponse struct {
}

type CallsListResponse struct {
}

type CallsUpdateResponse struct {
}

type CustomFieldsCreateResponse struct {
}

type CustomFieldsDeleteResponse struct {
}

type CustomFieldsGetResponse struct {
}

type CustomFieldsListResponse struct {
}

type CustomFieldsUpdateResponse struct {
}

type DealAttachmentsCreateResponse struct {
}

type DealAttachmentsDeleteResponse struct {
}

type DealAttachmentsGetResponse struct {
}

type DealAttachmentsUpdateResponse struct {
}

type DealCustomFieldsCreateResponse struct {
}

type DealCustomFieldsDeleteResponse struct {
}

type DealCustomFieldsGetResponse struct {
}

type DealCustomFieldsListResponse struct {
}

type DealCustomFieldsUpdateResponse struct {
}

type DealsCreateResponse struct {
}

type DealsDeleteResponse struct {
}

type DealsGetResponse struct {
}

type DealsListResponse struct {
}

type DealsUpdateResponse struct {
}

type EmCampaignsCreateResponse struct {
}

type EmCampaignsListResponse struct {
}

type EmCampaignsUpdateResponse struct {
}

type EmEventsCreateResponse struct {
}

type EmEventsListResponse struct {
}

type EventsCreateResponse struct {
}

type EventsGetResponse struct {
}

type EventsListResponse struct {
}

type GroupsCreateResponse struct {
}

type GroupsDeleteResponse struct {
}

type GroupsGetResponse struct {
}

type GroupsListResponse struct {
}

type GroupsRoundRobinListResponse struct {
}

type GroupsUpdateResponse struct {
}

type IdentityListResponse struct {
}

type MeListResponse struct {
}

type NotesCreateResponse struct {
}

type NotesDeleteResponse struct {
}

type NotesGetResponse struct {
}

type NotesUpdateResponse struct {
}

type PeopleCheckDuplicateListResponse struct {
}

type PeopleClaimCreateResponse struct {
}

type PeopleCreateResponse struct {
}

type PeopleDeleteResponse struct {
}

type PeopleGetResponse struct {
}

type PeopleIgnoreUnclaimedCreateResponse struct {
}

type PeopleListResponse struct {
}

type PeopleRelationshipsCreateResponse struct {
}

type PeopleRelationshipsDeleteResponse struct {
}

type PeopleRelationshipsGetResponse struct {
}

type PeopleRelationshipsListResponse struct {
}

type PeopleRelationshipsUpdateResponse struct {
}

type PeopleUnclaimedListResponse struct {
}

type PeopleUpdateResponse struct {
}

type PersonAttachmentsCreateResponse struct {
}

type PersonAttachmentsDeleteResponse struct {
}

type PersonAttachmentsGetResponse struct {
}

type PersonAttachmentsUpdateResponse struct {
}

type PipelinesCreateResponse struct {
}

type PipelinesDeleteResponse struct {
}

type PipelinesGetResponse struct {
}

type PipelinesListResponse struct {
}

type PipelinesUpdateResponse struct {
}

type PondsCreateResponse struct {
}

type PondsDeleteResponse struct {
}

type PondsGetResponse struct {
}

type PondsListResponse struct {
}

type PondsUpdateResponse struct {
}

type ReactionsGetResponse struct {
}

type ReactionsRefTypeRefIdCreateResponse struct {
}

type ReactionsRefTypeRefIdDeleteResponse struct {
}

type SmartListsGetResponse struct {
}

type SmartListsListResponse struct {
}

type StagesCreateResponse struct {
}

type StagesDeleteResponse struct {
}

type StagesGetResponse struct {
}

type StagesListResponse struct {
}

type StagesUpdateResponse struct {
}

type TasksCreateResponse struct {
}

type TasksDeleteResponse struct {
}

type TasksGetResponse struct {
}

type TasksListResponse struct {
}

type TasksUpdateResponse struct {
}

type TeamInboxesListResponse struct {
}

type TeamsCreateResponse struct {
}

type TeamsDeleteResponse struct {
}

type TeamsGetResponse struct {
}

type TeamsListResponse struct {
}

type TeamsUpdateResponse struct {
}

type TemplatesCreateResponse struct {
}

type TemplatesDeleteResponse struct {
}

type TemplatesGetResponse struct {
}

type TemplatesListResponse struct {
}

type TemplatesMergeCreateResponse struct {
}

type TemplatesUpdateResponse struct {
}

type TextMessageTemplatesCreateResponse struct {
}

type TextMessageTemplatesDeleteResponse struct {
}

type TextMessageTemplatesGetResponse struct {
}

type TextMessageTemplatesListResponse struct {
}

type TextMessageTemplatesMergeCreateResponse struct {
}

type TextMessageTemplatesUpdateResponse struct {
}

type TextMessagesCreateResponse struct {
}

type TextMessagesGetResponse struct {
}

type TextMessagesListResponse struct {
}

type ThreadedRepliesGetResponse struct {
}

type TimeframesListResponse struct {
}

type UsersDeleteResponse struct {
}

type UsersGetResponse struct {
}

type UsersListResponse struct {
}

type WebhookEventsGetResponse struct {
}

type WebhooksCreateResponse struct {
}

type WebhooksDeleteResponse struct {
}

type WebhooksGetResponse struct {
}

type WebhooksListResponse struct {
}

type WebhooksUpdateResponse struct {
}
