// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package mcp — code-orchestration thin surface.
//
// Two tools cover the entire API: <api>_search to discover endpoints, and
// <api>_execute to invoke one. This collapses a large API (50+ endpoints)
// to ~1K tokens of tool definitions while preserving full coverage — the
// agent writes the composition logic in its own sandbox.
//
// Pattern source: Anthropic 2026-04-22 "Building agents that reach
// production systems with MCP" — Cloudflare's MCP server covers ~2,500
// endpoints in roughly 1K tokens via the same search+execute shape.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"follow-up-boss-pp-cli/internal/cliutil"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterCodeOrchestrationTools registers the two agent-facing tools that
// cover the whole API surface. Called from RegisterTools in place of the
// per-endpoint registrations when MCP.Orchestration is "code".
func RegisterCodeOrchestrationTools(s *server.MCPServer) {
	registerProfiledTool(s,
		mcplib.NewTool("follow-up-boss_search",
			mcplib.WithDescription("Search the follow-up-boss API for endpoints matching a natural-language query. Returns a ranked list of {endpoint_id, method, path, summary} entries. Call this first to find the endpoint to execute."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Natural-language description of what you want to do.")),
			mcplib.WithNumber("limit", mcplib.Description("Max endpoints to return (default 10).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		cliutil.MCPToolSafety{Name: "follow-up-boss_search"},
		handleCodeOrchSearch,
	)

	registerProfiledTool(s,
		mcplib.NewTool("follow-up-boss_execute",
			mcplib.WithDescription("Execute one follow-up-boss API endpoint by its endpoint_id (from follow-up-boss_search). Params are passed as a JSON object; path placeholders and query strings are resolved automatically."),
			mcplib.WithString("endpoint_id", mcplib.Required(), mcplib.Description("Endpoint identifier returned by follow-up-boss_search (e.g., \"users.list\").")),
			mcplib.WithObject("params", mcplib.Description("Parameters for the endpoint. Path placeholders match by name; remaining entries become query string on GET/DELETE or JSON body on POST/PUT/PATCH.")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		cliutil.MCPToolSafety{Name: "follow-up-boss_execute", Destructive: true},
		handleCodeOrchExecute,
	)
}

// codeOrchEndpoint captures the small slice of endpoint metadata the
// search+execute pair needs at runtime. `keywords` is a precomputed
// lowercase stream of description + path tokens used for naive ranking;
// anything more sophisticated belongs on the agent side.
type codeOrchEndpoint struct {
	ID         string
	Method     string
	Path       string
	Tier       string
	Summary    string
	Positional []string
	keywords   []string
}

// codeOrchEndpoints is the generator-populated registry covering every
// endpoint declared in the spec. Kept flat on purpose — the agent queries
// via <api>_search, so hierarchy shows up as dotted IDs, not nested maps.
var codeOrchEndpoints = []codeOrchEndpoint{
	{
		ID:         "action-plans.list",
		Method:     "GET",
		Path:       "/actionPlans",
		Summary:    "Follow Up Boss GET /actionPlans. Source: https://docs.followupboss.com/reference/actionplans-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("action-plans", "list", "Follow Up Boss GET /actionPlans. Source: https://docs.followupboss.com/reference/actionplans-get", "/actionPlans"),
	},
	{
		ID:         "action-plans-people.create",
		Method:     "POST",
		Path:       "/actionPlansPeople",
		Summary:    "Follow Up Boss POST /actionPlansPeople. Source: https://docs.followupboss.com/reference/actionplanspeople-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("action-plans-people", "create", "Follow Up Boss POST /actionPlansPeople. Source: https://docs.followupboss.com/reference/actionplanspeople-post", "/actionPlansPeople"),
	},
	{
		ID:         "action-plans-people.list",
		Method:     "GET",
		Path:       "/actionPlansPeople",
		Summary:    "Follow Up Boss GET /actionPlansPeople. Source: https://docs.followupboss.com/reference/actionplanspeople-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("action-plans-people", "list", "Follow Up Boss GET /actionPlansPeople. Source: https://docs.followupboss.com/reference/actionplanspeople-get", "/actionPlansPeople"),
	},
	{
		ID:         "action-plans-people.update",
		Method:     "PUT",
		Path:       "/actionPlansPeople/{id}",
		Summary:    "Follow Up Boss PUT /actionPlansPeople/{id}. Source: https://docs.followupboss.com/reference/actionplanspeople-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("action-plans-people", "update", "Follow Up Boss PUT /actionPlansPeople/{id}. Source: https://docs.followupboss.com/reference/actionplanspeople-id-put", "/actionPlansPeople/{id}"),
	},
	{
		ID:         "appointment-outcomes.create",
		Method:     "POST",
		Path:       "/appointmentOutcomes",
		Summary:    "Follow Up Boss POST /appointmentOutcomes. Source: https://docs.followupboss.com/reference/appointmentoutcomes-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("appointment-outcomes", "create", "Follow Up Boss POST /appointmentOutcomes. Source: https://docs.followupboss.com/reference/appointmentoutcomes-post", "/appointmentOutcomes"),
	},
	{
		ID:         "appointment-outcomes.delete",
		Method:     "DELETE",
		Path:       "/appointmentOutcomes/{id}",
		Summary:    "Follow Up Boss DELETE /appointmentOutcomes/{id}. Source: https://docs.followupboss.com/reference/appointmentoutcomes-...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("appointment-outcomes", "delete", "Follow Up Boss DELETE /appointmentOutcomes/{id}. Source: https://docs.followupboss.com/reference/appointmentoutcomes-...", "/appointmentOutcomes/{id}"),
	},
	{
		ID:         "appointment-outcomes.get",
		Method:     "GET",
		Path:       "/appointmentOutcomes/{id}",
		Summary:    "Follow Up Boss GET /appointmentOutcomes/{id}. Source: https://docs.followupboss.com/reference/appointmentoutcomes-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("appointment-outcomes", "get", "Follow Up Boss GET /appointmentOutcomes/{id}. Source: https://docs.followupboss.com/reference/appointmentoutcomes-id-get", "/appointmentOutcomes/{id}"),
	},
	{
		ID:         "appointment-outcomes.list",
		Method:     "GET",
		Path:       "/appointmentOutcomes",
		Summary:    "Follow Up Boss GET /appointmentOutcomes. Source: https://docs.followupboss.com/reference/appointmentoutcomes-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("appointment-outcomes", "list", "Follow Up Boss GET /appointmentOutcomes. Source: https://docs.followupboss.com/reference/appointmentoutcomes-get", "/appointmentOutcomes"),
	},
	{
		ID:         "appointment-outcomes.update",
		Method:     "PUT",
		Path:       "/appointmentOutcomes/{id}",
		Summary:    "Follow Up Boss PUT /appointmentOutcomes/{id}. Source: https://docs.followupboss.com/reference/appointmentoutcomes-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("appointment-outcomes", "update", "Follow Up Boss PUT /appointmentOutcomes/{id}. Source: https://docs.followupboss.com/reference/appointmentoutcomes-id-put", "/appointmentOutcomes/{id}"),
	},
	{
		ID:         "appointment-types.create",
		Method:     "POST",
		Path:       "/appointmentTypes",
		Summary:    "Follow Up Boss POST /appointmentTypes. Source: https://docs.followupboss.com/reference/appointmenttypes-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("appointment-types", "create", "Follow Up Boss POST /appointmentTypes. Source: https://docs.followupboss.com/reference/appointmenttypes-post", "/appointmentTypes"),
	},
	{
		ID:         "appointment-types.delete",
		Method:     "DELETE",
		Path:       "/appointmentTypes/{id}",
		Summary:    "Follow Up Boss DELETE /appointmentTypes/{id}. Source: https://docs.followupboss.com/reference/appointmenttypes-id-delete",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("appointment-types", "delete", "Follow Up Boss DELETE /appointmentTypes/{id}. Source: https://docs.followupboss.com/reference/appointmenttypes-id-delete", "/appointmentTypes/{id}"),
	},
	{
		ID:         "appointment-types.get",
		Method:     "GET",
		Path:       "/appointmentTypes/{id}",
		Summary:    "Follow Up Boss GET /appointmentTypes/{id}. Source: https://docs.followupboss.com/reference/appointmenttypes-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("appointment-types", "get", "Follow Up Boss GET /appointmentTypes/{id}. Source: https://docs.followupboss.com/reference/appointmenttypes-id-get", "/appointmentTypes/{id}"),
	},
	{
		ID:         "appointment-types.list",
		Method:     "GET",
		Path:       "/appointmentTypes",
		Summary:    "Follow Up Boss GET /appointmentTypes. Source: https://docs.followupboss.com/reference/appointmenttypes-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("appointment-types", "list", "Follow Up Boss GET /appointmentTypes. Source: https://docs.followupboss.com/reference/appointmenttypes-get", "/appointmentTypes"),
	},
	{
		ID:         "appointment-types.update",
		Method:     "PUT",
		Path:       "/appointmentTypes/{id}",
		Summary:    "Follow Up Boss PUT /appointmentTypes/{id}. Source: https://docs.followupboss.com/reference/appointmenttypes-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("appointment-types", "update", "Follow Up Boss PUT /appointmentTypes/{id}. Source: https://docs.followupboss.com/reference/appointmenttypes-id-put", "/appointmentTypes/{id}"),
	},
	{
		ID:         "appointments.create",
		Method:     "POST",
		Path:       "/appointments",
		Summary:    "Follow Up Boss POST /appointments. Source: https://docs.followupboss.com/reference/appointments-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("appointments", "create", "Follow Up Boss POST /appointments. Source: https://docs.followupboss.com/reference/appointments-post", "/appointments"),
	},
	{
		ID:         "appointments.delete",
		Method:     "DELETE",
		Path:       "/appointments/{id}",
		Summary:    "Follow Up Boss DELETE /appointments/{id}. Source: https://docs.followupboss.com/reference/appointments-id-delete",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("appointments", "delete", "Follow Up Boss DELETE /appointments/{id}. Source: https://docs.followupboss.com/reference/appointments-id-delete", "/appointments/{id}"),
	},
	{
		ID:         "appointments.get",
		Method:     "GET",
		Path:       "/appointments/{id}",
		Summary:    "Follow Up Boss GET /appointments/{id}. Source: https://docs.followupboss.com/reference/appointments-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("appointments", "get", "Follow Up Boss GET /appointments/{id}. Source: https://docs.followupboss.com/reference/appointments-id-get", "/appointments/{id}"),
	},
	{
		ID:         "appointments.list",
		Method:     "GET",
		Path:       "/appointments",
		Summary:    "Follow Up Boss GET /appointments. Source: https://docs.followupboss.com/reference/appointments-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("appointments", "list", "Follow Up Boss GET /appointments. Source: https://docs.followupboss.com/reference/appointments-get", "/appointments"),
	},
	{
		ID:         "appointments.update",
		Method:     "PUT",
		Path:       "/appointments/{id}",
		Summary:    "Follow Up Boss PUT /appointments/{id}. Source: https://docs.followupboss.com/reference/appointments-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("appointments", "update", "Follow Up Boss PUT /appointments/{id}. Source: https://docs.followupboss.com/reference/appointments-id-put", "/appointments/{id}"),
	},
	{
		ID:         "automations.get",
		Method:     "GET",
		Path:       "/automations/{id}",
		Summary:    "Follow Up Boss GET /automations/{id}. Source: https://docs.followupboss.com/reference/automationsid",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("automations", "get", "Follow Up Boss GET /automations/{id}. Source: https://docs.followupboss.com/reference/automationsid", "/automations/{id}"),
	},
	{
		ID:         "automations.list",
		Method:     "GET",
		Path:       "/automations",
		Summary:    "Follow Up Boss GET /automations. Source: https://docs.followupboss.com/reference/automations",
		Positional: []string{},
		keywords:   codeOrchKeywords("automations", "list", "Follow Up Boss GET /automations. Source: https://docs.followupboss.com/reference/automations", "/automations"),
	},
	{
		ID:         "automations-people.create",
		Method:     "POST",
		Path:       "/automationsPeople",
		Summary:    "Follow Up Boss POST /automationsPeople. Source: https://docs.followupboss.com/reference/automationspeople-1",
		Positional: []string{},
		keywords:   codeOrchKeywords("automations-people", "create", "Follow Up Boss POST /automationsPeople. Source: https://docs.followupboss.com/reference/automationspeople-1", "/automationsPeople"),
	},
	{
		ID:         "automations-people.get",
		Method:     "GET",
		Path:       "/automationsPeople/{id}",
		Summary:    "Follow Up Boss GET /automationsPeople/{id}. Source: https://docs.followupboss.com/reference/automationspeopleid-1",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("automations-people", "get", "Follow Up Boss GET /automationsPeople/{id}. Source: https://docs.followupboss.com/reference/automationspeopleid-1", "/automationsPeople/{id}"),
	},
	{
		ID:         "automations-people.list",
		Method:     "GET",
		Path:       "/automationsPeople",
		Summary:    "Follow Up Boss GET /automationsPeople. Source: https://docs.followupboss.com/reference/automationspeople",
		Positional: []string{},
		keywords:   codeOrchKeywords("automations-people", "list", "Follow Up Boss GET /automationsPeople. Source: https://docs.followupboss.com/reference/automationspeople", "/automationsPeople"),
	},
	{
		ID:         "automations-people.update",
		Method:     "PUT",
		Path:       "/automationsPeople/{id}",
		Summary:    "Follow Up Boss PUT /automationsPeople/{id}. Source: https://docs.followupboss.com/reference/automationspeopleid",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("automations-people", "update", "Follow Up Boss PUT /automationsPeople/{id}. Source: https://docs.followupboss.com/reference/automationspeopleid", "/automationsPeople/{id}"),
	},
	{
		ID:         "calls.create",
		Method:     "POST",
		Path:       "/calls",
		Summary:    "Follow Up Boss POST /calls. Source: https://docs.followupboss.com/reference/calls-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("calls", "create", "Follow Up Boss POST /calls. Source: https://docs.followupboss.com/reference/calls-post", "/calls"),
	},
	{
		ID:         "calls.get",
		Method:     "GET",
		Path:       "/calls/{id}",
		Summary:    "Follow Up Boss GET /calls/{id}. Source: https://docs.followupboss.com/reference/calls-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("calls", "get", "Follow Up Boss GET /calls/{id}. Source: https://docs.followupboss.com/reference/calls-id-get", "/calls/{id}"),
	},
	{
		ID:         "calls.list",
		Method:     "GET",
		Path:       "/calls",
		Summary:    "Follow Up Boss GET /calls. Source: https://docs.followupboss.com/reference/calls-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("calls", "list", "Follow Up Boss GET /calls. Source: https://docs.followupboss.com/reference/calls-get", "/calls"),
	},
	{
		ID:         "calls.update",
		Method:     "PUT",
		Path:       "/calls/{id}",
		Summary:    "Follow Up Boss PUT /calls/{id}. Source: https://docs.followupboss.com/reference/calls-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("calls", "update", "Follow Up Boss PUT /calls/{id}. Source: https://docs.followupboss.com/reference/calls-id-put", "/calls/{id}"),
	},
	{
		ID:         "custom-fields.create",
		Method:     "POST",
		Path:       "/customFields",
		Summary:    "Follow Up Boss POST /customFields. Source: https://docs.followupboss.com/reference/customfields-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("custom-fields", "create", "Follow Up Boss POST /customFields. Source: https://docs.followupboss.com/reference/customfields-post", "/customFields"),
	},
	{
		ID:         "custom-fields.delete",
		Method:     "DELETE",
		Path:       "/customFields/{id}",
		Summary:    "Follow Up Boss DELETE /customFields/{id}. Source: https://docs.followupboss.com/reference/customfields-id-delete",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("custom-fields", "delete", "Follow Up Boss DELETE /customFields/{id}. Source: https://docs.followupboss.com/reference/customfields-id-delete", "/customFields/{id}"),
	},
	{
		ID:         "custom-fields.get",
		Method:     "GET",
		Path:       "/customFields/{id}",
		Summary:    "Follow Up Boss GET /customFields/{id}. Source: https://docs.followupboss.com/reference/customfields-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("custom-fields", "get", "Follow Up Boss GET /customFields/{id}. Source: https://docs.followupboss.com/reference/customfields-id-get", "/customFields/{id}"),
	},
	{
		ID:         "custom-fields.list",
		Method:     "GET",
		Path:       "/customFields",
		Summary:    "Follow Up Boss GET /customFields. Source: https://docs.followupboss.com/reference/customfields-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("custom-fields", "list", "Follow Up Boss GET /customFields. Source: https://docs.followupboss.com/reference/customfields-get", "/customFields"),
	},
	{
		ID:         "custom-fields.update",
		Method:     "PUT",
		Path:       "/customFields/{id}",
		Summary:    "Follow Up Boss PUT /customFields/{id}. Source: https://docs.followupboss.com/reference/customfields-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("custom-fields", "update", "Follow Up Boss PUT /customFields/{id}. Source: https://docs.followupboss.com/reference/customfields-id-put", "/customFields/{id}"),
	},
	{
		ID:         "deal-attachments.create",
		Method:     "POST",
		Path:       "/dealAttachments",
		Summary:    "Follow Up Boss POST /dealAttachments. Source: https://docs.followupboss.com/reference/dealattachments-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("deal-attachments", "create", "Follow Up Boss POST /dealAttachments. Source: https://docs.followupboss.com/reference/dealattachments-post", "/dealAttachments"),
	},
	{
		ID:         "deal-attachments.delete",
		Method:     "DELETE",
		Path:       "/dealAttachments/{id}",
		Summary:    "Follow Up Boss DELETE /dealAttachments/{id}. Source: https://docs.followupboss.com/reference/dealattachments-id-delete",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("deal-attachments", "delete", "Follow Up Boss DELETE /dealAttachments/{id}. Source: https://docs.followupboss.com/reference/dealattachments-id-delete", "/dealAttachments/{id}"),
	},
	{
		ID:         "deal-attachments.get",
		Method:     "GET",
		Path:       "/dealAttachments/{id}",
		Summary:    "Follow Up Boss GET /dealAttachments/{id}. Source: https://docs.followupboss.com/reference/dealattachments-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("deal-attachments", "get", "Follow Up Boss GET /dealAttachments/{id}. Source: https://docs.followupboss.com/reference/dealattachments-id-get", "/dealAttachments/{id}"),
	},
	{
		ID:         "deal-attachments.update",
		Method:     "PUT",
		Path:       "/dealAttachments/{id}",
		Summary:    "Follow Up Boss PUT /dealAttachments/{id}. Source: https://docs.followupboss.com/reference/dealattachments-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("deal-attachments", "update", "Follow Up Boss PUT /dealAttachments/{id}. Source: https://docs.followupboss.com/reference/dealattachments-id-put", "/dealAttachments/{id}"),
	},
	{
		ID:         "deal-custom-fields.create",
		Method:     "POST",
		Path:       "/dealCustomFields",
		Summary:    "Follow Up Boss POST /dealCustomFields. Source: https://docs.followupboss.com/reference/dealcustomfields-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("deal-custom-fields", "create", "Follow Up Boss POST /dealCustomFields. Source: https://docs.followupboss.com/reference/dealcustomfields-post", "/dealCustomFields"),
	},
	{
		ID:         "deal-custom-fields.delete",
		Method:     "DELETE",
		Path:       "/dealCustomFields/{id}",
		Summary:    "Follow Up Boss DELETE /dealCustomFields/{id}. Source: https://docs.followupboss.com/reference/dealcustomfields-id-delete",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("deal-custom-fields", "delete", "Follow Up Boss DELETE /dealCustomFields/{id}. Source: https://docs.followupboss.com/reference/dealcustomfields-id-delete", "/dealCustomFields/{id}"),
	},
	{
		ID:         "deal-custom-fields.get",
		Method:     "GET",
		Path:       "/dealCustomFields/{id}",
		Summary:    "Follow Up Boss GET /dealCustomFields/{id}. Source: https://docs.followupboss.com/reference/dealcustomfields-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("deal-custom-fields", "get", "Follow Up Boss GET /dealCustomFields/{id}. Source: https://docs.followupboss.com/reference/dealcustomfields-id-get", "/dealCustomFields/{id}"),
	},
	{
		ID:         "deal-custom-fields.list",
		Method:     "GET",
		Path:       "/dealCustomFields",
		Summary:    "Follow Up Boss GET /dealCustomFields. Source: https://docs.followupboss.com/reference/dealcustomfields-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("deal-custom-fields", "list", "Follow Up Boss GET /dealCustomFields. Source: https://docs.followupboss.com/reference/dealcustomfields-get", "/dealCustomFields"),
	},
	{
		ID:         "deal-custom-fields.update",
		Method:     "PUT",
		Path:       "/dealCustomFields/{id}",
		Summary:    "Follow Up Boss PUT /dealCustomFields/{id}. Source: https://docs.followupboss.com/reference/dealcustomfields-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("deal-custom-fields", "update", "Follow Up Boss PUT /dealCustomFields/{id}. Source: https://docs.followupboss.com/reference/dealcustomfields-id-put", "/dealCustomFields/{id}"),
	},
	{
		ID:         "deals.create",
		Method:     "POST",
		Path:       "/deals",
		Summary:    "Follow Up Boss POST /deals. Source: https://docs.followupboss.com/reference/deals-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("deals", "create", "Follow Up Boss POST /deals. Source: https://docs.followupboss.com/reference/deals-post", "/deals"),
	},
	{
		ID:         "deals.delete",
		Method:     "DELETE",
		Path:       "/deals/{id}",
		Summary:    "Follow Up Boss DELETE /deals/{id}. Source: https://docs.followupboss.com/reference/deals-id-delete",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("deals", "delete", "Follow Up Boss DELETE /deals/{id}. Source: https://docs.followupboss.com/reference/deals-id-delete", "/deals/{id}"),
	},
	{
		ID:         "deals.get",
		Method:     "GET",
		Path:       "/deals/{id}",
		Summary:    "Follow Up Boss GET /deals/{id}. Source: https://docs.followupboss.com/reference/deals-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("deals", "get", "Follow Up Boss GET /deals/{id}. Source: https://docs.followupboss.com/reference/deals-id-get", "/deals/{id}"),
	},
	{
		ID:         "deals.list",
		Method:     "GET",
		Path:       "/deals",
		Summary:    "Follow Up Boss GET /deals. Source: https://docs.followupboss.com/reference/deals-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("deals", "list", "Follow Up Boss GET /deals. Source: https://docs.followupboss.com/reference/deals-get", "/deals"),
	},
	{
		ID:         "deals.update",
		Method:     "PUT",
		Path:       "/deals/{id}",
		Summary:    "Follow Up Boss PUT /deals/{id}. Source: https://docs.followupboss.com/reference/deals-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("deals", "update", "Follow Up Boss PUT /deals/{id}. Source: https://docs.followupboss.com/reference/deals-id-put", "/deals/{id}"),
	},
	{
		ID:         "em-campaigns.create",
		Method:     "POST",
		Path:       "/emCampaigns",
		Summary:    "Follow Up Boss POST /emCampaigns. Source: https://docs.followupboss.com/reference/emcampaigns-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("em-campaigns", "create", "Follow Up Boss POST /emCampaigns. Source: https://docs.followupboss.com/reference/emcampaigns-post", "/emCampaigns"),
	},
	{
		ID:         "em-campaigns.list",
		Method:     "GET",
		Path:       "/emCampaigns",
		Summary:    "Follow Up Boss GET /emCampaigns. Source: https://docs.followupboss.com/reference/emcampaigns-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("em-campaigns", "list", "Follow Up Boss GET /emCampaigns. Source: https://docs.followupboss.com/reference/emcampaigns-get", "/emCampaigns"),
	},
	{
		ID:         "em-campaigns.update",
		Method:     "PUT",
		Path:       "/emCampaigns/{id}",
		Summary:    "Follow Up Boss PUT /emCampaigns/{id}. Source: https://docs.followupboss.com/reference/emcampaigns-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("em-campaigns", "update", "Follow Up Boss PUT /emCampaigns/{id}. Source: https://docs.followupboss.com/reference/emcampaigns-id-put", "/emCampaigns/{id}"),
	},
	{
		ID:         "em-events.create",
		Method:     "POST",
		Path:       "/emEvents",
		Summary:    "Follow Up Boss POST /emEvents. Source: https://docs.followupboss.com/reference/emevents-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("em-events", "create", "Follow Up Boss POST /emEvents. Source: https://docs.followupboss.com/reference/emevents-post", "/emEvents"),
	},
	{
		ID:         "em-events.list",
		Method:     "GET",
		Path:       "/emEvents",
		Summary:    "Follow Up Boss GET /emEvents. Source: https://docs.followupboss.com/reference/emevents-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("em-events", "list", "Follow Up Boss GET /emEvents. Source: https://docs.followupboss.com/reference/emevents-get", "/emEvents"),
	},
	{
		ID:         "events.create",
		Method:     "POST",
		Path:       "/events",
		Summary:    "Follow Up Boss POST /events. Source: https://docs.followupboss.com/reference/events-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("events", "create", "Follow Up Boss POST /events. Source: https://docs.followupboss.com/reference/events-post", "/events"),
	},
	{
		ID:         "events.get",
		Method:     "GET",
		Path:       "/events/{id}",
		Summary:    "Follow Up Boss GET /events/{id}. Source: https://docs.followupboss.com/reference/events-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("events", "get", "Follow Up Boss GET /events/{id}. Source: https://docs.followupboss.com/reference/events-id-get", "/events/{id}"),
	},
	{
		ID:         "events.list",
		Method:     "GET",
		Path:       "/events",
		Summary:    "Follow Up Boss GET /events. Source: https://docs.followupboss.com/reference/getting-started",
		Positional: []string{},
		keywords:   codeOrchKeywords("events", "list", "Follow Up Boss GET /events. Source: https://docs.followupboss.com/reference/getting-started", "/events"),
	},
	{
		ID:         "groups.create",
		Method:     "POST",
		Path:       "/groups",
		Summary:    "Follow Up Boss POST /groups. Source: https://docs.followupboss.com/reference/groups-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("groups", "create", "Follow Up Boss POST /groups. Source: https://docs.followupboss.com/reference/groups-post", "/groups"),
	},
	{
		ID:         "groups.delete",
		Method:     "DELETE",
		Path:       "/groups/{id}",
		Summary:    "Follow Up Boss DELETE /groups/{id}. Source: https://docs.followupboss.com/reference/groups-id-delete",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("groups", "delete", "Follow Up Boss DELETE /groups/{id}. Source: https://docs.followupboss.com/reference/groups-id-delete", "/groups/{id}"),
	},
	{
		ID:         "groups.get",
		Method:     "GET",
		Path:       "/groups/{id}",
		Summary:    "Follow Up Boss GET /groups/{id}. Source: https://docs.followupboss.com/reference/groups-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("groups", "get", "Follow Up Boss GET /groups/{id}. Source: https://docs.followupboss.com/reference/groups-id-get", "/groups/{id}"),
	},
	{
		ID:         "groups.list",
		Method:     "GET",
		Path:       "/groups",
		Summary:    "Follow Up Boss GET /groups. Source: https://docs.followupboss.com/reference/groups-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("groups", "list", "Follow Up Boss GET /groups. Source: https://docs.followupboss.com/reference/groups-get", "/groups"),
	},
	{
		ID:         "groups.round-robin-list",
		Method:     "GET",
		Path:       "/groups/roundRobin",
		Summary:    "Follow Up Boss GET /groups/roundRobin. Source: https://docs.followupboss.com/reference/groups-roundrobin-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("groups", "round-robin-list", "Follow Up Boss GET /groups/roundRobin. Source: https://docs.followupboss.com/reference/groups-roundrobin-get", "/groups/roundRobin"),
	},
	{
		ID:         "groups.update",
		Method:     "PUT",
		Path:       "/groups/{id}",
		Summary:    "Follow Up Boss PUT /groups/{id}. Source: https://docs.followupboss.com/reference/groups-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("groups", "update", "Follow Up Boss PUT /groups/{id}. Source: https://docs.followupboss.com/reference/groups-id-put", "/groups/{id}"),
	},
	{
		ID:         "identity.list",
		Method:     "GET",
		Path:       "/identity",
		Summary:    "Follow Up Boss GET /identity. Source: https://docs.followupboss.com/reference/identity",
		Positional: []string{},
		keywords:   codeOrchKeywords("identity", "list", "Follow Up Boss GET /identity. Source: https://docs.followupboss.com/reference/identity", "/identity"),
	},
	{
		ID:         "me.list",
		Method:     "GET",
		Path:       "/me",
		Summary:    "Follow Up Boss GET /me. Source: https://docs.followupboss.com/reference/me",
		Positional: []string{},
		keywords:   codeOrchKeywords("me", "list", "Follow Up Boss GET /me. Source: https://docs.followupboss.com/reference/me", "/me"),
	},
	{
		ID:         "notes.create",
		Method:     "POST",
		Path:       "/notes",
		Summary:    "Follow Up Boss POST /notes. Source: https://docs.followupboss.com/reference/notes-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("notes", "create", "Follow Up Boss POST /notes. Source: https://docs.followupboss.com/reference/notes-post", "/notes"),
	},
	{
		ID:         "notes.delete",
		Method:     "DELETE",
		Path:       "/notes/{id}",
		Summary:    "Follow Up Boss DELETE /notes/{id}. Source: https://docs.followupboss.com/reference/notes-id-delete",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("notes", "delete", "Follow Up Boss DELETE /notes/{id}. Source: https://docs.followupboss.com/reference/notes-id-delete", "/notes/{id}"),
	},
	{
		ID:         "notes.get",
		Method:     "GET",
		Path:       "/notes/{id}",
		Summary:    "Follow Up Boss GET /notes/{id}. Source: https://docs.followupboss.com/reference/notes-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("notes", "get", "Follow Up Boss GET /notes/{id}. Source: https://docs.followupboss.com/reference/notes-id-get", "/notes/{id}"),
	},
	{
		ID:         "notes.update",
		Method:     "PUT",
		Path:       "/notes/{id}",
		Summary:    "Follow Up Boss PUT /notes/{id}. Source: https://docs.followupboss.com/reference/notes-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("notes", "update", "Follow Up Boss PUT /notes/{id}. Source: https://docs.followupboss.com/reference/notes-id-put", "/notes/{id}"),
	},
	{
		ID:         "people.check-duplicate-list",
		Method:     "GET",
		Path:       "/people/checkDuplicate",
		Summary:    "Follow Up Boss GET /people/checkDuplicate. Source: https://docs.followupboss.com/reference/people-checkduplicate",
		Positional: []string{},
		keywords:   codeOrchKeywords("people", "check-duplicate-list", "Follow Up Boss GET /people/checkDuplicate. Source: https://docs.followupboss.com/reference/people-checkduplicate", "/people/checkDuplicate"),
	},
	{
		ID:         "people.claim-create",
		Method:     "POST",
		Path:       "/people/claim",
		Summary:    "Follow Up Boss POST /people/claim. Source: https://docs.followupboss.com/reference/people-claim",
		Positional: []string{},
		keywords:   codeOrchKeywords("people", "claim-create", "Follow Up Boss POST /people/claim. Source: https://docs.followupboss.com/reference/people-claim", "/people/claim"),
	},
	{
		ID:         "people.create",
		Method:     "POST",
		Path:       "/people",
		Summary:    "Follow Up Boss POST /people. Source: https://docs.followupboss.com/reference/people-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("people", "create", "Follow Up Boss POST /people. Source: https://docs.followupboss.com/reference/people-post", "/people"),
	},
	{
		ID:         "people.delete",
		Method:     "DELETE",
		Path:       "/people/{id}",
		Summary:    "Follow Up Boss DELETE /people/{id}. Source: https://docs.followupboss.com/reference/people-id-delete",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("people", "delete", "Follow Up Boss DELETE /people/{id}. Source: https://docs.followupboss.com/reference/people-id-delete", "/people/{id}"),
	},
	{
		ID:         "people.get",
		Method:     "GET",
		Path:       "/people/{id}",
		Summary:    "Follow Up Boss GET /people/{id}. Source: https://docs.followupboss.com/reference/people-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("people", "get", "Follow Up Boss GET /people/{id}. Source: https://docs.followupboss.com/reference/people-id-get", "/people/{id}"),
	},
	{
		ID:         "people.ignore-unclaimed-create",
		Method:     "POST",
		Path:       "/people/ignoreUnclaimed",
		Summary:    "Follow Up Boss POST /people/ignoreUnclaimed. Source: https://docs.followupboss.com/reference/people-ignoreunclaimed",
		Positional: []string{},
		keywords:   codeOrchKeywords("people", "ignore-unclaimed-create", "Follow Up Boss POST /people/ignoreUnclaimed. Source: https://docs.followupboss.com/reference/people-ignoreunclaimed", "/people/ignoreUnclaimed"),
	},
	{
		ID:         "people.list",
		Method:     "GET",
		Path:       "/people",
		Summary:    "Follow Up Boss GET /people. Source: https://docs.followupboss.com/reference/people-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("people", "list", "Follow Up Boss GET /people. Source: https://docs.followupboss.com/reference/people-get", "/people"),
	},
	{
		ID:         "people.unclaimed-list",
		Method:     "GET",
		Path:       "/people/unclaimed",
		Summary:    "Follow Up Boss GET /people/unclaimed. Source: https://docs.followupboss.com/reference/peopleunclaimed",
		Positional: []string{},
		keywords:   codeOrchKeywords("people", "unclaimed-list", "Follow Up Boss GET /people/unclaimed. Source: https://docs.followupboss.com/reference/peopleunclaimed", "/people/unclaimed"),
	},
	{
		ID:         "people.update",
		Method:     "PUT",
		Path:       "/people/{id}",
		Summary:    "Follow Up Boss PUT /people/{id}. Source: https://docs.followupboss.com/reference/people-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("people", "update", "Follow Up Boss PUT /people/{id}. Source: https://docs.followupboss.com/reference/people-id-put", "/people/{id}"),
	},
	{
		ID:         "people-relationships.create",
		Method:     "POST",
		Path:       "/peopleRelationships",
		Summary:    "Follow Up Boss POST /peopleRelationships. Source: https://docs.followupboss.com/reference/peoplerelationships-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("people-relationships", "create", "Follow Up Boss POST /peopleRelationships. Source: https://docs.followupboss.com/reference/peoplerelationships-post", "/peopleRelationships"),
	},
	{
		ID:         "people-relationships.delete",
		Method:     "DELETE",
		Path:       "/peopleRelationships/{id}",
		Summary:    "Follow Up Boss DELETE /peopleRelationships/{id}. Source: https://docs.followupboss.com/reference/peoplerelationships-...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("people-relationships", "delete", "Follow Up Boss DELETE /peopleRelationships/{id}. Source: https://docs.followupboss.com/reference/peoplerelationships-...", "/peopleRelationships/{id}"),
	},
	{
		ID:         "people-relationships.get",
		Method:     "GET",
		Path:       "/peopleRelationships/{id}",
		Summary:    "Follow Up Boss GET /peopleRelationships/{id}. Source: https://docs.followupboss.com/reference/peoplerelationships-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("people-relationships", "get", "Follow Up Boss GET /peopleRelationships/{id}. Source: https://docs.followupboss.com/reference/peoplerelationships-id-get", "/peopleRelationships/{id}"),
	},
	{
		ID:         "people-relationships.list",
		Method:     "GET",
		Path:       "/peopleRelationships",
		Summary:    "Follow Up Boss GET /peopleRelationships. Source: https://docs.followupboss.com/reference/peoplerelationships",
		Positional: []string{},
		keywords:   codeOrchKeywords("people-relationships", "list", "Follow Up Boss GET /peopleRelationships. Source: https://docs.followupboss.com/reference/peoplerelationships", "/peopleRelationships"),
	},
	{
		ID:         "people-relationships.update",
		Method:     "PUT",
		Path:       "/peopleRelationships/{id}",
		Summary:    "Follow Up Boss PUT /peopleRelationships/{id}. Source: https://docs.followupboss.com/reference/peoplerelationships-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("people-relationships", "update", "Follow Up Boss PUT /peopleRelationships/{id}. Source: https://docs.followupboss.com/reference/peoplerelationships-id-put", "/peopleRelationships/{id}"),
	},
	{
		ID:         "person-attachments.create",
		Method:     "POST",
		Path:       "/personAttachments",
		Summary:    "Follow Up Boss POST /personAttachments. Source: https://docs.followupboss.com/reference/personattachments-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("person-attachments", "create", "Follow Up Boss POST /personAttachments. Source: https://docs.followupboss.com/reference/personattachments-post", "/personAttachments"),
	},
	{
		ID:         "person-attachments.delete",
		Method:     "DELETE",
		Path:       "/personAttachments/{id}",
		Summary:    "Follow Up Boss DELETE /personAttachments/{id}. Source: https://docs.followupboss.com/reference/personattachments-id-d...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("person-attachments", "delete", "Follow Up Boss DELETE /personAttachments/{id}. Source: https://docs.followupboss.com/reference/personattachments-id-d...", "/personAttachments/{id}"),
	},
	{
		ID:         "person-attachments.get",
		Method:     "GET",
		Path:       "/personAttachments/{id}",
		Summary:    "Follow Up Boss GET /personAttachments/{id}. Source: https://docs.followupboss.com/reference/personattachments-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("person-attachments", "get", "Follow Up Boss GET /personAttachments/{id}. Source: https://docs.followupboss.com/reference/personattachments-id-get", "/personAttachments/{id}"),
	},
	{
		ID:         "person-attachments.update",
		Method:     "PUT",
		Path:       "/personAttachments/{id}",
		Summary:    "Follow Up Boss PUT /personAttachments/{id}. Source: https://docs.followupboss.com/reference/personattachments-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("person-attachments", "update", "Follow Up Boss PUT /personAttachments/{id}. Source: https://docs.followupboss.com/reference/personattachments-id-put", "/personAttachments/{id}"),
	},
	{
		ID:         "pipelines.create",
		Method:     "POST",
		Path:       "/pipelines",
		Summary:    "Follow Up Boss POST /pipelines. Source: https://docs.followupboss.com/reference/pipelines-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("pipelines", "create", "Follow Up Boss POST /pipelines. Source: https://docs.followupboss.com/reference/pipelines-post", "/pipelines"),
	},
	{
		ID:         "pipelines.delete",
		Method:     "DELETE",
		Path:       "/pipelines/{id}",
		Summary:    "Follow Up Boss DELETE /pipelines/{id}. Source: https://docs.followupboss.com/reference/pipelines-id-delete",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("pipelines", "delete", "Follow Up Boss DELETE /pipelines/{id}. Source: https://docs.followupboss.com/reference/pipelines-id-delete", "/pipelines/{id}"),
	},
	{
		ID:         "pipelines.get",
		Method:     "GET",
		Path:       "/pipelines/{id}",
		Summary:    "Follow Up Boss GET /pipelines/{id}. Source: https://docs.followupboss.com/reference/pipelines-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("pipelines", "get", "Follow Up Boss GET /pipelines/{id}. Source: https://docs.followupboss.com/reference/pipelines-id-get", "/pipelines/{id}"),
	},
	{
		ID:         "pipelines.list",
		Method:     "GET",
		Path:       "/pipelines",
		Summary:    "Follow Up Boss GET /pipelines. Source: https://docs.followupboss.com/reference/pipelines-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("pipelines", "list", "Follow Up Boss GET /pipelines. Source: https://docs.followupboss.com/reference/pipelines-get", "/pipelines"),
	},
	{
		ID:         "pipelines.update",
		Method:     "PUT",
		Path:       "/pipelines/{id}",
		Summary:    "Follow Up Boss PUT /pipelines/{id}. Source: https://docs.followupboss.com/reference/pipelines-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("pipelines", "update", "Follow Up Boss PUT /pipelines/{id}. Source: https://docs.followupboss.com/reference/pipelines-id-put", "/pipelines/{id}"),
	},
	{
		ID:         "ponds.create",
		Method:     "POST",
		Path:       "/ponds",
		Summary:    "Follow Up Boss POST /ponds. Source: https://docs.followupboss.com/reference/ponds-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("ponds", "create", "Follow Up Boss POST /ponds. Source: https://docs.followupboss.com/reference/ponds-post", "/ponds"),
	},
	{
		ID:         "ponds.delete",
		Method:     "DELETE",
		Path:       "/ponds/{id}",
		Summary:    "Follow Up Boss DELETE /ponds/{id}. Source: https://docs.followupboss.com/reference/ponds-id-delete",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("ponds", "delete", "Follow Up Boss DELETE /ponds/{id}. Source: https://docs.followupboss.com/reference/ponds-id-delete", "/ponds/{id}"),
	},
	{
		ID:         "ponds.get",
		Method:     "GET",
		Path:       "/ponds/{id}",
		Summary:    "Follow Up Boss GET /ponds/{id}. Source: https://docs.followupboss.com/reference/ponds-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("ponds", "get", "Follow Up Boss GET /ponds/{id}. Source: https://docs.followupboss.com/reference/ponds-id-get", "/ponds/{id}"),
	},
	{
		ID:         "ponds.list",
		Method:     "GET",
		Path:       "/ponds",
		Summary:    "Follow Up Boss GET /ponds. Source: https://docs.followupboss.com/reference/ponds-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("ponds", "list", "Follow Up Boss GET /ponds. Source: https://docs.followupboss.com/reference/ponds-get", "/ponds"),
	},
	{
		ID:         "ponds.update",
		Method:     "PUT",
		Path:       "/ponds/{id}",
		Summary:    "Follow Up Boss PUT /ponds/{id}. Source: https://docs.followupboss.com/reference/ponds-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("ponds", "update", "Follow Up Boss PUT /ponds/{id}. Source: https://docs.followupboss.com/reference/ponds-id-put", "/ponds/{id}"),
	},
	{
		ID:         "reactions.get",
		Method:     "GET",
		Path:       "/reactions/{id}",
		Summary:    "Follow Up Boss GET /reactions/{id}. Source: https://docs.followupboss.com/reference/reactions",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("reactions", "get", "Follow Up Boss GET /reactions/{id}. Source: https://docs.followupboss.com/reference/reactions", "/reactions/{id}"),
	},
	{
		ID:         "reactions.ref-type-ref-id-create",
		Method:     "POST",
		Path:       "/reactions/{refType}/{refId}",
		Summary:    "Follow Up Boss POST /reactions/{refType}/{refId}. Source: https://docs.followupboss.com/reference/reactions-reftype-r...",
		Positional: []string{"refType", "refId"},
		keywords:   codeOrchKeywords("reactions", "ref-type-ref-id-create", "Follow Up Boss POST /reactions/{refType}/{refId}. Source: https://docs.followupboss.com/reference/reactions-reftype-r...", "/reactions/{refType}/{refId}"),
	},
	{
		ID:         "reactions.ref-type-ref-id-delete",
		Method:     "DELETE",
		Path:       "/reactions/{refType}/{refId}",
		Summary:    "Follow Up Boss DELETE /reactions/{refType}/{refId}. Source: https://docs.followupboss.com/reference/reactions-reftype...",
		Positional: []string{"refType", "refId"},
		keywords:   codeOrchKeywords("reactions", "ref-type-ref-id-delete", "Follow Up Boss DELETE /reactions/{refType}/{refId}. Source: https://docs.followupboss.com/reference/reactions-reftype...", "/reactions/{refType}/{refId}"),
	},
	{
		ID:         "smart-lists.get",
		Method:     "GET",
		Path:       "/smartLists/{id}",
		Summary:    "Follow Up Boss GET /smartLists/{id}. Source: https://docs.followupboss.com/reference/smartlist-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("smart-lists", "get", "Follow Up Boss GET /smartLists/{id}. Source: https://docs.followupboss.com/reference/smartlist-id-get", "/smartLists/{id}"),
	},
	{
		ID:         "smart-lists.list",
		Method:     "GET",
		Path:       "/smartLists",
		Summary:    "Follow Up Boss GET /smartLists. Source: https://docs.followupboss.com/reference/smartlists-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("smart-lists", "list", "Follow Up Boss GET /smartLists. Source: https://docs.followupboss.com/reference/smartlists-get", "/smartLists"),
	},
	{
		ID:         "stages.create",
		Method:     "POST",
		Path:       "/stages",
		Summary:    "Follow Up Boss POST /stages. Source: https://docs.followupboss.com/reference/stages-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("stages", "create", "Follow Up Boss POST /stages. Source: https://docs.followupboss.com/reference/stages-post", "/stages"),
	},
	{
		ID:         "stages.delete",
		Method:     "DELETE",
		Path:       "/stages/{id}",
		Summary:    "Follow Up Boss DELETE /stages/{id}. Source: https://docs.followupboss.com/reference/stage-id-delete",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("stages", "delete", "Follow Up Boss DELETE /stages/{id}. Source: https://docs.followupboss.com/reference/stage-id-delete", "/stages/{id}"),
	},
	{
		ID:         "stages.get",
		Method:     "GET",
		Path:       "/stages/{id}",
		Summary:    "Follow Up Boss GET /stages/{id}. Source: https://docs.followupboss.com/reference/stages-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("stages", "get", "Follow Up Boss GET /stages/{id}. Source: https://docs.followupboss.com/reference/stages-id-get", "/stages/{id}"),
	},
	{
		ID:         "stages.list",
		Method:     "GET",
		Path:       "/stages",
		Summary:    "Follow Up Boss GET /stages. Source: https://docs.followupboss.com/reference/stages-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("stages", "list", "Follow Up Boss GET /stages. Source: https://docs.followupboss.com/reference/stages-get", "/stages"),
	},
	{
		ID:         "stages.update",
		Method:     "PUT",
		Path:       "/stages/{id}",
		Summary:    "Follow Up Boss PUT /stages/{id}. Source: https://docs.followupboss.com/reference/stages-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("stages", "update", "Follow Up Boss PUT /stages/{id}. Source: https://docs.followupboss.com/reference/stages-id-put", "/stages/{id}"),
	},
	{
		ID:         "tasks.create",
		Method:     "POST",
		Path:       "/tasks",
		Summary:    "Follow Up Boss POST /tasks. Source: https://docs.followupboss.com/reference/tasks-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("tasks", "create", "Follow Up Boss POST /tasks. Source: https://docs.followupboss.com/reference/tasks-post", "/tasks"),
	},
	{
		ID:         "tasks.delete",
		Method:     "DELETE",
		Path:       "/tasks/{id}",
		Summary:    "Follow Up Boss DELETE /tasks/{id}. Source: https://docs.followupboss.com/reference/tasks-id-delete",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("tasks", "delete", "Follow Up Boss DELETE /tasks/{id}. Source: https://docs.followupboss.com/reference/tasks-id-delete", "/tasks/{id}"),
	},
	{
		ID:         "tasks.get",
		Method:     "GET",
		Path:       "/tasks/{id}",
		Summary:    "Follow Up Boss GET /tasks/{id}. Source: https://docs.followupboss.com/reference/tasks-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("tasks", "get", "Follow Up Boss GET /tasks/{id}. Source: https://docs.followupboss.com/reference/tasks-id-get", "/tasks/{id}"),
	},
	{
		ID:         "tasks.list",
		Method:     "GET",
		Path:       "/tasks",
		Summary:    "Follow Up Boss GET /tasks. Source: https://docs.followupboss.com/reference/tasks-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("tasks", "list", "Follow Up Boss GET /tasks. Source: https://docs.followupboss.com/reference/tasks-get", "/tasks"),
	},
	{
		ID:         "tasks.update",
		Method:     "PUT",
		Path:       "/tasks/{id}",
		Summary:    "Follow Up Boss PUT /tasks/{id}. Source: https://docs.followupboss.com/reference/tasks-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("tasks", "update", "Follow Up Boss PUT /tasks/{id}. Source: https://docs.followupboss.com/reference/tasks-id-put", "/tasks/{id}"),
	},
	{
		ID:         "team-inboxes.list",
		Method:     "GET",
		Path:       "/teamInboxes",
		Summary:    "Follow Up Boss GET /teamInboxes. Source: https://docs.followupboss.com/reference/teaminboxes",
		Positional: []string{},
		keywords:   codeOrchKeywords("team-inboxes", "list", "Follow Up Boss GET /teamInboxes. Source: https://docs.followupboss.com/reference/teaminboxes", "/teamInboxes"),
	},
	{
		ID:         "teams.create",
		Method:     "POST",
		Path:       "/teams",
		Summary:    "Follow Up Boss POST /teams. Source: https://docs.followupboss.com/reference/teams-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("teams", "create", "Follow Up Boss POST /teams. Source: https://docs.followupboss.com/reference/teams-post", "/teams"),
	},
	{
		ID:         "teams.delete",
		Method:     "DELETE",
		Path:       "/teams/{id}",
		Summary:    "Follow Up Boss DELETE /teams/{id}. Source: https://docs.followupboss.com/reference/teams-id-delete",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("teams", "delete", "Follow Up Boss DELETE /teams/{id}. Source: https://docs.followupboss.com/reference/teams-id-delete", "/teams/{id}"),
	},
	{
		ID:         "teams.get",
		Method:     "GET",
		Path:       "/teams/{id}",
		Summary:    "Follow Up Boss GET /teams/{id}. Source: https://docs.followupboss.com/reference/teams-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("teams", "get", "Follow Up Boss GET /teams/{id}. Source: https://docs.followupboss.com/reference/teams-id-get", "/teams/{id}"),
	},
	{
		ID:         "teams.list",
		Method:     "GET",
		Path:       "/teams",
		Summary:    "Follow Up Boss GET /teams. Source: https://docs.followupboss.com/reference/teams-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("teams", "list", "Follow Up Boss GET /teams. Source: https://docs.followupboss.com/reference/teams-get", "/teams"),
	},
	{
		ID:         "teams.update",
		Method:     "PUT",
		Path:       "/teams/{id}",
		Summary:    "Follow Up Boss PUT /teams/{id}. Source: https://docs.followupboss.com/reference/teams-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("teams", "update", "Follow Up Boss PUT /teams/{id}. Source: https://docs.followupboss.com/reference/teams-id-put", "/teams/{id}"),
	},
	{
		ID:         "templates.create",
		Method:     "POST",
		Path:       "/templates",
		Summary:    "Follow Up Boss POST /templates. Source: https://docs.followupboss.com/reference/templates-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("templates", "create", "Follow Up Boss POST /templates. Source: https://docs.followupboss.com/reference/templates-post", "/templates"),
	},
	{
		ID:         "templates.delete",
		Method:     "DELETE",
		Path:       "/templates/{id}",
		Summary:    "Follow Up Boss DELETE /templates/{id}. Source: https://docs.followupboss.com/reference/templates-id-delete",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("templates", "delete", "Follow Up Boss DELETE /templates/{id}. Source: https://docs.followupboss.com/reference/templates-id-delete", "/templates/{id}"),
	},
	{
		ID:         "templates.get",
		Method:     "GET",
		Path:       "/templates/{id}",
		Summary:    "Follow Up Boss GET /templates/{id}. Source: https://docs.followupboss.com/reference/templates-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("templates", "get", "Follow Up Boss GET /templates/{id}. Source: https://docs.followupboss.com/reference/templates-id-get", "/templates/{id}"),
	},
	{
		ID:         "templates.list",
		Method:     "GET",
		Path:       "/templates",
		Summary:    "Follow Up Boss GET /templates. Source: https://docs.followupboss.com/reference/templates-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("templates", "list", "Follow Up Boss GET /templates. Source: https://docs.followupboss.com/reference/templates-get", "/templates"),
	},
	{
		ID:         "templates.merge-create",
		Method:     "POST",
		Path:       "/templates/merge",
		Summary:    "Follow Up Boss POST /templates/merge. Source: https://docs.followupboss.com/reference/templates-merge",
		Positional: []string{},
		keywords:   codeOrchKeywords("templates", "merge-create", "Follow Up Boss POST /templates/merge. Source: https://docs.followupboss.com/reference/templates-merge", "/templates/merge"),
	},
	{
		ID:         "templates.update",
		Method:     "PUT",
		Path:       "/templates/{id}",
		Summary:    "Follow Up Boss PUT /templates/{id}. Source: https://docs.followupboss.com/reference/templates-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("templates", "update", "Follow Up Boss PUT /templates/{id}. Source: https://docs.followupboss.com/reference/templates-id-put", "/templates/{id}"),
	},
	{
		ID:         "text-message-templates.create",
		Method:     "POST",
		Path:       "/textMessageTemplates",
		Summary:    "Follow Up Boss POST /textMessageTemplates. Source: https://docs.followupboss.com/reference/textmessagetemplates-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("text-message-templates", "create", "Follow Up Boss POST /textMessageTemplates. Source: https://docs.followupboss.com/reference/textmessagetemplates-post", "/textMessageTemplates"),
	},
	{
		ID:         "text-message-templates.delete",
		Method:     "DELETE",
		Path:       "/textMessageTemplates/{id}",
		Summary:    "Follow Up Boss DELETE /textMessageTemplates/{id}. Source: https://docs.followupboss.com/reference/textmessagetemplate...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("text-message-templates", "delete", "Follow Up Boss DELETE /textMessageTemplates/{id}. Source: https://docs.followupboss.com/reference/textmessagetemplate...", "/textMessageTemplates/{id}"),
	},
	{
		ID:         "text-message-templates.get",
		Method:     "GET",
		Path:       "/textMessageTemplates/{id}",
		Summary:    "Follow Up Boss GET /textMessageTemplates/{id}. Source: https://docs.followupboss.com/reference/textmessagetemplates-i...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("text-message-templates", "get", "Follow Up Boss GET /textMessageTemplates/{id}. Source: https://docs.followupboss.com/reference/textmessagetemplates-i...", "/textMessageTemplates/{id}"),
	},
	{
		ID:         "text-message-templates.list",
		Method:     "GET",
		Path:       "/textMessageTemplates",
		Summary:    "Follow Up Boss GET /textMessageTemplates. Source: https://docs.followupboss.com/reference/textmessagetemplates-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("text-message-templates", "list", "Follow Up Boss GET /textMessageTemplates. Source: https://docs.followupboss.com/reference/textmessagetemplates-get", "/textMessageTemplates"),
	},
	{
		ID:         "text-message-templates.merge-create",
		Method:     "POST",
		Path:       "/textMessageTemplates/merge",
		Summary:    "Follow Up Boss POST /textMessageTemplates/merge. Source: https://docs.followupboss.com/reference/textmessagetemplates...",
		Positional: []string{},
		keywords:   codeOrchKeywords("text-message-templates", "merge-create", "Follow Up Boss POST /textMessageTemplates/merge. Source: https://docs.followupboss.com/reference/textmessagetemplates...", "/textMessageTemplates/merge"),
	},
	{
		ID:         "text-message-templates.update",
		Method:     "PUT",
		Path:       "/textMessageTemplates/{id}",
		Summary:    "Follow Up Boss PUT /textMessageTemplates/{id}. Source: https://docs.followupboss.com/reference/textmessagetemplates-i...",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("text-message-templates", "update", "Follow Up Boss PUT /textMessageTemplates/{id}. Source: https://docs.followupboss.com/reference/textmessagetemplates-i...", "/textMessageTemplates/{id}"),
	},
	{
		ID:         "text-messages.create",
		Method:     "POST",
		Path:       "/textMessages",
		Summary:    "Follow Up Boss POST /textMessages. Source: https://docs.followupboss.com/reference/textmessages-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("text-messages", "create", "Follow Up Boss POST /textMessages. Source: https://docs.followupboss.com/reference/textmessages-post", "/textMessages"),
	},
	{
		ID:         "text-messages.get",
		Method:     "GET",
		Path:       "/textMessages/{id}",
		Summary:    "Follow Up Boss GET /textMessages/{id}. Source: https://docs.followupboss.com/reference/textmessages-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("text-messages", "get", "Follow Up Boss GET /textMessages/{id}. Source: https://docs.followupboss.com/reference/textmessages-id-get", "/textMessages/{id}"),
	},
	{
		ID:         "text-messages.list",
		Method:     "GET",
		Path:       "/textMessages",
		Summary:    "Follow Up Boss GET /textMessages. Source: https://docs.followupboss.com/reference/textmessages-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("text-messages", "list", "Follow Up Boss GET /textMessages. Source: https://docs.followupboss.com/reference/textmessages-get", "/textMessages"),
	},
	{
		ID:         "threaded-replies.get",
		Method:     "GET",
		Path:       "/threadedReplies/{id}",
		Summary:    "Follow Up Boss GET /threadedReplies/{id}. Source: https://docs.followupboss.com/reference/threaded-replies",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("threaded-replies", "get", "Follow Up Boss GET /threadedReplies/{id}. Source: https://docs.followupboss.com/reference/threaded-replies", "/threadedReplies/{id}"),
	},
	{
		ID:         "timeframes.list",
		Method:     "GET",
		Path:       "/timeframes",
		Summary:    "Follow Up Boss GET /timeframes. Source: https://docs.followupboss.com/reference/timeframes-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("timeframes", "list", "Follow Up Boss GET /timeframes. Source: https://docs.followupboss.com/reference/timeframes-get", "/timeframes"),
	},
	{
		ID:         "users.delete",
		Method:     "DELETE",
		Path:       "/users/{id}",
		Summary:    "Follow Up Boss DELETE /users/{id}. Source: https://docs.followupboss.com/reference/users-id-delete",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("users", "delete", "Follow Up Boss DELETE /users/{id}. Source: https://docs.followupboss.com/reference/users-id-delete", "/users/{id}"),
	},
	{
		ID:         "users.get",
		Method:     "GET",
		Path:       "/users/{id}",
		Summary:    "Follow Up Boss GET /users/{id}. Source: https://docs.followupboss.com/reference/users-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("users", "get", "Follow Up Boss GET /users/{id}. Source: https://docs.followupboss.com/reference/users-id-get", "/users/{id}"),
	},
	{
		ID:         "users.list",
		Method:     "GET",
		Path:       "/users",
		Summary:    "Follow Up Boss GET /users. Source: https://docs.followupboss.com/reference/users-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("users", "list", "Follow Up Boss GET /users. Source: https://docs.followupboss.com/reference/users-get", "/users"),
	},
	{
		ID:         "webhook-events.get",
		Method:     "GET",
		Path:       "/webhookEvents/{id}",
		Summary:    "Follow Up Boss GET /webhookEvents/{id}. Source: https://docs.followupboss.com/reference/webhookevents-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("webhook-events", "get", "Follow Up Boss GET /webhookEvents/{id}. Source: https://docs.followupboss.com/reference/webhookevents-get", "/webhookEvents/{id}"),
	},
	{
		ID:         "webhooks.create",
		Method:     "POST",
		Path:       "/webhooks",
		Summary:    "Follow Up Boss POST /webhooks. Source: https://docs.followupboss.com/reference/webhooks-post",
		Positional: []string{},
		keywords:   codeOrchKeywords("webhooks", "create", "Follow Up Boss POST /webhooks. Source: https://docs.followupboss.com/reference/webhooks-post", "/webhooks"),
	},
	{
		ID:         "webhooks.delete",
		Method:     "DELETE",
		Path:       "/webhooks/{id}",
		Summary:    "Follow Up Boss DELETE /webhooks/{id}. Source: https://docs.followupboss.com/reference/webhooks-id-delete",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("webhooks", "delete", "Follow Up Boss DELETE /webhooks/{id}. Source: https://docs.followupboss.com/reference/webhooks-id-delete", "/webhooks/{id}"),
	},
	{
		ID:         "webhooks.get",
		Method:     "GET",
		Path:       "/webhooks/{id}",
		Summary:    "Follow Up Boss GET /webhooks/{id}. Source: https://docs.followupboss.com/reference/webhooks-id-get",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("webhooks", "get", "Follow Up Boss GET /webhooks/{id}. Source: https://docs.followupboss.com/reference/webhooks-id-get", "/webhooks/{id}"),
	},
	{
		ID:         "webhooks.list",
		Method:     "GET",
		Path:       "/webhooks",
		Summary:    "Follow Up Boss GET /webhooks. Source: https://docs.followupboss.com/reference/webhooks-get",
		Positional: []string{},
		keywords:   codeOrchKeywords("webhooks", "list", "Follow Up Boss GET /webhooks. Source: https://docs.followupboss.com/reference/webhooks-get", "/webhooks"),
	},
	{
		ID:         "webhooks.update",
		Method:     "PUT",
		Path:       "/webhooks/{id}",
		Summary:    "Follow Up Boss PUT /webhooks/{id}. Source: https://docs.followupboss.com/reference/webhooks-id-put",
		Positional: []string{"id"},
		keywords:   codeOrchKeywords("webhooks", "update", "Follow Up Boss PUT /webhooks/{id}. Source: https://docs.followupboss.com/reference/webhooks-id-put", "/webhooks/{id}"),
	},
}

// codeOrchStopwords filters two-letter and short common-word substrings
// that pollute ranking via the substring-contains rule. Without them, a
// search for "list links" matches every endpoint whose description
// contains "is enrolled" because "is" is two chars and the matcher
// accepts kw.contains(t) || t.contains(kw).
var codeOrchStopwords = map[string]bool{
	"a": true, "an": true, "and": true, "are": true, "as": true,
	"at": true, "be": true, "by": true, "for": true, "from": true,
	"has": true, "in": true, "is": true, "it": true, "its": true,
	"of": true, "on": true, "or": true, "that": true, "the": true,
	"this": true, "to": true, "was": true, "will": true, "with": true,
	"your": true, "you": true, "any": true, "all": true,
}

// codeOrchKeywords produces the lowercase token stream used for search
// ranking. Defined at package level so the registry initializer can call it
// inline above without pulling in a separate precompute step.
func codeOrchKeywords(resource, endpoint, summary, path string) []string {
	raw := strings.ToLower(resource + " " + endpoint + " " + summary + " " + path)
	raw = strings.Map(func(r rune) rune {
		switch r {
		case '_', '-', '/', '{', '}', '.', ',', ':', ';':
			return ' '
		}
		return r
	}, raw)
	out := make([]string, 0, 16)
	seen := map[string]bool{}
	for _, tok := range strings.Fields(raw) {
		if len(tok) < 3 || codeOrchStopwords[tok] || seen[tok] {
			continue
		}
		seen[tok] = true
		out = append(out, tok)
	}
	return out
}

func handleCodeOrchSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || strings.TrimSpace(query) == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}
	limit := 10
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	terms := codeOrchKeywords("", "", query, "")
	type scored struct {
		ep    *codeOrchEndpoint
		score int
	}
	results := make([]scored, 0, len(codeOrchEndpoints))
	for i := range codeOrchEndpoints {
		ep := &codeOrchEndpoints[i]
		score := 0
		for _, t := range terms {
			for _, kw := range ep.keywords {
				if kw == t {
					score += 2
				} else if strings.Contains(kw, t) || strings.Contains(t, kw) {
					score++
				}
			}
		}
		if score > 0 {
			results = append(results, scored{ep: ep, score: score})
		}
	}
	sort.SliceStable(results, func(i, j int) bool { return results[i].score > results[j].score })
	if len(results) > limit {
		results = results[:limit]
	}

	out := make([]map[string]any, 0, len(results))
	for _, r := range results {
		out = append(out, map[string]any{
			"endpoint_id": r.ep.ID,
			"method":      r.ep.Method,
			"path":        r.ep.Path,
			"summary":     r.ep.Summary,
			"score":       r.score,
		})
	}
	data, _ := json.Marshal(map[string]any{"count": len(out), "results": out})
	return mcplib.NewToolResultText(string(data)), nil
}

func handleCodeOrchExecute(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	id, ok := args["endpoint_id"].(string)
	if !ok || id == "" {
		return mcplib.NewToolResultError("endpoint_id is required (call follow-up-boss_search first)"), nil
	}

	var ep *codeOrchEndpoint
	for i := range codeOrchEndpoints {
		if codeOrchEndpoints[i].ID == id {
			ep = &codeOrchEndpoints[i]
			break
		}
	}
	if ep == nil {
		return mcplib.NewToolResultError(fmt.Sprintf("unknown endpoint_id %q — call follow-up-boss_search to discover valid ids", id)), nil
	}

	params, _ := args["params"].(map[string]any)
	if params == nil {
		params = map[string]any{}
	}

	c, err := newMCPClient()
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path := ep.Path
	for _, p := range ep.Positional {
		if v, ok := params[p]; ok {
			path = strings.ReplaceAll(path, "{"+p+"}", fmt.Sprintf("%v", v))
			delete(params, p)
		}
	}

	// Code-orch dispatch has no schema metadata at runtime to bucket params
	// into body vs query, so POST/PUT/PATCH keep the everything-to-body
	// design. DELETE is the one verb where query routing is unambiguous; the
	// previous code built `query` but never passed it.
	query := map[string]string{}
	if ep.Method == "GET" || ep.Method == "DELETE" {
		for k, v := range params {
			query[k] = fmt.Sprintf("%v", v)
		}
	}

	var data json.RawMessage
	switch ep.Method {
	case "GET":
		data, err = c.Get(path, query)
	case "DELETE":
		data, _, err = c.DeleteWithParams(path, query)
	case "POST":
		data, _, err = c.Post(path, params)
	case "PUT":
		data, _, err = c.Put(path, params)
	case "PATCH":
		data, _, err = c.Patch(path, params)
	default:
		return mcplib.NewToolResultError(fmt.Sprintf("unsupported method %q", ep.Method)), nil
	}
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	return mcplib.NewToolResultText(string(data)), nil
}
