// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"strings"
	"testing"

	"follow-up-boss-pp-cli/internal/cliutil"
	mcplib "github.com/mark3labs/mcp-go/mcp"
)

func TestProfileToolFilterAgentOmitsBlockedTools(t *testing.T) {
	t.Setenv(cliutil.MCPProfileEnvVar, cliutil.MCPProfileAgent)
	restore := profileToolSafety
	t.Cleanup(func() { profileToolSafety = restore })

	profileToolSafety = map[string]cliutil.MCPToolSafety{
		"people_delete": {Name: "people_delete", Destructive: true},
		"mail_get":      {Name: "mail_get", PrivacySensitive: true},
		"context":       {Name: "context"},
	}

	tools := []mcplib.Tool{{Name: "context"}, {Name: "mail_get"}, {Name: "people_delete"}}
	got := ProfileToolFilter(context.Background(), tools)
	if len(got) != 1 || got[0].Name != "context" {
		t.Fatalf("ProfileToolFilter() = %#v, want only context", got)
	}
}

func TestProfileGuardedHandlerAgentRejectsDirectInvocation(t *testing.T) {
	t.Setenv(cliutil.MCPProfileEnvVar, cliutil.MCPProfileAgent)
	called := false
	handler := profileGuardedHandler(cliutil.MCPToolSafety{Name: "people_delete", Destructive: true}, func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		called = true
		return mcplib.NewToolResultText("ok"), nil
	})

	result, err := handler(context.Background(), mcplib.CallToolRequest{})
	if err != nil {
		t.Fatalf("handler returned error: %v", err)
	}
	if called {
		t.Fatal("blocked direct invocation should not call underlying handler")
	}
	if result == nil || !result.IsError || len(result.Content) == 0 {
		t.Fatalf("handler returned %#v, want MCP tool error", result)
	}
	text, ok := result.Content[0].(mcplib.TextContent)
	if !ok || !strings.Contains(text.Text, "tool not available in agent profile; propose via follow-up-boss-pp-cli") {
		t.Fatalf("handler text = %#v, want profile unavailable message", result.Content[0])
	}
}

func TestProfileToolFilterOperatorExposesFullSurface(t *testing.T) {
	t.Setenv(cliutil.MCPProfileEnvVar, cliutil.MCPProfileOperator)
	restore := profileToolSafety
	t.Cleanup(func() { profileToolSafety = restore })

	profileToolSafety = map[string]cliutil.MCPToolSafety{
		"people_delete": {Name: "people_delete", Destructive: true},
	}

	tools := []mcplib.Tool{{Name: "people_delete"}}
	got := ProfileToolFilter(context.Background(), tools)
	if len(got) != 1 || got[0].Name != "people_delete" {
		t.Fatalf("ProfileToolFilter() = %#v, want destructive tool in operator profile", got)
	}
}
