// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"follow-up-boss-pp-cli/internal/cli"
	"follow-up-boss-pp-cli/internal/client"
	"follow-up-boss-pp-cli/internal/cliutil"
	"follow-up-boss-pp-cli/internal/config"
	"follow-up-boss-pp-cli/internal/mcp/cobratree"
	"follow-up-boss-pp-cli/internal/store"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	// Code-orchestration mode — the full surface is covered by two tools
	// (<api>_search + <api>_execute). Endpoint-mirror tools are suppressed.
	RegisterCodeOrchestrationTools(s)
	// Search tool — faster than iterating list endpoints for finding specific items
	registerProfiledTool(s,
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		cliutil.MCPToolSafety{Name: "search"},
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	registerProfiledTool(s,
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		cliutil.MCPToolSafety{Name: "sql"},
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	registerProfiledTool(s,
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		cliutil.MCPToolSafety{Name: "context"},
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath, registerProfiledTool)
}

var profileToolSafety = map[string]cliutil.MCPToolSafety{}

func registerProfiledTool(s *server.MCPServer, tool mcplib.Tool, safety cliutil.MCPToolSafety, handler server.ToolHandlerFunc) {
	if safety.Name == "" {
		safety.Name = tool.Name
	}
	if tool.Annotations.DestructiveHint != nil && *tool.Annotations.DestructiveHint {
		safety.Destructive = true
	}
	profileToolSafety[tool.Name] = safety
	s.AddTool(tool, profileGuardedHandler(safety, handler))
}

func profileGuardedHandler(safety cliutil.MCPToolSafety, handler server.ToolHandlerFunc) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		requestSafety := safety
		if requestSafety.Name == "" {
			requestSafety.Name = req.Params.Name
		}
		if !cliutil.MCPToolAvailableInProfile(requestSafety) {
			payload, _ := json.Marshal(map[string]string{"error": cliutil.MCPProfileUnavailableMessage("follow-up-boss-pp-cli")})
			return mcplib.NewToolResultError(string(payload)), nil
		}
		return handler(ctx, req)
	}
}

func ProfileToolFilter(ctx context.Context, tools []mcplib.Tool) []mcplib.Tool {
	_ = ctx
	if cliutil.CurrentMCPProfile() == cliutil.MCPProfileOperator {
		return tools
	}
	filtered := make([]mcplib.Tool, 0, len(tools))
	for _, tool := range tools {
		safety := profileToolSafety[tool.Name]
		if safety.Name == "" {
			safety.Name = tool.Name
		}
		if cliutil.MCPToolAvailableInProfile(safety) {
			filtered = append(filtered, tool)
		}
	}
	return filtered
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, binaryResponse bool, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if binaryResponse {
			headers = map[string]string{client.BinaryResponseHeader: "true"}
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if binaryResponse {
				data, err = c.GetWithHeaders(path, params, headers)
				break
			}
			data, err = c.Get(path, params)
		case "POST":
			if binaryResponse {
				data, _, err = c.PostWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PostWithParams(path, params, bodyArgs)
		case "PUT":
			if binaryResponse {
				data, _, err = c.PutWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(path, params, bodyArgs)
		case "PATCH":
			if binaryResponse {
				data, _, err = c.PatchWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(path, params, bodyArgs)
		case "DELETE":
			if binaryResponse {
				data, _, err = c.DeleteWithParamsAndHeaders(path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export FUB_API_KEY=<your-key>" +
					"\n      Get a key at: https://docs.followupboss.com/reference/authentication" +
					"\n      Use a Follow Up Boss API key; the printed CLI encodes it as Basic key-colon auth." +
					"\n      Run 'follow-up-boss-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your API key." +
					"\n      Set it with: export FUB_API_KEY=<your-key>" +
					"\n      Get a key at: https://docs.followupboss.com/reference/authentication" +
					"\n      Use a Follow Up Boss API key; the printed CLI encodes it as Basic key-colon auth." +
					"\n      Run 'follow-up-boss-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export FUB_API_KEY=<your-key>" +
					"\n      Get a key at: https://docs.followupboss.com/reference/authentication" +
					"\n      Use a Follow Up Boss API key; the printed CLI encodes it as Basic key-colon auth." +
					"\n      Run 'follow-up-boss-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "follow-up-boss-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "follow-up-boss-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "follow-up-boss",
		"description": "Docs-derived Follow Up Boss REST API spec for CLI Printing Press.",
		"archetype":   "crm",
		"tool_count":  143,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion follow-up-boss-pp-cli binary.",
		"auth": map[string]any{
			"type": "api_key",
			"env_vars": []map[string]any{
				{
					"name":        "FUB_API_KEY",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
			"key_url":      "https://docs.followupboss.com/reference/authentication",
			"instructions": "Use a Follow Up Boss API key; the printed CLI encodes it as Basic key-colon auth.",
		},
		"resources": []map[string]any{
			{
				"name":        "action-plans",
				"description": "Manage action plans",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "action-plans-people",
				"description": "Manage action plans people",
				"endpoints":   []string{"create", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "appointment-outcomes",
				"description": "Manage appointment outcomes",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "appointment-types",
				"description": "Manage appointment types",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "appointments",
				"description": "Manage appointments",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "automations",
				"description": "Manage automations",
				"endpoints":   []string{"get", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "automations-people",
				"description": "Manage automations people",
				"endpoints":   []string{"create", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "calls",
				"description": "Manage calls",
				"endpoints":   []string{"create", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "custom-fields",
				"description": "Manage custom fields",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "deal-attachments",
				"description": "Manage deal attachments",
				"endpoints":   []string{"create", "delete", "get", "update"},
				"searchable":  true,
			},
			{
				"name":        "deal-custom-fields",
				"description": "Manage deal custom fields",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "deals",
				"description": "Manage deals",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "em-campaigns",
				"description": "Manage em campaigns",
				"endpoints":   []string{"create", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "em-events",
				"description": "Manage em events",
				"endpoints":   []string{"create", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "events",
				"description": "Manage events",
				"endpoints":   []string{"create", "get", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "groups",
				"description": "Manage groups",
				"endpoints":   []string{"create", "delete", "get", "list", "round-robin-list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "identity",
				"description": "Manage identity",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "me",
				"description": "Manage me",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "notes",
				"description": "Manage notes",
				"endpoints":   []string{"create", "delete", "get", "update"},
				"searchable":  true,
			},
			{
				"name":        "people",
				"description": "Manage people",
				"endpoints":   []string{"check-duplicate-list", "claim-create", "create", "delete", "get", "ignore-unclaimed-create", "list", "unclaimed-list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "people-relationships",
				"description": "Manage people relationships",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "person-attachments",
				"description": "Manage person attachments",
				"endpoints":   []string{"create", "delete", "get", "update"},
				"searchable":  true,
			},
			{
				"name":        "pipelines",
				"description": "Manage pipelines",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "ponds",
				"description": "Manage ponds",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "reactions",
				"description": "Manage reactions",
				"endpoints":   []string{"get", "ref-type-ref-id-create", "ref-type-ref-id-delete"},
				"searchable":  true,
			},
			{
				"name":        "smart-lists",
				"description": "Manage smart lists",
				"endpoints":   []string{"get", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "stages",
				"description": "Manage stages",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "tasks",
				"description": "Manage tasks",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "team-inboxes",
				"description": "Manage team inboxes",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "teams",
				"description": "Manage teams",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "templates",
				"description": "Manage templates",
				"endpoints":   []string{"create", "delete", "get", "list", "merge-create", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "text-message-templates",
				"description": "Manage text message templates",
				"endpoints":   []string{"create", "delete", "get", "list", "merge-create", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "text-messages",
				"description": "Manage text messages",
				"endpoints":   []string{"create", "get", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "threaded-replies",
				"description": "Manage threaded replies",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "timeframes",
				"description": "Manage timeframes",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "users",
				"description": "Manage users",
				"endpoints":   []string{"delete", "get", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "webhook-events",
				"description": "Manage webhook events",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "webhooks",
				"description": "Manage webhooks",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass offset parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		"playbook": []map[string]string{
			{"topic": "Contact lookup", "insight": "Use search for finding contacts by name/email. List endpoints return unsorted results and require pagination for large datasets."},
			{"topic": "Activity tracking", "insight": "When checking deal activity, sync first and query locally. CRM APIs often throttle activity-log endpoints heavily."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
