package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestRenderCatalogTable_Golden locks the rendering of a worst-case
// row: backticks live inside the link text (Name and Skill columns),
// the description carries punctuation we don't want to over-escape
// (commas, parentheses, an apostrophe, a hyphen). If markdown escaping
// ever changes here, the table cell display in the README changes.
// The per-row format is the documented surface; protect it.
func TestRenderCatalogTable_Golden(t *testing.T) {
	entries := []RegistryEntry{
		{
			Name:        "hubspot-pp-cli",
			Category:    "sales-and-crm",
			API:         "HubSpot",
			Description: "Work with contacts, companies, deals, tickets, and pipelines.",
			Path:        "library/sales-and-crm/hubspot",
		},
	}

	got := renderCatalogTable(entries)

	want := `<!-- this section is generated by tools/generate-registry; do not hand-edit -->
| Name | Skill | Release | What it does |
|------|-------|---------|--------------|
| [` + "`hubspot-pp-cli`" + `](library/sales-and-crm/hubspot/) | [` + "`/pp-hubspot-pp-cli`" + `](cli-skills/pp-hubspot-pp-cli/SKILL.md) | [latest](https://github.com/mvanhorn/printing-press-library/releases/tag/hubspot-pp-cli-current) | Work with contacts, companies, deals, tickets, and pipelines. |
`

	if got != want {
		t.Errorf("renderCatalogTable mismatch\nwant:\n%s\ngot:\n%s", want, got)
	}
}

func TestRenderCatalogTable_PrinterDisplayNameLinksToHandle(t *testing.T) {
	entries := []RegistryEntry{
		{
			Name:        "squarespace",
			Category:    "commerce",
			API:         "Squarespace",
			Description: "Manage Squarespace commerce and account workflows.",
			Path:        "library/commerce/squarespace",
			Printer:     "zaydiscold",
			PrinterName: "Zayd",
		},
	}

	got := renderCatalogTable(entries)

	if !strings.Contains(got, "Printed by [Zayd](https://github.com/zaydiscold)") {
		t.Fatalf("catalog should render printer_name as link text and printer as URL handle, got:\n%s", got)
	}
	if strings.Contains(got, "Printed by [@zaydiscold]") {
		t.Fatalf("catalog should not use handle as link text when printer_name is present, got:\n%s", got)
	}
}

func TestRenderCatalogTable_PrinterHandleFallback(t *testing.T) {
	entries := []RegistryEntry{
		{
			Name:        "example",
			Category:    "tools",
			API:         "Example",
			Description: "Example workflows.",
			Path:        "library/tools/example",
			Printer:     "octocat",
		},
	}

	got := renderCatalogTable(entries)

	if !strings.Contains(got, "Printed by [@octocat](https://github.com/octocat)") {
		t.Fatalf("catalog should fall back to @handle link text when printer_name is absent, got:\n%s", got)
	}
}

// TestFormatDescription covers the normalization rules: trim, collapse
// newlines (a description must fit one table cell), and ensure
// terminal punctuation. The "?" / "!" branch matters because some
// descriptions are written as questions and we shouldn't append a
// trailing period in that case.
func TestFormatDescription(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		{"trims and adds period", "  hello world  ", "hello world."},
		{"keeps existing period", "hello.", "hello."},
		{"keeps existing question mark", "really?", "really?"},
		{"keeps existing exclamation", "wow!", "wow!"},
		{"collapses LF newlines", "line one\nline two", "line one line two."},
		{"collapses CRLF newlines", "line one\r\nline two", "line one line two."},
		{"empty stays empty", "   ", ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := formatDescription(tc.in); got != tc.want {
				t.Errorf("formatDescription(%q) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}

func TestRegistryDescription(t *testing.T) {
	cases := []struct {
		name               string
		prior              string
		goreleaser         string
		ppDescription      string
		catalogDescription string
		want               string
	}{
		{
			name:               "explicit catalog copy wins over prior registry and source fallbacks",
			prior:              "Curated catalog copy.",
			goreleaser:         "Goreleaser brews copy.",
			ppDescription:      "Manifest copy.",
			catalogDescription: "New website copy.",
			want:               "New website copy.",
		},
		{
			name:          "non-stale prior registry copy is preserved over source fallbacks",
			prior:         "Curated catalog copy.",
			goreleaser:    "Goreleaser brews copy.",
			ppDescription: "Manifest copy.",
			want:          "Curated catalog copy.",
		},
		{
			name:          "boilerplate prior is preserved without explicit catalog copy",
			prior:         "Printing Press CLI for Whoop.",
			goreleaser:    "Fetch WHOOP recovery, strain, sleep, workout, cycle, profile, and body-measurement data with OAuth-backed API access.",
			ppDescription: "Manifest copy.",
			want:          "Printing Press CLI for Whoop.",
		},
		{
			name:          "raw-html prior is preserved without explicit catalog copy",
			prior:         "<p>",
			goreleaser:    "Search setlist.fm artists, setlists, venues, cities, and concert histories through the setlist.fm API.",
			ppDescription: "Manifest copy.",
			want:          "<p>",
		},
		{
			name:          "truncated prior is preserved without explicit catalog copy",
			prior:         "Every EmailOctopus v2 endpoint, plus the cross-list joins, churn diffs, and rate-budgeted bulk operations the API...",
			goreleaser:    "Manage EmailOctopus lists, contacts, campaigns, automations, reports, and cross-list cleanup workflows from the terminal.",
			ppDescription: "Manifest copy.",
			want:          "Every EmailOctopus v2 endpoint, plus the cross-list joins, churn diffs, and rate-budgeted bulk operations the API...",
		},
		{
			name:          "oversized prior is preserved without explicit catalog copy",
			prior:         strings.Repeat("Recipe catalog copy ", 20),
			goreleaser:    "Search trusted recipe sites, rank results, save a local cookbook, and enrich nutrition data with USDA FoodData Central.",
			ppDescription: "Manifest copy.",
			want:          strings.Repeat("Recipe catalog copy ", 20),
		},
		{
			name:          "boilerplate prior with no source is preserved",
			prior:         "Printing Press CLI for Missing.",
			goreleaser:    "",
			ppDescription: "",
			want:          "Printing Press CLI for Missing.",
		},
		{
			name:          "raw-html prior with no source is preserved",
			prior:         "<p>",
			goreleaser:    "",
			ppDescription: "",
			want:          "<p>",
		},
		{
			name:          "bare-heading prior falls through to manifest before goreleaser",
			prior:         "# Introduction",
			goreleaser:    "Real catalog copy.",
			ppDescription: "Manifest copy.",
			want:          "Manifest copy.",
		},
		{
			name:          "empty prior falls through to manifest before goreleaser",
			prior:         "",
			goreleaser:    "Goreleaser copy.",
			ppDescription: "Manifest copy.",
			want:          "Manifest copy.",
		},
		{
			name:          "empty prior and goreleaser fall through to pp manifest description (lawhub-shape repair)",
			prior:         "",
			goreleaser:    "",
			ppDescription: "Local-first LSAT practice analytics.",
			want:          "Local-first LSAT practice analytics.",
		},
		{
			name:          "bare-heading prior with empty goreleaser falls through to pp",
			prior:         "# Introduction",
			goreleaser:    "",
			ppDescription: "Manifest copy.",
			want:          "Manifest copy.",
		},
		{
			name:          "empty source falls back to non-stale prior registry copy",
			prior:         "Legacy but valid catalog copy.",
			goreleaser:    "",
			ppDescription: "",
			want:          "Legacy but valid catalog copy.",
		},
		{
			name:          "all empty returns empty (validation catches this separately)",
			prior:         "",
			goreleaser:    "",
			ppDescription: "",
			want:          "",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := registryDescription(tc.prior, tc.goreleaser, tc.ppDescription, tc.catalogDescription); got != tc.want {
				t.Errorf("registryDescription(%q, %q, %q, %q) = %q, want %q",
					tc.prior, tc.goreleaser, tc.ppDescription, tc.catalogDescription, got, tc.want)
			}
		})
	}
}

func TestAPIDisplayName(t *testing.T) {
	cases := []struct {
		name  string
		pp    printingPressManifest
		prior RegistryEntry
		slug  string
		want  string
	}{
		{
			name:  "curated punctuation wins over auto display",
			pp:    printingPressManifest{APIName: "cal-com", DisplayName: "Cal Com"},
			prior: RegistryEntry{API: "Cal.com"},
			slug:  "cal-com",
			want:  "Cal.com",
		},
		{
			name:  "curated spacing wins over naive display",
			pp:    printingPressManifest{APIName: "producthunt", DisplayName: "Producthunt"},
			prior: RegistryEntry{API: "Product Hunt"},
			slug:  "producthunt",
			want:  "Product Hunt",
		},
		{
			name:  "long description prior falls through to manifest display",
			pp:    printingPressManifest{APIName: "recipe-goat", DisplayName: "Recipe GOAT"},
			prior: RegistryEntry{API: "Cross-site recipe aggregator (37 trusted sites: King Arthur, Serious Eats, Smitten Kitchen, AllRecipes, Food52, BBC Food, EatingWell, Food Network, and 29 more) + USDA FoodData Central"},
			slug:  "recipe-goat",
			want:  "Recipe GOAT",
		},
		{
			name:  "title-cased slug falls through to brand casing",
			pp:    printingPressManifest{APIName: "setlist-fm", DisplayName: "setlist.fm"},
			prior: RegistryEntry{API: "Setlist Fm"},
			slug:  "setlist-fm",
			want:  "setlist.fm",
		},
		{
			name:  "internal capitalization replaces title-cased slug",
			pp:    printingPressManifest{APIName: "coingecko", DisplayName: "CoinGecko"},
			prior: RegistryEntry{API: "Coingecko"},
			slug:  "coingecko",
			want:  "CoinGecko",
		},
		{
			name:  "lowercase brand replaces title-cased slug",
			pp:    printingPressManifest{APIName: "beehiiv", DisplayName: "beehiiv"},
			prior: RegistryEntry{API: "Beehiiv"},
			slug:  "beehiiv",
			want:  "beehiiv",
		},
		{
			name:  "generic suffix falls through to full parent product",
			pp:    printingPressManifest{APIName: "servicetitan-pricebook", DisplayName: "ServiceTitan Pricebook"},
			prior: RegistryEntry{API: "Pricebook"},
			slug:  "servicetitan-pricebook",
			want:  "ServiceTitan Pricebook",
		},
		{
			name:  "PP-prefixed artifact yields to corrected display name",
			pp:    printingPressManifest{APIName: "clarity", DisplayName: "Microsoft Clarity"},
			prior: RegistryEntry{API: "PP Clarity"},
			slug:  "clarity",
			want:  "Microsoft Clarity",
		},
		{
			name:  "PP-prefixed brand without shared tail is preserved",
			pp:    printingPressManifest{APIName: "pp-labs", DisplayName: "Acme Widgets"},
			prior: RegistryEntry{API: "PP Labs"},
			slug:  "pp-labs",
			want:  "PP Labs",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := apiDisplayName(tc.pp, tc.prior, tc.slug); got != tc.want {
				t.Errorf("apiDisplayName(%+v, %+v, %q) = %q, want %q", tc.pp, tc.prior, tc.slug, got, tc.want)
			}
		})
	}
}

func TestRepairDuplicateAPIDisplayNamesUsesSourceDisplay(t *testing.T) {
	entries := []RegistryEntry{
		{
			Name:      "substack",
			API:       "Substack",
			sourceAPI: "Substack",
		},
		{
			Name:      "substack-creator",
			API:       "Substack",
			sourceAPI: "Substack Creator",
		},
		{
			Name:      "cal-com",
			API:       "Cal.com",
			sourceAPI: "Cal Com",
		},
	}

	repairDuplicateAPIDisplayNames(entries)

	if got := entries[1].API; got != "Substack Creator" {
		t.Fatalf("substack-creator API = %q, want source display name", got)
	}
	if got := entries[2].API; got != "Cal.com" {
		t.Fatalf("non-duplicate curated API = %q, want unchanged", got)
	}
}

func TestRepairDuplicateAPIDisplayNamesPartialRepair(t *testing.T) {
	entries := []RegistryEntry{
		{Name: "alpha", API: "Acme", sourceAPI: "Acme Corp"},
		{Name: "beta", API: "Acme", sourceAPI: "Acme"},
		{Name: "gamma", API: "Acme", sourceAPI: "Acme"},
	}

	repairDuplicateAPIDisplayNames(entries)

	if got := entries[0].API; got != "Acme Corp" {
		t.Fatalf("repairable entry API = %q, want source display name", got)
	}
	if entries[1].API != "Acme" || entries[2].API != "Acme" {
		t.Fatalf("unrepairable entries should remain duplicated, got %q and %q", entries[1].API, entries[2].API)
	}
	if errs := validateUniqueAPIDisplayNames(entries, nil); len(errs) == 0 {
		t.Fatal("want validation to report the unresolved duplicate, got no errors")
	}
}

func TestTitleCaseSlug(t *testing.T) {
	cases := map[string]string{
		"setlist-fm": "Setlist Fm",
		"éclair-api": "Éclair Api",
	}
	for in, want := range cases {
		t.Run(in, func(t *testing.T) {
			if got := titleCaseSlug(in); got != want {
				t.Errorf("titleCaseSlug(%q) = %q, want %q", in, got, want)
			}
		})
	}
}

func TestSearchTerms(t *testing.T) {
	got := searchTerms(printingPressManifest{
		APIName:         "booking-com",
		DisplayName:     "Booking.com",
		CLIName:         "booking-com-pp-cli",
		Description:     "Search Booking.com hotels, scrape details and reviews.",
		AuthDescription: "Authenticated trips use cookie import.",
		NovelFeatures: []struct {
			Name        string `json:"name"`
			Command     string `json:"command"`
			Description string `json:"description"`
			Rationale   string `json:"rationale"`
		}{
			{
				Name:        "Compare two hotels side-by-side",
				Command:     "compare",
				Description: "Fetches detail and reviews for two hotels in parallel.",
				Rationale:   "Useful for lodging decisions.",
			},
		},
	})

	want := []string{
		"booking-com",
		"Booking.com",
		"booking-com-pp-cli",
		"Search Booking.com hotels, scrape details and reviews.",
		"Authenticated trips use cookie import.",
		"Compare two hotels side-by-side",
		"compare",
		"Fetches detail and reviews for two hotels in parallel.",
		"Useful for lodging decisions.",
	}
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Fatalf("searchTerms mismatch\nwant: %#v\ngot:  %#v", want, got)
	}
}

func TestBuildEntriesIncludesReleaseMetadataFromReleaseFiles(t *testing.T) {
	cwd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	repoRoot := filepath.Clean(filepath.Join(cwd, "..", ".."))
	if err := os.Chdir(repoRoot); err != nil {
		t.Fatalf("chdir repo root: %v", err)
	}
	t.Cleanup(func() { _ = os.Chdir(cwd) })

	generatedEntries, err := buildEntries(libraryDir, loadExistingEntries(registryPath))
	if err != nil {
		t.Fatalf("build entries: %v", err)
	}

	checked := 0
	var substack *Release
	for _, generated := range generatedEntries {
		if generated.Release != nil {
			checked++
		}
		if generated.Name == "substack" {
			substack = generated.Release
		}
	}
	if checked == 0 {
		t.Fatal("expected at least one .printing-press-release.json-backed registry entry")
	}
	if substack == nil || substack.CLIName != "substack-pp-cli" || strings.TrimSpace(substack.Version) == "" {
		t.Fatalf("generated substack release = %+v, want substack-pp-cli with non-empty version", substack)
	}
}

func TestIsUnreleasedSkeleton(t *testing.T) {
	cases := []struct {
		name string
		r    *Release
		want bool
	}{
		{"nil release is not a skeleton", nil, false},
		{"cli_name set + blank trio is an unreleased skeleton", &Release{CLIName: "x-pp-cli"}, true},
		{"whitespace-only trio is an unreleased skeleton", &Release{CLIName: "x-pp-cli", Version: "  ", ReleasedAt: "\t", SourceCommit: "\n"}, true},
		{"blank cli_name + blank trio is malformed, not a clean skeleton", &Release{}, false},
		{"whitespace cli_name + blank trio is malformed, not a clean skeleton", &Release{CLIName: "  "}, false},
		{"version set means released", &Release{CLIName: "x-pp-cli", Version: "2026.6.3"}, false},
		{"source_commit set means released", &Release{CLIName: "x-pp-cli", SourceCommit: "abc123"}, false},
	}
	for _, tc := range cases {
		if got := isUnreleasedSkeleton(tc.r); got != tc.want {
			t.Errorf("%s: isUnreleasedSkeleton = %v, want %v", tc.name, got, tc.want)
		}
	}
}

// A freshly-printed CLI ships a blank release skeleton; the post-merge release
// workflow stamps it later. buildEntries must omit the release block for such an
// entry so registry.json never carries empty required release fields — the npm
// installer's parseRegistryEntry rejects a release object with blank
// version/released_at/source_commit and skips the whole CLI. A genuinely
// released ledger is still emitted.
func TestBuildEntriesOmitsReleaseForUnreleasedSkeleton(t *testing.T) {
	root := t.TempDir()
	writeCLI := func(category, slug, ppJSON, releaseJSON string) {
		t.Helper()
		dir := filepath.Join(root, category, slug)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dir, ".printing-press.json"), []byte(ppJSON), 0o644); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dir, ".printing-press-release.json"), []byte(releaseJSON), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	writeCLI("ai", "released", `{"display_name":"Released","api_name":"released","description":"Does things."}`,
		`{"cli_name":"released-pp-cli","version":"2026.6.3","released_at":"2026-06-23T00:00:00Z","source_commit":"abc123"}`)
	writeCLI("ai", "skeleton", `{"display_name":"Skeleton","api_name":"skeleton","description":"Does things."}`,
		`{"cli_name":"skeleton-pp-cli","version":"","released_at":"","source_commit":""}`)

	entries, err := buildEntries(root, map[string]RegistryEntry{})
	if err != nil {
		t.Fatalf("buildEntries: %v", err)
	}
	got := map[string]*Release{}
	for _, e := range entries {
		got[e.Name] = e.Release
	}
	if got["released"] == nil {
		t.Errorf("released CLI: want a release block, got nil")
	} else if got["released"].Version != "2026.6.3" {
		t.Errorf("released CLI: version = %q, want 2026.6.3", got["released"].Version)
	}
	if got["skeleton"] != nil {
		t.Errorf("unreleased skeleton: want no release block (nil), got %+v", got["skeleton"])
	}
	// With the skeleton's release block omitted, the strict validator passes it
	// via the e.Release == nil path — no false positive on the pre-merge state.
	if errs := validateEntries(entries); len(errs) != 0 {
		t.Errorf("validateEntries on built entries: want no errors, got %v", errs)
	}
}

// A malformed ledger — trio blank but cli_name ALSO blank (e.g. a printer
// workflow misfire) — must not be silently omitted. It is kept as a non-nil
// release block so validateEntries still flags the empty cli_name, preserving
// the pre-existing gate that the skeleton-omission must not weaken.
func TestBuildEntriesKeepsReleaseForBlankCLINameSkeleton(t *testing.T) {
	root := t.TempDir()
	dir := filepath.Join(root, "ai", "broken")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, ".printing-press.json"),
		[]byte(`{"display_name":"Broken","api_name":"broken","description":"Does things."}`), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, ".printing-press-release.json"),
		[]byte(`{"cli_name":"","version":"","released_at":"","source_commit":""}`), 0o644); err != nil {
		t.Fatal(err)
	}

	entries, err := buildEntries(root, map[string]RegistryEntry{})
	if err != nil {
		t.Fatalf("buildEntries: %v", err)
	}
	var rel *Release
	for _, e := range entries {
		if e.Name == "broken" {
			rel = e.Release
		}
	}
	if rel == nil {
		t.Fatal("blank cli_name skeleton: release block must be kept (not omitted) so validation can flag it")
	}
	if errs := validateEntries(entries); !strings.Contains(strings.Join(errs, "\n"), "broken: release.cli_name is empty") {
		t.Errorf("want a release.cli_name error for the malformed skeleton, got: %v", errs)
	}
}

// TestValidateEntries exercises the source-only validation that backs the
// --validate flag. The required-field set must stay in lockstep with the
// npm installer's parseRegistry contract — any new requiredString check
// added there should grow a case here.
func TestValidateEntries(t *testing.T) {
	mcpOK := &MCPBlock{Binary: "x-pp-mcp", Transports: []string{"stdio"}, AuthType: "api_key"}

	cases := []struct {
		name    string
		entries []RegistryEntry
		// wantSubstrs is a set of substrings that must appear in the joined
		// error report. Using substrings avoids brittle exact-match coupling
		// to the error-message phrasing while still pinning slug + field.
		wantSubstrs []string
		wantOK      bool
	}{
		{
			name: "valid entry passes",
			entries: []RegistryEntry{
				{Name: "ok", Category: "tools", API: "OK", Description: "Does things.", Path: "library/tools/ok"},
			},
			wantOK: true,
		},
		{
			name: "empty description fails with sources-checked message in resolution order",
			entries: []RegistryEntry{
				{Name: "lawhub", Category: "education", API: "LawHub", Description: "", Path: "library/education/lawhub"},
			},
			wantSubstrs: []string{
				"lawhub: description is empty",
				// Sources appear in fallback-resolution order: .printing-press.json
				// description is listed before goreleaser brews, matching what
				// registryDescription consults.
				".printing-press.json description, .goreleaser.yaml brews description",
			},
		},
		{
			name: "all-whitespace description fails (matches npm requiredString trim semantics)",
			entries: []RegistryEntry{
				{Name: "ws", Category: "tools", API: "WS", Description: "   \t\n  ", Path: "library/tools/ws"},
			},
			wantSubstrs: []string{"ws: description is empty"},
		},
		{
			name: "all-whitespace name reports under (unnamed) prefix",
			entries: []RegistryEntry{
				{Name: "  ", Category: "tools", API: "X", Description: "Has desc.", Path: "library/tools/x"},
			},
			wantSubstrs: []string{"(unnamed): name is empty"},
		},
		{
			name: "all-whitespace mcp.auth_type fails",
			entries: []RegistryEntry{
				{
					Name: "x", Category: "tools", API: "X", Description: "Has desc.", Path: "library/tools/x",
					MCP: &MCPBlock{Binary: "x-pp-mcp", Transports: []string{"stdio"}, AuthType: "   "},
				},
			},
			wantSubstrs: []string{"x: mcp.auth_type is empty"},
		},
		{
			name: "multiple entries each report independently",
			entries: []RegistryEntry{
				{Name: "a", Category: "tools", API: "A", Description: "", Path: "library/tools/a"},
				{Name: "b", Category: "tools", API: "B", Description: "", Path: "library/tools/b"},
				{Name: "c", Category: "tools", API: "C", Description: "Has desc.", Path: "library/tools/c"},
			},
			wantSubstrs: []string{
				"a: description is empty",
				"b: description is empty",
			},
		},
		{
			name: "missing mcp.binary fails when mcp block present",
			entries: []RegistryEntry{
				{
					Name: "x", Category: "tools", API: "X", Description: "Has desc.", Path: "library/tools/x",
					MCP: &MCPBlock{Binary: "", Transports: []string{"stdio"}, AuthType: "api_key"},
				},
			},
			wantSubstrs: []string{"x: mcp.binary is empty"},
		},
		{
			name: "missing mcp.transports fails when mcp block present",
			entries: []RegistryEntry{
				{
					Name: "x", Category: "tools", API: "X", Description: "Has desc.", Path: "library/tools/x",
					MCP: &MCPBlock{Binary: "x-pp-mcp", Transports: nil, AuthType: "api_key"},
				},
			},
			wantSubstrs: []string{"x: mcp.transports is empty"},
		},
		{
			name: "missing mcp.auth_type fails when mcp block present",
			entries: []RegistryEntry{
				{
					Name: "x", Category: "tools", API: "X", Description: "Has desc.", Path: "library/tools/x",
					MCP: &MCPBlock{Binary: "x-pp-mcp", Transports: []string{"stdio"}, AuthType: ""},
				},
			},
			wantSubstrs: []string{"x: mcp.auth_type is empty"},
		},
		{
			name: "non-mcp entry skips mcp checks",
			entries: []RegistryEntry{
				{Name: "x", Category: "tools", API: "X", Description: "Has desc.", Path: "library/tools/x"},
			},
			wantOK: true,
		},
		{
			name: "valid mcp block passes",
			entries: []RegistryEntry{
				{Name: "x", Category: "tools", API: "X", Description: "Has desc.", Path: "library/tools/x", MCP: mcpOK},
			},
			wantOK: true,
		},
		{
			name: "valid release block passes",
			entries: []RegistryEntry{
				{
					Name: "x", Category: "tools", API: "X", Description: "Has desc.", Path: "library/tools/x",
					Release: &Release{CLIName: "x-pp-cli", Version: "2026.6.23", ReleasedAt: "2026-06-23T00:00:00Z", SourceCommit: "abc123"},
				},
			},
			wantOK: true,
		},
		{
			name: "release block required fields fail when blank",
			entries: []RegistryEntry{
				{
					Name: "x", Category: "tools", API: "X", Description: "Has desc.", Path: "library/tools/x",
					Release: &Release{CLIName: " ", Version: "", ReleasedAt: "	", SourceCommit: "\n"},
				},
			},
			wantSubstrs: []string{
				"x: release.cli_name is empty",
				"x: release.version is empty",
				"x: release.released_at is empty",
				"x: release.source_commit is empty",
			},
		},
		{
			name: "unnamed entry reports under (unnamed) prefix",
			entries: []RegistryEntry{
				{Name: "", Category: "tools", API: "X", Description: "Has desc.", Path: "library/tools/x"},
			},
			wantSubstrs: []string{"(unnamed): name is empty"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := validateEntries(tc.entries)
			joined := strings.Join(got, "\n")
			if tc.wantOK {
				if len(got) != 0 {
					t.Fatalf("validateEntries: want no errors, got:\n%s", joined)
				}
				return
			}
			for _, sub := range tc.wantSubstrs {
				if !strings.Contains(joined, sub) {
					t.Errorf("validateEntries: missing substring %q in output:\n%s", sub, joined)
				}
			}
		})
	}
}

func TestValidateUniqueAPIDisplayNames(t *testing.T) {
	entries := []RegistryEntry{
		{Name: "substack", Category: "media", API: "Substack", Description: "Growth loop.", Path: "library/media/substack"},
		{Name: "substack-creator", Category: "media", API: "Substack", Description: "Creator workflows.", Path: "library/media/substack-creator"},
		{Name: "espn", Category: "media", API: "ESPN", Description: "Sports.", Path: "library/media/espn"},
	}

	t.Run("full validation rejects duplicate display labels", func(t *testing.T) {
		got := strings.Join(validateUniqueAPIDisplayNames(entries, nil), "\n")
		if !strings.Contains(got, `api display name "Substack" is used by multiple entries: substack, substack-creator`) {
			t.Fatalf("missing duplicate display error, got:\n%s", got)
		}
	})

	t.Run("scoped validation catches a touched entry colliding with unchanged sibling", func(t *testing.T) {
		got := strings.Join(validateUniqueAPIDisplayNames(entries, []string{"substack-creator"}), "\n")
		if !strings.Contains(got, "substack, substack-creator") {
			t.Fatalf("missing scoped duplicate display error, got:\n%s", got)
		}
	})

	t.Run("scoped validation ignores unrelated duplicate groups", func(t *testing.T) {
		if got := validateUniqueAPIDisplayNames(entries, []string{"espn"}); len(got) != 0 {
			t.Fatalf("want no unrelated duplicate errors, got: %v", got)
		}
	})
}

// TestValidateEntries_IgnoresPriorCuratedValue is the regression test for
// the lawhub-shape bug. The validator must NOT accept an entry whose only
// non-empty description comes from a prior curated registry value — that
// path is exactly what masked the original bug. This is enforced by the
// caller (main passes an empty existing map), but we also assert
// validateEntries' own contract: it judges only what's in the entry struct.
func TestValidateEntries_IgnoresPriorCuratedValue(t *testing.T) {
	// Entry with an empty description (post-source-only resolution) must
	// fail validation regardless of any external curated value.
	entries := []RegistryEntry{
		{Name: "lawhub", Category: "education", API: "LawHub", Description: "", Path: "library/education/lawhub"},
	}
	got := validateEntries(entries)
	if len(got) == 0 {
		t.Fatal("validateEntries: expected failure for empty description, got none")
	}
}

// TestFilterEntriesBySlug pins the scoping the PR-time --validate gate
// relies on: only the named CLIs are validated, so a stale PR that doesn't
// touch an already-correct CLI is never failed for it (the agent-capture /
// tiktok-shop false-failure on PRs branched before those descriptions
// landed). Unmatched slugs are dropped silently (deleted/renamed CLIs).
func TestFilterEntriesBySlug(t *testing.T) {
	entries := []RegistryEntry{
		{Name: "agent-capture", Category: "developer-tools", API: "Agent Capture", Path: "library/developer-tools/agent-capture", Description: ""},
		{Name: "tiktok-shop", Category: "commerce", API: "TikTok Shop", Path: "library/commerce/tiktok-shop", Description: ""},
		{Name: "exchangerate-api", Category: "finance", API: "ExchangeRate-API", Path: "library/finance/exchangerate-api", Description: "Currency conversion."},
	}

	t.Run("restricts to named slugs and excludes the rest", func(t *testing.T) {
		got := filterEntriesBySlug(entries, []string{"exchangerate-api"})
		if len(got) != 1 || got[0].Name != "exchangerate-api" {
			t.Fatalf("want only exchangerate-api, got %+v", got)
		}
		// The dropped agent-capture/tiktok-shop entries (empty description)
		// must not reach validateEntries, so a PR touching only
		// exchangerate-api validates clean.
		if errs := validateEntries(got); len(errs) != 0 {
			t.Errorf("want no errors for scoped clean entry, got: %v", errs)
		}
	})

	t.Run("a changed CLI with an empty description still fails", func(t *testing.T) {
		got := filterEntriesBySlug(entries, []string{"agent-capture"})
		if len(got) != 1 {
			t.Fatalf("want agent-capture in scope, got %+v", got)
		}
		if errs := validateEntries(got); len(errs) == 0 {
			t.Error("want failure for in-scope empty description, got none")
		}
	})

	t.Run("unmatched slug is ignored", func(t *testing.T) {
		if got := filterEntriesBySlug(entries, []string{"deleted-cli"}); len(got) != 0 {
			t.Fatalf("want empty for unmatched slug, got %+v", got)
		}
	})

	t.Run("whitespace around a slug is trimmed", func(t *testing.T) {
		got := filterEntriesBySlug(entries, []string{"  exchangerate-api  "})
		if len(got) != 1 || got[0].Name != "exchangerate-api" {
			t.Fatalf("want exchangerate-api matched after trim, got %+v", got)
		}
	})
}

// TestRenderCatalogCounts checks both pluralization branches and the
// happy multi-entry / multi-category path. The pluralization matters
// because the rendered string lands in human-readable prose; "1 CLIs
// across 1 categories" reads as a generator bug.
func TestRenderCatalogCounts(t *testing.T) {
	cases := []struct {
		name    string
		entries []RegistryEntry
		want    string
	}{
		{
			name:    "single CLI, single category",
			entries: []RegistryEntry{{Name: "a", Category: "x"}},
			want:    "1 CLI across 1 category.",
		},
		{
			name: "many CLIs, many categories",
			entries: []RegistryEntry{
				{Name: "a", Category: "x"},
				{Name: "b", Category: "y"},
				{Name: "c", Category: "x"},
			},
			want: "3 CLIs across 2 categories.",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := renderCatalogCounts(tc.entries)
			if !strings.HasSuffix(got, tc.want) {
				t.Errorf("renderCatalogCounts: want suffix %q, got:\n%s", tc.want, got)
			}
		})
	}
}

// TestUpdateReadme_RoundTrip verifies the splice preserves surrounding
// prose and that running the generator twice on the same input is a
// byte-level no-op (idempotence — the same property registry.json
// generation already guarantees, extended to README rendering).
func TestUpdateReadme_RoundTrip(t *testing.T) {
	entries := []RegistryEntry{
		{Name: "espn", Category: "media-and-entertainment", Description: "Live scores.", Path: "library/media-and-entertainment/espn"},
	}

	src := `# Title

Intro prose.

<!-- catalog-counts:begin -->
old counts
<!-- catalog-counts:end -->

Middle prose.

<!-- catalog:begin -->
old table
<!-- catalog:end -->

Trailing prose.
`

	first, err := updateReadme([]byte(src), entries)
	if err != nil {
		t.Fatalf("first updateReadme: %v", err)
	}
	second, err := updateReadme(first, entries)
	if err != nil {
		t.Fatalf("second updateReadme: %v", err)
	}
	if string(first) != string(second) {
		t.Errorf("updateReadme not idempotent\nfirst:\n%s\nsecond:\n%s", first, second)
	}
	if !strings.Contains(string(first), "# Title") || !strings.Contains(string(first), "Intro prose.") || !strings.Contains(string(first), "Middle prose.") || !strings.Contains(string(first), "Trailing prose.") {
		t.Errorf("updateReadme dropped surrounding prose; got:\n%s", first)
	}
	if strings.Contains(string(first), "old table") || strings.Contains(string(first), "old counts") {
		t.Errorf("updateReadme failed to replace sentinel content; got:\n%s", first)
	}
}

// TestDetectMCPTransports covers the source-grep detection logic.
// Encoding the detection rule in tests guards against two regressions:
// (a) a future generator template renaming NewStreamableHTTPServer to a
//
//	differently-named entry point would silently flip every dual-transport
//	CLI back to stdio-only, and the test fails before the registry is
//	re-emitted.
//
// (b) the missing-binary fallback returning nil would cause the registry
//
//	to emit `"transports": null` instead of `["stdio"]`; we lock in the
//	non-nil ["stdio"] default so the JSON shape stays a real array.
func TestDetectMCPTransports(t *testing.T) {
	stdioOnlyMain := `package main

import "github.com/mark3labs/mcp-go/server"

func main() {
	s := server.NewMCPServer("Demo", "1.0.0")
	server.ServeStdio(s)
}
`
	dualTransportMain := `package main

import "github.com/mark3labs/mcp-go/server"

func main() {
	s := server.NewMCPServer("Demo", "1.0.0")
	switch *transport {
	case "stdio":
		server.ServeStdio(s)
	case "http":
		httpSrv := server.NewStreamableHTTPServer(s)
		_ = httpSrv.Start(":7777")
	}
}
`

	cases := []struct {
		name    string
		binary  string
		writeAt string // relative to cliDir; "" means don't write
		body    string
		want    []string
	}{
		{
			name:    "stdio-only binary",
			binary:  "demo-pp-mcp",
			writeAt: "cmd/demo-pp-mcp/main.go",
			body:    stdioOnlyMain,
			want:    []string{"stdio"},
		},
		{
			name:    "dual transport binary",
			binary:  "demo-pp-mcp",
			writeAt: "cmd/demo-pp-mcp/main.go",
			body:    dualTransportMain,
			want:    []string{"stdio", "http"},
		},
		{
			name:    "missing binary file falls back to stdio",
			binary:  "demo-pp-mcp",
			writeAt: "",
			want:    []string{"stdio"},
		},
		{
			name:    "empty binary name returns stdio without filesystem read",
			binary:  "",
			writeAt: "",
			want:    []string{"stdio"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			cliDir := t.TempDir()
			if tc.writeAt != "" {
				path := filepath.Join(cliDir, tc.writeAt)
				if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
					t.Fatalf("mkdir: %v", err)
				}
				if err := os.WriteFile(path, []byte(tc.body), 0o644); err != nil {
					t.Fatalf("write main.go: %v", err)
				}
			}
			got := detectMCPTransports(cliDir, tc.binary)
			if len(got) != len(tc.want) {
				t.Fatalf("transports = %v, want %v", got, tc.want)
			}
			for i, v := range tc.want {
				if got[i] != v {
					t.Errorf("transports[%d] = %q, want %q", i, got[i], v)
				}
			}
		})
	}
}

// TestUpdateReadme_MissingSentinels ensures updateReadme errors out
// rather than silently no-oping when a README hasn't opted into the
// sentinel scheme. Silent no-op would let drift sneak back in.
func TestUpdateReadme_MissingSentinels(t *testing.T) {
	src := `# Title

No sentinels here.
`
	_, err := updateReadme([]byte(src), nil)
	if err == nil {
		t.Fatal("expected error when sentinels missing, got nil")
	}
	if !strings.Contains(err.Error(), "missing begin sentinel") {
		t.Errorf("expected missing-sentinel error, got: %v", err)
	}
}
