// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newActionPlansPeopleCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "action-plans-people",
		Short:  "Manage action plans people",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newActionPlansPeopleCreateCmd(flags))
	cmd.AddCommand(newActionPlansPeopleListCmd(flags))
	cmd.AddCommand(newActionPlansPeopleUpdateCmd(flags))
	return cmd
}
