// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bytes"
	"encoding/json"
	"path/filepath"
	"testing"
	"time"

	"follow-up-boss-pp-cli/internal/store"
)

func executeTestRoot(args ...string) ([]byte, error) {
	var flags rootFlags
	root := newRootCmd(&flags)
	var stdout, stderr bytes.Buffer
	root.SetOut(&stdout)
	root.SetErr(&stderr)
	root.SetArgs(args)
	err := root.Execute()
	if err != nil && stderr.Len() > 0 {
		return stdout.Bytes(), err
	}
	return stdout.Bytes(), err
}

func TestAgentCRMEmptyStoreOutputShape(t *testing.T) {
	missingDB := filepath.Join(t.TempDir(), "missing.db")
	out, err := executeTestRoot("--json", "agent-crm", "agenda", "today", "--db", missingDB)
	if err != nil {
		t.Fatalf("agent-crm agenda today: %v", err)
	}
	var got crmResult
	if err := json.Unmarshal(out, &got); err != nil {
		t.Fatalf("output is not crmResult JSON: %v\n%s", err, string(out))
	}
	if got.DataStatus != "empty_local_store" {
		t.Fatalf("DataStatus = %q, want empty_local_store", got.DataStatus)
	}
	if got.Items == nil {
		t.Fatalf("Items should be an empty array, got nil")
	}
	if len(got.Items) != 0 {
		t.Fatalf("Items len = %d, want 0", len(got.Items))
	}
}

func TestAgentCRMFixtureBackedNextActions(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := store.Open(dbPath)
	if err != nil {
		t.Fatalf("open store: %v", err)
	}
	defer s.Close()

	due := time.Now().Add(2 * time.Hour).UTC().Format(time.RFC3339)
	_, _, err = s.UpsertBatch("tasks", []json.RawMessage{
		json.RawMessage(`{"id":"task-1","name":"Call lead","personId":"person-1","dueDate":"` + due + `","status":"open"}`),
	})
	if err != nil {
		t.Fatalf("upsert tasks: %v", err)
	}
	_, _, err = s.UpsertBatch("people", []json.RawMessage{
		json.RawMessage(`{"id":"person-1","firstName":"Ada","lastName":"Lovelace","createdAt":"` + due + `","email":"ada@example.com","phone":"555-0100"}`),
	})
	if err != nil {
		t.Fatalf("upsert people: %v", err)
	}

	out, err := executeTestRoot("--json", "agent-crm", "next-actions", "--db", dbPath)
	if err != nil {
		t.Fatalf("agent-crm next-actions: %v", err)
	}
	var got crmResult
	if err := json.Unmarshal(out, &got); err != nil {
		t.Fatalf("output is not crmResult JSON: %v\n%s", err, string(out))
	}
	if got.DataStatus != "ok" {
		t.Fatalf("DataStatus = %q, want ok", got.DataStatus)
	}
	if len(got.Items) == 0 {
		t.Fatalf("expected at least one suggested CRM action")
	}
	item := got.Items[0]
	if item.Object.Type == "" || item.Priority == 0 || len(item.ReasonCodes) == 0 || item.ProposedAction == "" {
		t.Fatalf("agent CRM item shape is incomplete: %#v", item)
	}
	if item.Evidence == nil || item.Confidence == 0 {
		t.Fatalf("agent CRM item lacks evidence/confidence: %#v", item)
	}
}
