// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"follow-up-boss-pp-cli/internal/store"
	"github.com/spf13/cobra"
)

// PATCH: Hand-authored agent-native CRM reasoning layer for Follow Up Boss.
// It intentionally reads the local SQLite resource store instead of mirroring
// REST endpoints, so agents get prioritized actions with evidence.

type crmObjectRef struct {
	Type string `json:"type"`
	ID   string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}

type crmFinding struct {
	Object         crmObjectRef   `json:"object"`
	Priority       int            `json:"priority"`
	ReasonCodes    []string       `json:"reason_codes"`
	Evidence       map[string]any `json:"evidence"`
	Confidence     float64        `json:"confidence"`
	ProposedAction string         `json:"proposed_action"`
	ApplyCommand   string         `json:"apply_command,omitempty"`
}

type crmResult struct {
	GeneratedAt    string         `json:"generated_at"`
	DataStatus     string         `json:"data_status"`
	DBPath         string         `json:"db_path"`
	ResourceCounts map[string]int `json:"resource_counts"`
	Items          []crmFinding   `json:"items"`
}

type crmContextPack struct {
	GeneratedAt    string           `json:"generated_at"`
	DataStatus     string           `json:"data_status"`
	DBPath         string           `json:"db_path"`
	Object         crmObjectRef     `json:"object"`
	Summary        map[string]any   `json:"summary"`
	Evidence       []map[string]any `json:"evidence"`
	SuggestedItems []crmFinding     `json:"suggested_items"`
	ResourceCounts map[string]int   `json:"resource_counts"`
}

type crmDataset struct {
	dbPath     string
	status     string
	counts     map[string]int
	people     []map[string]any
	tasks      []map[string]any
	smartLists []map[string]any
	deals      []map[string]any
	pipelines  []map[string]any
}

func agentCRMAnnotations() map[string]string {
	return map[string]string{"mcp:read-only": "true", "pp:max_staleness": "1h"}
}

func newAgentCRMCmd(flags *rootFlags) *cobra.Command {
	var dbPath string
	cmd := &cobra.Command{
		Use:         "agent-crm",
		Short:       "Agent-native CRM workflows from the local Follow Up Boss store",
		Annotations: agentCRMAnnotations(),
		RunE:        parentNoSubcommandRunE(flags),
	}
	cmd.PersistentFlags().StringVar(&dbPath, "db", "", "Local SQLite database path")

	agenda := &cobra.Command{Use: "agenda", Short: "Build CRM agendas", Annotations: agentCRMAnnotations(), RunE: parentNoSubcommandRunE(flags)}
	agenda.AddCommand(&cobra.Command{
		Use:         "today",
		Short:       "Prioritize today's tasks and overdue lead work",
		Annotations: agentCRMAnnotations(),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCRMFindings(cmd, flags, dbPath, agendaTodayFindings)
		},
	})

	triage := &cobra.Command{Use: "triage", Short: "Triage CRM queues", Annotations: agentCRMAnnotations(), RunE: parentNoSubcommandRunE(flags)}
	triage.AddCommand(&cobra.Command{
		Use:         "leads",
		Short:       "Rank leads needing attention",
		Annotations: agentCRMAnnotations(),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCRMFindings(cmd, flags, dbPath, triageLeadFindings)
		},
	})

	contextCmd := &cobra.Command{Use: "context", Short: "Build compact CRM context packs", Annotations: agentCRMAnnotations(), RunE: parentNoSubcommandRunE(flags)}
	contextCmd.AddCommand(newCRMContextPersonCmd(flags, &dbPath))
	contextCmd.AddCommand(newCRMContextDealCmd(flags, &dbPath))
	contextCmd.AddCommand(newCRMContextPipelineCmd(flags, &dbPath))
	contextCmd.AddCommand(newCRMContextDayCmd(flags, &dbPath))

	cmd.AddCommand(agenda)
	cmd.AddCommand(triage)
	cmd.AddCommand(&cobra.Command{
		Use:         "speed-to-lead",
		Short:       "Find new leads without fast first contact evidence",
		Annotations: agentCRMAnnotations(),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCRMFindings(cmd, flags, dbPath, speedToLeadFindings)
		},
	})
	cmd.AddCommand(&cobra.Command{
		Use:         "followup-gaps",
		Short:       "Find stale relationships with no open task coverage",
		Annotations: agentCRMAnnotations(),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCRMFindings(cmd, flags, dbPath, followupGapFindings)
		},
	})
	cmd.AddCommand(&cobra.Command{
		Use:         "next-actions",
		Short:       "Draft next actions from tasks and lead state",
		Annotations: agentCRMAnnotations(),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCRMFindings(cmd, flags, dbPath, nextActionFindings)
		},
	})
	cmd.AddCommand(&cobra.Command{
		Use:         "data-quality",
		Short:       "Find CRM records that need cleanup before automation",
		Annotations: agentCRMAnnotations(),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCRMFindings(cmd, flags, dbPath, dataQualityFindings)
		},
	})
	cmd.AddCommand(contextCmd)
	return cmd
}

func newCRMContextPersonCmd(flags *rootFlags, dbPath *string) *cobra.Command {
	var id string
	cmd := &cobra.Command{
		Use:         "person",
		Short:       "Build a person context pack",
		Annotations: agentCRMAnnotations(),
		RunE: func(cmd *cobra.Command, args []string) error {
			ds, err := loadCRMDataset(cmd, *dbPath)
			if err != nil {
				return err
			}
			person := findCRMRecord(ds.people, id)
			pack := baseCRMContext(ds, crmObjectRef{Type: "person", ID: id})
			if person == nil {
				pack.Summary["found"] = false
				pack.SuggestedItems = []crmFinding{}
				return printJSONFiltered(cmd.OutOrStdout(), pack, flags)
			}
			pack.Object = crmRef("person", person)
			pack.Summary["found"] = true
			pack.Summary["stage"] = firstString(person, "stage", "status")
			pack.Summary["source"] = firstString(person, "source", "leadSource")
			pack.Evidence = append(pack.Evidence, crmEvidence("person_fields", person, "createdAt", "updatedAt", "lastActivityDate", "lastCommunication", "assignedTo"))
			pack.SuggestedItems = personFindings(person, ds.tasks)
			return printJSONFiltered(cmd.OutOrStdout(), pack, flags)
		},
	}
	cmd.Flags().StringVar(&id, "id", "", "Person ID from the local store")
	return cmd
}

func newCRMContextDealCmd(flags *rootFlags, dbPath *string) *cobra.Command {
	var id string
	cmd := &cobra.Command{
		Use:         "deal",
		Short:       "Build a deal context pack",
		Annotations: agentCRMAnnotations(),
		RunE: func(cmd *cobra.Command, args []string) error {
			ds, err := loadCRMDataset(cmd, *dbPath)
			if err != nil {
				return err
			}
			deal := findCRMRecord(ds.deals, id)
			pack := baseCRMContext(ds, crmObjectRef{Type: "deal", ID: id})
			if deal == nil {
				pack.Summary["found"] = false
				pack.SuggestedItems = []crmFinding{}
				return printJSONFiltered(cmd.OutOrStdout(), pack, flags)
			}
			pack.Object = crmRef("deal", deal)
			pack.Summary["found"] = true
			pack.Summary["stage"] = firstString(deal, "stage", "stageName", "status")
			pack.Summary["value"] = firstAny(deal, "value", "price", "amount")
			pack.Evidence = append(pack.Evidence, crmEvidence("deal_fields", deal, "createdAt", "updatedAt", "stage", "stageName", "status", "personId"))
			pack.SuggestedItems = []crmFinding{{
				Object:         pack.Object,
				Priority:       3,
				ReasonCodes:    []string{"deal_context_review"},
				Evidence:       map[string]any{"updated_at": firstString(deal, "updatedAt", "updated_at"), "stage": pack.Summary["stage"]},
				Confidence:     0.58,
				ProposedAction: "Review deal stage, owner, and most recent activity before drafting outreach.",
				ApplyCommand:   fmt.Sprintf("follow-up-boss-pp-cli deals get --id %s --data-source local --agent", pack.Object.ID),
			}}
			return printJSONFiltered(cmd.OutOrStdout(), pack, flags)
		},
	}
	cmd.Flags().StringVar(&id, "id", "", "Deal ID from the local store")
	return cmd
}

func newCRMContextPipelineCmd(flags *rootFlags, dbPath *string) *cobra.Command {
	return &cobra.Command{
		Use:         "pipeline",
		Short:       "Build a pipeline context pack",
		Annotations: agentCRMAnnotations(),
		RunE: func(cmd *cobra.Command, args []string) error {
			ds, err := loadCRMDataset(cmd, *dbPath)
			if err != nil {
				return err
			}
			pack := baseCRMContext(ds, crmObjectRef{Type: "pipeline"})
			pack.Summary["people_by_stage"] = groupCount(ds.people, "stage", "status")
			pack.Summary["deals_by_stage"] = groupCount(ds.deals, "stage", "stageName", "status")
			pack.Summary["smart_lists"] = compactRecords(ds.smartLists, 10)
			pack.SuggestedItems = append(followupGapFindings(ds), dataQualityFindings(ds)...)
			pack.SuggestedItems = limitFindings(pack.SuggestedItems, 10)
			pack.SuggestedItems = nonNilFindings(pack.SuggestedItems)
			return printJSONFiltered(cmd.OutOrStdout(), pack, flags)
		},
	}
}

func newCRMContextDayCmd(flags *rootFlags, dbPath *string) *cobra.Command {
	return &cobra.Command{
		Use:         "day",
		Short:       "Build a day context pack",
		Annotations: agentCRMAnnotations(),
		RunE: func(cmd *cobra.Command, args []string) error {
			ds, err := loadCRMDataset(cmd, *dbPath)
			if err != nil {
				return err
			}
			pack := baseCRMContext(ds, crmObjectRef{Type: "day", ID: time.Now().Format("2006-01-02")})
			pack.Summary["due_today_or_overdue"] = len(dueTasks(ds.tasks, time.Now(), 24*time.Hour))
			pack.Summary["new_people_24h"] = countRecent(ds.people, "createdAt", 24*time.Hour)
			pack.SuggestedItems = agendaTodayFindings(ds)
			pack.SuggestedItems = nonNilFindings(pack.SuggestedItems)
			return printJSONFiltered(cmd.OutOrStdout(), pack, flags)
		},
	}
}

func runCRMFindings(cmd *cobra.Command, flags *rootFlags, dbPath string, build func(crmDataset) []crmFinding) error {
	ds, err := loadCRMDataset(cmd, dbPath)
	if err != nil {
		return err
	}
	items := limitFindings(build(ds), 25)
	items = nonNilFindings(items)
	result := crmResult{
		GeneratedAt:    time.Now().Format(time.RFC3339),
		DataStatus:     ds.status,
		DBPath:         ds.dbPath,
		ResourceCounts: ds.counts,
		Items:          items,
	}
	return printJSONFiltered(cmd.OutOrStdout(), result, flags)
}

func nonNilFindings(items []crmFinding) []crmFinding {
	if items == nil {
		return []crmFinding{}
	}
	return items
}

func loadCRMDataset(cmd *cobra.Command, dbPath string) (crmDataset, error) {
	if dbPath == "" {
		dbPath = defaultDBPath("follow-up-boss-pp-cli")
	}
	ds := crmDataset{dbPath: dbPath, status: "empty_local_store", counts: map[string]int{}}
	db, err := openCRMStore(cmd, dbPath)
	if err != nil {
		return ds, err
	}
	if db == nil {
		return ds, nil
	}
	defer db.Close()
	warnCRMStaleness(cmd, db)
	counts, err := db.Status()
	if err != nil {
		return ds, fmt.Errorf("reading local CRM status: %w", err)
	}
	ds.status = "ok"
	ds.counts = counts
	ds.people = loadCRMResource(db, "people", 500)
	ds.tasks = loadCRMResource(db, "tasks", 500)
	ds.smartLists = loadCRMResource(db, "smart-lists", 200)
	ds.deals = loadCRMResource(db, "deals", 500)
	ds.pipelines = loadCRMResource(db, "pipelines", 200)
	return ds, nil
}

func openCRMStore(cmd *cobra.Command, dbPath string) (*store.Store, error) {
	if _, err := os.Stat(dbPath); os.IsNotExist(err) {
		return nil, nil
	}
	db, err := store.OpenReadOnly(dbPath)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		if strings.Contains(err.Error(), "unable to open database file") || strings.Contains(err.Error(), "out of memory") {
			return nil, nil
		}
		return nil, fmt.Errorf("opening local CRM database: %w", err)
	}
	return db, nil
}

func warnCRMStaleness(cmd *cobra.Command, db *store.Store) {
	if cmd == nil || db == nil {
		return
	}
	max, err := time.ParseDuration(cmdAnnotation(cmd, "pp:max_staleness"))
	if err != nil || max <= 0 {
		return
	}
	var raw any
	if err := db.DB().QueryRow(`SELECT MIN(last_synced_at) FROM sync_state`).Scan(&raw); err != nil {
		if !strings.Contains(err.Error(), "no such table") {
			fmt.Fprintf(os.Stderr, "warning: follow-up-boss-pp-cli cache freshness unknown for %s (%v)\n", cmd.CommandPath(), err)
		}
		return
	}
	lastSynced, ok := parseCRMStalenessTime(raw)
	if !ok {
		fmt.Fprintf(os.Stderr, "warning: follow-up-boss-pp-cli cache has no sync_state evidence for %s (max_staleness=%s)\n", cmd.CommandPath(), max)
		return
	}
	if age := time.Since(lastSynced); age > max {
		fmt.Fprintf(os.Stderr, "warning: follow-up-boss-pp-cli cache for %s is stale (age=%s, max_staleness=%s)\n", cmd.CommandPath(), age.Round(time.Second), max)
	}
}

func cmdAnnotation(cmd *cobra.Command, key string) string {
	for c := cmd; c != nil; c = c.Parent() {
		if c.Annotations == nil {
			continue
		}
		if value := strings.TrimSpace(c.Annotations[key]); value != "" {
			return value
		}
	}
	return ""
}

func parseCRMStalenessTime(value any) (time.Time, bool) {
	switch v := value.(type) {
	case nil:
		return time.Time{}, false
	case time.Time:
		return v, true
	case string:
		return parseCRMStalenessTimeString(v)
	case []byte:
		return parseCRMStalenessTimeString(string(v))
	default:
		return time.Time{}, false
	}
}

func parseCRMStalenessTimeString(value string) (time.Time, bool) {
	value = strings.TrimSpace(value)
	if value == "" {
		return time.Time{}, false
	}
	for _, layout := range []string{
		time.RFC3339Nano,
		time.RFC3339,
		time.DateTime,
		"2006-01-02 15:04:05.999999999-07:00",
		"2006-01-02 15:04:05.999999999Z07:00",
		"2006-01-02 15:04:05.999999999 -0700 MST",
		"2006-01-02 15:04:05.999999999 -0700",
		"2006-01-02 15:04:05 -0700 MST",
		"2006-01-02 15:04:05 -0700",
	} {
		if t, err := time.Parse(layout, value); err == nil {
			return t, true
		}
	}
	return time.Time{}, false
}

func loadCRMResource(db *store.Store, resourceType string, limit int) []map[string]any {
	raw, err := db.List(resourceType, limit)
	if err != nil {
		return nil
	}
	out := make([]map[string]any, 0, len(raw))
	for _, item := range raw {
		var obj map[string]any
		if json.Unmarshal(item, &obj) == nil {
			out = append(out, obj)
		}
	}
	return out
}

func agendaTodayFindings(ds crmDataset) []crmFinding {
	now := time.Now()
	var out []crmFinding
	for _, task := range dueTasks(ds.tasks, now, 24*time.Hour) {
		out = append(out, taskFinding(task, "due_today_or_overdue", 1, "Complete or reschedule this CRM task today."))
	}
	out = append(out, speedToLeadFindings(ds)...)
	return sortFindings(out)
}

func triageLeadFindings(ds crmDataset) []crmFinding {
	var out []crmFinding
	out = append(out, speedToLeadFindings(ds)...)
	out = append(out, followupGapFindings(ds)...)
	out = append(out, dataQualityFindings(ds)...)
	return sortFindings(out)
}

func speedToLeadFindings(ds crmDataset) []crmFinding {
	var out []crmFinding
	now := time.Now()
	for _, person := range ds.people {
		created, ok := firstTime(person, "createdAt", "created_at")
		if !ok || now.Sub(created) > 24*time.Hour {
			continue
		}
		lastContact, contacted := firstTime(person, "lastCommunication", "lastCommunicationAt", "lastActivityDate", "updatedAt")
		if contacted && lastContact.Sub(created) <= 5*time.Minute {
			continue
		}
		out = append(out, crmFinding{
			Object:         crmRef("person", person),
			Priority:       1,
			ReasonCodes:    []string{"new_lead", "speed_to_lead_gap"},
			Evidence:       map[string]any{"created_at": created.Format(time.RFC3339), "last_contact_at": timeOrNil(lastContact, contacted)},
			Confidence:     0.72,
			ProposedAction: "Attempt first response now, then create a same-day follow-up task if contact is not made.",
			ApplyCommand:   fmt.Sprintf("follow-up-boss-pp-cli tasks create --person-id %s --agent", recordID(person)),
		})
	}
	return sortFindings(out)
}

func followupGapFindings(ds crmDataset) []crmFinding {
	var out []crmFinding
	openTasks := openTaskPersonSet(ds.tasks)
	for _, person := range ds.people {
		id := recordID(person)
		if id == "" || openTasks[id] {
			continue
		}
		lastTouch, ok := firstTime(person, "lastCommunication", "lastCommunicationAt", "lastActivityDate", "updatedAt")
		if !ok || time.Since(lastTouch) < 7*24*time.Hour {
			continue
		}
		out = append(out, crmFinding{
			Object:         crmRef("person", person),
			Priority:       2,
			ReasonCodes:    []string{"stale_relationship", "no_open_task"},
			Evidence:       map[string]any{"last_touch_at": lastTouch.Format(time.RFC3339), "open_task_found": false},
			Confidence:     0.68,
			ProposedAction: "Draft a check-in or create a follow-up task based on the last known stage/source.",
			ApplyCommand:   fmt.Sprintf("follow-up-boss-pp-cli tasks create --person-id %s --agent", id),
		})
	}
	return sortFindings(out)
}

func nextActionFindings(ds crmDataset) []crmFinding {
	var out []crmFinding
	for _, task := range ds.tasks {
		if isTaskClosed(task) {
			continue
		}
		out = append(out, taskFinding(task, "open_task", 2, "Use this task as the next concrete CRM action."))
	}
	out = append(out, followupGapFindings(ds)...)
	return sortFindings(out)
}

func dataQualityFindings(ds crmDataset) []crmFinding {
	var out []crmFinding
	for _, person := range ds.people {
		var reasons []string
		if recordName(person) == "" {
			reasons = append(reasons, "missing_name")
		}
		if !hasContactField(person, "email", "emails") {
			reasons = append(reasons, "missing_email")
		}
		if !hasContactField(person, "phone", "phones", "mobilePhone", "homePhone") {
			reasons = append(reasons, "missing_phone")
		}
		if len(reasons) == 0 {
			continue
		}
		out = append(out, crmFinding{
			Object:         crmRef("person", person),
			Priority:       3,
			ReasonCodes:    reasons,
			Evidence:       map[string]any{"fields_checked": []string{"name", "email", "phone"}, "updated_at": firstString(person, "updatedAt", "updated_at")},
			Confidence:     0.8,
			ProposedAction: "Fill missing contact fields before enrolling this record in automation.",
			ApplyCommand:   fmt.Sprintf("follow-up-boss-pp-cli people update --id %s --agent", recordID(person)),
		})
	}
	return sortFindings(out)
}

func personFindings(person map[string]any, tasks []map[string]any) []crmFinding {
	ds := crmDataset{people: []map[string]any{person}, tasks: tasks}
	return limitFindings(append(followupGapFindings(ds), dataQualityFindings(ds)...), 10)
}

func taskFinding(task map[string]any, reason string, priority int, action string) crmFinding {
	return crmFinding{
		Object:         crmRef("task", task),
		Priority:       priority,
		ReasonCodes:    []string{reason},
		Evidence:       map[string]any{"due_at": firstString(task, "dueDate", "dueAt", "due_at"), "person_id": firstString(task, "personId", "person_id")},
		Confidence:     0.74,
		ProposedAction: action,
		ApplyCommand:   fmt.Sprintf("follow-up-boss-pp-cli tasks update --id %s --agent", recordID(task)),
	}
}

func baseCRMContext(ds crmDataset, obj crmObjectRef) crmContextPack {
	return crmContextPack{
		GeneratedAt:    time.Now().Format(time.RFC3339),
		DataStatus:     ds.status,
		DBPath:         ds.dbPath,
		Object:         obj,
		Summary:        map[string]any{},
		Evidence:       []map[string]any{},
		SuggestedItems: []crmFinding{},
		ResourceCounts: ds.counts,
	}
}

func dueTasks(tasks []map[string]any, now time.Time, window time.Duration) []map[string]any {
	var out []map[string]any
	for _, task := range tasks {
		if isTaskClosed(task) {
			continue
		}
		due, ok := firstTime(task, "dueDate", "dueAt", "due_at")
		if ok && due.Before(now.Add(window)) {
			out = append(out, task)
		}
	}
	return out
}

func isTaskClosed(task map[string]any) bool {
	if b, ok := firstAny(task, "isCompleted", "completed").(bool); ok && b {
		return true
	}
	return firstString(task, "completedAt", "completed_at", "status") == "completed"
}

func openTaskPersonSet(tasks []map[string]any) map[string]bool {
	out := map[string]bool{}
	for _, task := range tasks {
		if isTaskClosed(task) {
			continue
		}
		if id := firstString(task, "personId", "person_id"); id != "" {
			out[id] = true
		}
	}
	return out
}

func findCRMRecord(records []map[string]any, id string) map[string]any {
	if id == "" {
		return nil
	}
	for _, record := range records {
		if recordID(record) == id {
			return record
		}
	}
	return nil
}

func crmRef(resourceType string, record map[string]any) crmObjectRef {
	return crmObjectRef{Type: resourceType, ID: recordID(record), Name: recordName(record)}
}

func recordID(record map[string]any) string {
	return firstString(record, "id", "_id", "uuid")
}

func recordName(record map[string]any) string {
	if name := firstString(record, "name", "title", "fullName"); name != "" {
		return name
	}
	first := firstString(record, "firstName", "first_name")
	last := firstString(record, "lastName", "last_name")
	return strings.TrimSpace(first + " " + last)
}

func firstAny(record map[string]any, keys ...string) any {
	for _, key := range keys {
		if v, ok := record[key]; ok && v != nil {
			return v
		}
	}
	return nil
}

func firstString(record map[string]any, keys ...string) string {
	for _, key := range keys {
		if v, ok := record[key]; ok && v != nil {
			switch t := v.(type) {
			case string:
				return strings.TrimSpace(t)
			case json.Number:
				return t.String()
			default:
				return strings.TrimSpace(fmt.Sprintf("%v", t))
			}
		}
	}
	return ""
}

func firstTime(record map[string]any, keys ...string) (time.Time, bool) {
	for _, key := range keys {
		raw := firstString(record, key)
		if raw == "" {
			continue
		}
		for _, layout := range []string{time.RFC3339, "2006-01-02T15:04:05Z", "2006-01-02 15:04:05", "2006-01-02"} {
			if t, err := time.Parse(layout, raw); err == nil {
				return t, true
			}
		}
	}
	return time.Time{}, false
}

func timeOrNil(t time.Time, ok bool) any {
	if !ok {
		return nil
	}
	return t.Format(time.RFC3339)
}

func hasContactField(record map[string]any, keys ...string) bool {
	for _, key := range keys {
		v := firstAny(record, key)
		switch t := v.(type) {
		case string:
			if strings.TrimSpace(t) != "" {
				return true
			}
		case []any:
			if len(t) > 0 {
				return true
			}
		case []map[string]any:
			if len(t) > 0 {
				return true
			}
		}
	}
	return false
}

func crmEvidence(label string, record map[string]any, keys ...string) map[string]any {
	out := map[string]any{"label": label}
	for _, key := range keys {
		if v := firstAny(record, key); v != nil {
			out[key] = v
		}
	}
	return out
}

func groupCount(records []map[string]any, keys ...string) map[string]int {
	out := map[string]int{}
	for _, record := range records {
		key := firstString(record, keys...)
		if key == "" {
			key = "unknown"
		}
		out[key]++
	}
	return out
}

func compactRecords(records []map[string]any, limit int) []crmObjectRef {
	if len(records) > limit {
		records = records[:limit]
	}
	out := make([]crmObjectRef, 0, len(records))
	for _, record := range records {
		out = append(out, crmRef("smart-list", record))
	}
	return out
}

func countRecent(records []map[string]any, field string, window time.Duration) int {
	count := 0
	for _, record := range records {
		if t, ok := firstTime(record, field); ok && time.Since(t) <= window {
			count++
		}
	}
	return count
}

func sortFindings(items []crmFinding) []crmFinding {
	sort.SliceStable(items, func(i, j int) bool {
		if items[i].Priority != items[j].Priority {
			return items[i].Priority < items[j].Priority
		}
		return items[i].Object.ID < items[j].Object.ID
	})
	return items
}

func limitFindings(items []crmFinding, limit int) []crmFinding {
	items = sortFindings(items)
	if limit > 0 && len(items) > limit {
		return items[:limit]
	}
	return items
}
