// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAppointmentOutcomesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "appointment-outcomes",
		Short:  "Manage appointment outcomes",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAppointmentOutcomesCreateCmd(flags))
	cmd.AddCommand(newAppointmentOutcomesDeleteCmd(flags))
	cmd.AddCommand(newAppointmentOutcomesGetCmd(flags))
	cmd.AddCommand(newAppointmentOutcomesListCmd(flags))
	cmd.AddCommand(newAppointmentOutcomesUpdateCmd(flags))
	return cmd
}
