// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAppointmentTypesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "appointment-types",
		Short:  "Manage appointment types",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAppointmentTypesCreateCmd(flags))
	cmd.AddCommand(newAppointmentTypesDeleteCmd(flags))
	cmd.AddCommand(newAppointmentTypesGetCmd(flags))
	cmd.AddCommand(newAppointmentTypesListCmd(flags))
	cmd.AddCommand(newAppointmentTypesUpdateCmd(flags))
	return cmd
}
