// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAppointmentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "appointments",
		Short:  "Manage appointments",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAppointmentsCreateCmd(flags))
	cmd.AddCommand(newAppointmentsDeleteCmd(flags))
	cmd.AddCommand(newAppointmentsGetCmd(flags))
	cmd.AddCommand(newAppointmentsListCmd(flags))
	cmd.AddCommand(newAppointmentsUpdateCmd(flags))
	return cmd
}
