// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"context"
	"encoding/json"
	"fmt"
	"follow-up-boss-pp-cli/internal/cliutil"
	"follow-up-boss-pp-cli/internal/config"
	"github.com/spf13/cobra"
	"io"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"runtime"
	"strings"
	"time"
)

// PATCH: Follow Up Boss OAuth helpers are hand-authored because the generated
// API surface only knows REST endpoints, not the browser/token helper flow.
const followUpBossOAuthAuthorizeURL = "https://app.followupboss.com/oauth/authorize"
const followUpBossOAuthTokenURL = "https://app.followupboss.com/oauth/token"

func newAuthCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "auth",
		Short: "Manage authentication for Follow Up Boss",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAuthSetupCmd(flags))
	cmd.AddCommand(newAuthStatusCmd(flags))
	cmd.AddCommand(newAuthSetTokenCmd(flags))
	cmd.AddCommand(newAuthOAuthURLCmd(flags))
	cmd.AddCommand(newAuthOAuthTokenCmd(flags))
	cmd.AddCommand(newAuthOAuthRefreshCmd(flags))
	cmd.AddCommand(newAuthLogoutCmd(flags))

	return cmd
}

func newAuthOAuthURLCmd(flags *rootFlags) *cobra.Command {
	var clientID string
	var redirectURI string
	var state string
	var scope string
	cmd := &cobra.Command{
		Use:     "oauth-url",
		Short:   "Build a Follow Up Boss OAuth authorization URL",
		Example: "  follow-up-boss-pp-cli auth oauth-url --client-id CLIENT_ID --redirect-uri https://example.com/callback",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}
			if clientID == "" {
				clientID = cfg.ClientID
			}
			if clientID == "" {
				return usageErr(fmt.Errorf("--client-id is required unless client_id is saved in config or FUB_CLIENT_ID is set"))
			}
			if redirectURI == "" {
				return usageErr(fmt.Errorf("--redirect-uri is required"))
			}
			u, err := buildOAuthURL(clientID, redirectURI, state, scope)
			if err != nil {
				return usageErr(err)
			}
			if flags.asJSON {
				return printJSONFiltered(cmd.OutOrStdout(), map[string]any{"authorize_url": u}, flags)
			}
			fmt.Fprintln(cmd.OutOrStdout(), u)
			return nil
		},
	}
	cmd.Flags().StringVar(&clientID, "client-id", "", "OAuth client ID (defaults to config client_id or FUB_CLIENT_ID)")
	cmd.Flags().StringVar(&redirectURI, "redirect-uri", "", "OAuth redirect URI registered with Follow Up Boss")
	cmd.Flags().StringVar(&state, "state", "", "Opaque state value to include in the authorization URL")
	cmd.Flags().StringVar(&scope, "scope", "", "Optional OAuth scope string")
	return cmd
}

func newAuthOAuthTokenCmd(flags *rootFlags) *cobra.Command {
	var clientID string
	var clientSecret string
	var code string
	var redirectURI string
	var tokenURL string
	cmd := &cobra.Command{
		Use:     "oauth-token",
		Short:   "Exchange an OAuth authorization code and save the tokens",
		Example: "  follow-up-boss-pp-cli auth oauth-token --client-id CLIENT_ID --client-secret CLIENT_SECRET --code CODE --redirect-uri https://example.com/callback",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}
			clientID, clientSecret = resolveOAuthClient(cfg, clientID, clientSecret)
			if clientID == "" {
				return usageErr(fmt.Errorf("--client-id is required unless client_id is saved in config or FUB_CLIENT_ID is set"))
			}
			if clientSecret == "" {
				return usageErr(fmt.Errorf("--client-secret is required unless client_secret is saved in config or FUB_CLIENT_SECRET is set"))
			}
			if code == "" {
				return usageErr(fmt.Errorf("--code is required"))
			}
			if redirectURI == "" {
				return usageErr(fmt.Errorf("--redirect-uri is required"))
			}
			token, err := exchangeOAuthToken(cmd.Context(), http.DefaultClient, tokenURL, clientID, clientSecret, url.Values{
				"grant_type":   {"authorization_code"},
				"code":         {code},
				"redirect_uri": {redirectURI},
			})
			if err != nil {
				return authErr(err)
			}
			expiry := oauthExpiry(token.ExpiresIn)
			if err := cfg.SaveTokens(clientID, clientSecret, token.AccessToken, token.RefreshToken, expiry); err != nil {
				return configErr(fmt.Errorf("saving OAuth tokens: %w", err))
			}
			return printOAuthSaved(cmd, flags, cfg.Path, expiry, token.RefreshToken != "")
		},
	}
	cmd.Flags().StringVar(&clientID, "client-id", "", "OAuth client ID (defaults to config client_id or FUB_CLIENT_ID)")
	cmd.Flags().StringVar(&clientSecret, "client-secret", "", "OAuth client secret (defaults to config client_secret or FUB_CLIENT_SECRET)")
	cmd.Flags().StringVar(&code, "code", "", "Authorization code returned by Follow Up Boss")
	cmd.Flags().StringVar(&redirectURI, "redirect-uri", "", "Redirect URI used for the authorization request")
	cmd.Flags().StringVar(&tokenURL, "token-url", followUpBossOAuthTokenURL, "OAuth token endpoint")
	_ = cmd.Flags().MarkHidden("token-url")
	return cmd
}

func newAuthOAuthRefreshCmd(flags *rootFlags) *cobra.Command {
	var clientID string
	var clientSecret string
	var refreshToken string
	var tokenURL string
	cmd := &cobra.Command{
		Use:     "oauth-refresh",
		Short:   "Refresh saved OAuth tokens",
		Example: "  follow-up-boss-pp-cli auth oauth-refresh",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}
			clientID, clientSecret = resolveOAuthClient(cfg, clientID, clientSecret)
			if refreshToken == "" {
				refreshToken = cfg.RefreshToken
			}
			if clientID == "" {
				return usageErr(fmt.Errorf("--client-id is required unless client_id is saved in config or FUB_CLIENT_ID is set"))
			}
			if clientSecret == "" {
				return usageErr(fmt.Errorf("--client-secret is required unless client_secret is saved in config or FUB_CLIENT_SECRET is set"))
			}
			if refreshToken == "" {
				return usageErr(fmt.Errorf("--refresh-token is required unless a refresh token is saved in config"))
			}
			token, err := exchangeOAuthToken(cmd.Context(), http.DefaultClient, tokenURL, clientID, clientSecret, url.Values{
				"grant_type":    {"refresh_token"},
				"refresh_token": {refreshToken},
			})
			if err != nil {
				return authErr(err)
			}
			if token.RefreshToken == "" {
				token.RefreshToken = refreshToken
			}
			expiry := oauthExpiry(token.ExpiresIn)
			if err := cfg.SaveTokens(clientID, clientSecret, token.AccessToken, token.RefreshToken, expiry); err != nil {
				return configErr(fmt.Errorf("saving OAuth tokens: %w", err))
			}
			return printOAuthSaved(cmd, flags, cfg.Path, expiry, token.RefreshToken != "")
		},
	}
	cmd.Flags().StringVar(&clientID, "client-id", "", "OAuth client ID (defaults to config client_id or FUB_CLIENT_ID)")
	cmd.Flags().StringVar(&clientSecret, "client-secret", "", "OAuth client secret (defaults to config client_secret or FUB_CLIENT_SECRET)")
	cmd.Flags().StringVar(&refreshToken, "refresh-token", "", "Refresh token (defaults to config refresh_token)")
	cmd.Flags().StringVar(&tokenURL, "token-url", followUpBossOAuthTokenURL, "OAuth token endpoint")
	_ = cmd.Flags().MarkHidden("token-url")
	return cmd
}

func buildOAuthURL(clientID, redirectURI, state, scope string) (string, error) {
	if clientID == "" || redirectURI == "" {
		return "", fmt.Errorf("client-id and redirect-uri are required")
	}
	u, err := url.Parse(followUpBossOAuthAuthorizeURL)
	if err != nil {
		return "", err
	}
	q := u.Query()
	q.Set("response_type", "code")
	q.Set("client_id", clientID)
	q.Set("redirect_uri", redirectURI)
	if state != "" {
		q.Set("state", state)
	}
	if scope != "" {
		q.Set("scope", scope)
	}
	u.RawQuery = q.Encode()
	return u.String(), nil
}

func resolveOAuthClient(cfg *config.Config, clientID, clientSecret string) (string, string) {
	if clientID == "" {
		clientID = cfg.ClientID
	}
	if clientSecret == "" {
		clientSecret = cfg.ClientSecret
	}
	return clientID, clientSecret
}

type oauthTokenResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int    `json:"expires_in"`
	TokenType    string `json:"token_type"`
}

func exchangeOAuthToken(ctx context.Context, httpClient *http.Client, tokenURL, clientID, clientSecret string, form url.Values) (*oauthTokenResponse, error) {
	req, err := http.NewRequestWithContext(ctx, "POST", tokenURL, strings.NewReader(form.Encode()))
	if err != nil {
		return nil, fmt.Errorf("creating token request: %w", err)
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Set("Accept", "application/json")
	req.SetBasicAuth(clientID, clientSecret)
	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("requesting OAuth token: %w", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return nil, fmt.Errorf("reading OAuth token response: %w", err)
	}
	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("OAuth token endpoint returned HTTP %d", resp.StatusCode)
	}
	var token oauthTokenResponse
	if err := json.Unmarshal(body, &token); err != nil {
		return nil, fmt.Errorf("parsing OAuth token response: %w", err)
	}
	if token.AccessToken == "" {
		return nil, fmt.Errorf("OAuth token response did not include an access_token")
	}
	return &token, nil
}

func oauthExpiry(expiresIn int) time.Time {
	if expiresIn <= 0 {
		return time.Time{}
	}
	return time.Now().Add(time.Duration(expiresIn) * time.Second)
}

func printOAuthSaved(cmd *cobra.Command, flags *rootFlags, configPath string, expiry time.Time, hasRefreshToken bool) error {
	out := map[string]any{
		"saved":             true,
		"config_path":       configPath,
		"has_access_token":  true,
		"has_refresh_token": hasRefreshToken,
	}
	if !expiry.IsZero() {
		out["token_expiry"] = expiry.Format(time.RFC3339)
	}
	if flags.asJSON {
		return printJSONFiltered(cmd.OutOrStdout(), out, flags)
	}
	fmt.Fprintf(cmd.OutOrStdout(), "OAuth tokens saved to %s\n", configPath)
	if !expiry.IsZero() {
		fmt.Fprintf(cmd.OutOrStdout(), "Access token expires at %s\n", expiry.Format(time.RFC3339))
	}
	if !hasRefreshToken {
		fmt.Fprintln(cmd.OutOrStdout(), "No refresh token was returned.")
	}
	return nil
}

// newAuthSetupCmd prints concrete steps for getting a credential. Side-effect
// rule: print by default, --launch opt-in to open the URL, short-circuit when
// the verifier is running this in a sandboxed subprocess.
func newAuthSetupCmd(_ *rootFlags) *cobra.Command {
	var launch bool
	cmd := &cobra.Command{
		Use:     "setup",
		Short:   "Print steps for obtaining a credential (use --launch to open the URL)",
		Example: "  follow-up-boss-pp-cli auth setup\n  follow-up-boss-pp-cli auth setup --launch",
		RunE: func(cmd *cobra.Command, args []string) error {
			w := cmd.OutOrStdout()
			fmt.Fprintln(w, "Get a key at: https://docs.followupboss.com/reference/authentication")
			fmt.Fprintln(w, "  Use a Follow Up Boss API key; the printed CLI encodes it as Basic key-colon auth.")
			fmt.Fprintln(w, "")
			fmt.Fprintln(w, "Then set:")
			fmt.Fprintln(w, "  export FUB_API_KEY=\"<your-token>\"")
			fmt.Fprintln(w, "  follow-up-boss-pp-cli auth set-token <token>")
			if !launch {
				return nil
			}
			launchURL := "https://docs.followupboss.com/reference/authentication"
			if cliutil.IsVerifyEnv() {
				fmt.Fprintf(w, "would launch: %s\n", launchURL)
				return nil
			}
			if err := openSetupURL(launchURL); err != nil {
				fmt.Fprintf(cmd.ErrOrStderr(), "could not open browser automatically: %v\nopen this URL manually: %s\n", err, launchURL)
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&launch, "launch", false, "Open the setup URL in your default browser")
	return cmd
}

// openSetupURL opens url in the OS default browser. Per the side-effect rule,
// the caller short-circuits with cliutil.IsVerifyEnv() before this is reached.
func openSetupURL(url string) error {
	var c *exec.Cmd
	switch runtime.GOOS {
	case "darwin":
		c = exec.Command("open", url)
	case "linux":
		c = exec.Command("xdg-open", url)
	case "windows":
		c = exec.Command("rundll32", "url.dll,FileProtocolHandler", url)
	default:
		return fmt.Errorf("unsupported OS: %s", runtime.GOOS)
	}
	return c.Start()
}

func newAuthStatusCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "status",
		Short:   "Show authentication status",
		Example: "  follow-up-boss-pp-cli auth status",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			w := cmd.OutOrStdout()
			header := cfg.AuthHeader()
			authed := header != ""
			// JSON envelope: {authenticated, verified, source, config}. When not
			// authenticated, write the envelope first then return authErr
			// so exit code carries the auth-failure signal.
			if flags.asJSON {
				out := map[string]any{
					"authenticated": authed,
					"verified":      false,
					"source":        cfg.AuthSource,
					"config":        cfg.Path,
				}
				if printErr := printJSONFiltered(w, out, flags); printErr != nil {
					return printErr
				}
				if !authed {
					return authErr(fmt.Errorf("no credentials configured"))
				}
				return nil
			}
			if !authed {
				fmt.Fprintln(w, red("Not authenticated"))
				fmt.Fprintln(w, "")
				fmt.Fprintln(w, "Set your token:")
				fmt.Fprintln(w, "  export FUB_API_KEY=\"your-token-here\"")
				fmt.Fprintf(w, "  follow-up-boss-pp-cli auth set-token <token>\n")
				return authErr(fmt.Errorf("no credentials configured"))
			}

			fmt.Fprintln(w, green("Credentials present (not verified)"))
			fmt.Fprintf(w, "  Source: %s\n", cfg.AuthSource)
			fmt.Fprintf(w, "  Config: %s\n", cfg.Path)
			return nil
		},
	}
}

func newAuthSetTokenCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "set-token <token>",
		Short:   "Save an API token to the config file",
		Example: "  follow-up-boss-pp-cli auth set-token YOUR_TOKEN_HERE",
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			// Clear any legacy auth_header so AuthHeader() falls through to
			// the newly-saved credential. Without this, a pre-existing
			// auth_header value (common after regenerate) shadows the saved
			// token and set-token silently has no effect. Silent clear (no
			// log line): a masked-tail variant could leak token bytes through
			// scripted dogfood that captures stderr.
			cfg.AuthHeaderVal = ""
			// api_key auth: AuthHeader() reads the env-var-derived field, not
			// AccessToken. Writing the token to AccessToken via SaveTokens
			// would persist the bytes but leave doctor reporting "not
			// configured" — the slot the header builder consults stays empty.
			if err := cfg.SaveCredential(args[0]); err != nil {
				return configErr(fmt.Errorf("saving token: %w", err))
			}

			// JSON envelope: {saved, config_path}.
			if flags.asJSON {
				return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
					"saved":       true,
					"config_path": cfg.Path,
				}, flags)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Token saved to %s\n", cfg.Path)
			return nil
		},
	}
}

func newAuthLogoutCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "logout",
		Short:   "Clear stored credentials",
		Example: "  follow-up-boss-pp-cli auth logout",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			if err := cfg.ClearTokens(); err != nil {
				return configErr(fmt.Errorf("clearing tokens: %w", err))
			}

			// Identify which (if any) auth env var is still exported so the
			// JSON envelope and the human prose can both surface it.
			envStillSet := ""
			if envStillSet == "" && os.Getenv("FUB_API_KEY") != "" {
				envStillSet = "FUB_API_KEY"
			}

			// JSON envelope: {cleared: true, note?: "<env_var> env var is still set"}.
			if flags.asJSON {
				out := map[string]any{"cleared": true}
				if envStillSet != "" {
					out["note"] = envStillSet + " env var is still set"
				}
				return printJSONFiltered(cmd.OutOrStdout(), out, flags)
			}

			if envStillSet != "" {
				fmt.Fprintf(cmd.OutOrStdout(), "Config cleared. Note: %s env var is still set.\n", envStillSet)
				return nil
			}
			fmt.Fprintln(cmd.OutOrStdout(), "Logged out. Credentials cleared.")
			return nil
		},
	}
}
