// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"net/url"
	"path/filepath"
	"strings"
	"testing"
)

func TestBuildOAuthURL(t *testing.T) {
	got, err := buildOAuthURL("client-id", "https://example.com/callback", "state-1", "read write")
	if err != nil {
		t.Fatalf("buildOAuthURL: %v", err)
	}
	u, err := url.Parse(got)
	if err != nil {
		t.Fatalf("parse URL: %v", err)
	}
	if u.Scheme+"://"+u.Host+u.Path != followUpBossOAuthAuthorizeURL {
		t.Fatalf("authorize URL = %s, want %s", u.Scheme+"://"+u.Host+u.Path, followUpBossOAuthAuthorizeURL)
	}
	q := u.Query()
	if q.Get("response_type") != "code" || q.Get("client_id") != "client-id" || q.Get("redirect_uri") != "https://example.com/callback" {
		t.Fatalf("unexpected query: %s", u.RawQuery)
	}
	if q.Get("state") != "state-1" || q.Get("scope") != "read write" {
		t.Fatalf("state/scope missing from query: %s", u.RawQuery)
	}
}

func TestAuthOAuthToken_SavesTokensWithoutPrintingRawToken(t *testing.T) {
	var sawBasicAuth bool
	var sawForm bool
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		auth := r.Header.Get("Authorization")
		wantAuth := "Basic " + base64.StdEncoding.EncodeToString([]byte("client-id:client-secret"))
		sawBasicAuth = auth == wantAuth
		if err := r.ParseForm(); err != nil {
			t.Fatalf("ParseForm: %v", err)
		}
		sawForm = r.Form.Get("grant_type") == "authorization_code" &&
			r.Form.Get("code") == "code-123" &&
			r.Form.Get("redirect_uri") == "https://example.com/callback"
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"access_token":"access-secret","refresh_token":"refresh-secret","expires_in":3600,"token_type":"Bearer"}`))
	}))
	defer server.Close()

	configPath := filepath.Join(t.TempDir(), "config.toml")
	var flags rootFlags
	root := newRootCmd(&flags)
	var stdout, stderr bytes.Buffer
	root.SetOut(&stdout)
	root.SetErr(&stderr)
	root.SetArgs([]string{
		"--config", configPath,
		"--json",
		"auth", "oauth-token",
		"--client-id", "client-id",
		"--client-secret", "client-secret",
		"--code", "code-123",
		"--redirect-uri", "https://example.com/callback",
		"--token-url", server.URL,
	})
	if err := root.Execute(); err != nil {
		t.Fatalf("Execute: %v\nstderr=%s", err, stderr.String())
	}
	if !sawBasicAuth {
		t.Fatalf("token exchange did not use HTTP Basic client auth")
	}
	if !sawForm {
		t.Fatalf("token exchange did not send expected form fields")
	}
	if strings.Contains(stdout.String(), "access-secret") || strings.Contains(stdout.String(), "refresh-secret") {
		t.Fatalf("raw tokens leaked in output: %s", stdout.String())
	}
	var out map[string]any
	if err := json.Unmarshal(stdout.Bytes(), &out); err != nil {
		t.Fatalf("output is not JSON: %v\n%s", err, stdout.String())
	}
	if out["saved"] != true || out["has_access_token"] != true || out["has_refresh_token"] != true {
		t.Fatalf("unexpected output envelope: %#v", out)
	}
}
