// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAutomationsPeopleCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "automations-people",
		Short:  "Manage automations people",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAutomationsPeopleCreateCmd(flags))
	cmd.AddCommand(newAutomationsPeopleGetCmd(flags))
	cmd.AddCommand(newAutomationsPeopleListCmd(flags))
	cmd.AddCommand(newAutomationsPeopleUpdateCmd(flags))
	return cmd
}
