// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAutomationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "automations",
		Short:  "Manage automations",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAutomationsGetCmd(flags))
	cmd.AddCommand(newAutomationsListCmd(flags))
	return cmd
}
