// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCallsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "calls",
		Short:  "Manage calls",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCallsCreateCmd(flags))
	cmd.AddCommand(newCallsGetCmd(flags))
	cmd.AddCommand(newCallsListCmd(flags))
	cmd.AddCommand(newCallsUpdateCmd(flags))
	return cmd
}
