// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDealsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "deals",
		Short:  "Manage deals",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDealsCreateCmd(flags))
	cmd.AddCommand(newDealsDeleteCmd(flags))
	cmd.AddCommand(newDealsGetCmd(flags))
	cmd.AddCommand(newDealsListCmd(flags))
	cmd.AddCommand(newDealsUpdateCmd(flags))
	return cmd
}
