// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDealAttachmentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "deal-attachments",
		Short:  "Manage deal attachments",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDealAttachmentsCreateCmd(flags))
	cmd.AddCommand(newDealAttachmentsDeleteCmd(flags))
	cmd.AddCommand(newDealAttachmentsGetCmd(flags))
	cmd.AddCommand(newDealAttachmentsUpdateCmd(flags))
	return cmd
}
