// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDealCustomFieldsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "deal-custom-fields",
		Short:  "Manage deal custom fields",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDealCustomFieldsCreateCmd(flags))
	cmd.AddCommand(newDealCustomFieldsDeleteCmd(flags))
	cmd.AddCommand(newDealCustomFieldsGetCmd(flags))
	cmd.AddCommand(newDealCustomFieldsListCmd(flags))
	cmd.AddCommand(newDealCustomFieldsUpdateCmd(flags))
	return cmd
}
