// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEmCampaignsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "em-campaigns",
		Short:  "Manage em campaigns",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newEmCampaignsCreateCmd(flags))
	cmd.AddCommand(newEmCampaignsListCmd(flags))
	cmd.AddCommand(newEmCampaignsUpdateCmd(flags))
	return cmd
}
