// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEmEventsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "em-events",
		Short:  "Manage em events",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newEmEventsCreateCmd(flags))
	cmd.AddCommand(newEmEventsListCmd(flags))
	return cmd
}
