// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEventsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "events",
		Short:  "Manage events",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newEventsCreateCmd(flags))
	cmd.AddCommand(newEventsGetCmd(flags))
	cmd.AddCommand(newEventsListCmd(flags))
	return cmd
}
