// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGroupsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "groups",
		Short:  "Manage groups",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newGroupsCreateCmd(flags))
	cmd.AddCommand(newGroupsDeleteCmd(flags))
	cmd.AddCommand(newGroupsGetCmd(flags))
	cmd.AddCommand(newGroupsListCmd(flags))
	cmd.AddCommand(newGroupsRoundRobinListCmd(flags))
	cmd.AddCommand(newGroupsUpdateCmd(flags))
	return cmd
}
