// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newNotesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "notes",
		Short:  "Manage notes",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newNotesCreateCmd(flags))
	cmd.AddCommand(newNotesDeleteCmd(flags))
	cmd.AddCommand(newNotesGetCmd(flags))
	cmd.AddCommand(newNotesUpdateCmd(flags))
	return cmd
}
