// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPeopleRelationshipsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "people-relationships",
		Short:  "Manage people relationships",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPeopleRelationshipsCreateCmd(flags))
	cmd.AddCommand(newPeopleRelationshipsDeleteCmd(flags))
	cmd.AddCommand(newPeopleRelationshipsGetCmd(flags))
	cmd.AddCommand(newPeopleRelationshipsListCmd(flags))
	cmd.AddCommand(newPeopleRelationshipsUpdateCmd(flags))
	return cmd
}
