// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPeopleCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "people",
		Short:  "Manage people",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPeopleCheckDuplicateListCmd(flags))
	cmd.AddCommand(newPeopleClaimCreateCmd(flags))
	cmd.AddCommand(newPeopleCreateCmd(flags))
	cmd.AddCommand(newPeopleDeleteCmd(flags))
	cmd.AddCommand(newPeopleGetCmd(flags))
	cmd.AddCommand(newPeopleIgnoreUnclaimedCreateCmd(flags))
	cmd.AddCommand(newPeopleListCmd(flags))
	cmd.AddCommand(newPeopleUnclaimedListCmd(flags))
	cmd.AddCommand(newPeopleUpdateCmd(flags))
	return cmd
}
