// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPersonAttachmentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "person-attachments",
		Short:  "Manage person attachments",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPersonAttachmentsCreateCmd(flags))
	cmd.AddCommand(newPersonAttachmentsDeleteCmd(flags))
	cmd.AddCommand(newPersonAttachmentsGetCmd(flags))
	cmd.AddCommand(newPersonAttachmentsUpdateCmd(flags))
	return cmd
}
