// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPondsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "ponds",
		Short:  "Manage ponds",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPondsCreateCmd(flags))
	cmd.AddCommand(newPondsDeleteCmd(flags))
	cmd.AddCommand(newPondsGetCmd(flags))
	cmd.AddCommand(newPondsListCmd(flags))
	cmd.AddCommand(newPondsUpdateCmd(flags))
	return cmd
}
