// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newActionPlansPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagLimit int
	var flagOffset string
	var flagUpdatedAfter string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "action-plans",
		Short:       "Follow Up Boss GET /actionPlans. Source: https://docs.followupboss.com/reference/actionplans-get",
		Long:        "Shortcut for 'action-plans list'. Follow Up Boss GET /actionPlans. Source: https://docs.followupboss.com/reference/actionplans-get",
		Example:     "  follow-up-boss-pp-cli action-plans",
		Annotations: map[string]string{"pp:endpoint": "action-plans.list", "pp:method": "GET", "pp:path": "/actionPlans", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/actionPlans"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "action-plans", path, map[string]string{
				"limit":        fmt.Sprintf("%v", flagLimit),
				"offset":       fmt.Sprintf("%v", flagOffset),
				"updatedAfter": fmt.Sprintf("%v", flagUpdatedAfter),
			}, nil, flagAll, "offset", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Maximum number of records to return")
	cmd.Flags().StringVar(&flagOffset, "offset", "", "Offset for paginated results")
	cmd.Flags().StringVar(&flagUpdatedAfter, "updated-after", "", "Return records updated after this timestamp")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
