// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newReactionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "reactions",
		Short:  "Manage reactions",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newReactionsGetCmd(flags))
	cmd.AddCommand(newReactionsRefTypeRefIdCreateCmd(flags))
	cmd.AddCommand(newReactionsRefTypeRefIdDeleteCmd(flags))
	return cmd
}
