// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSmartListsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "smart-lists",
		Short:  "Manage smart lists",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSmartListsGetCmd(flags))
	cmd.AddCommand(newSmartListsListCmd(flags))
	return cmd
}
