// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newStagesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "stages",
		Short:  "Manage stages",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newStagesCreateCmd(flags))
	cmd.AddCommand(newStagesDeleteCmd(flags))
	cmd.AddCommand(newStagesGetCmd(flags))
	cmd.AddCommand(newStagesListCmd(flags))
	cmd.AddCommand(newStagesUpdateCmd(flags))
	return cmd
}
