// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTasksCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "tasks",
		Short:  "Manage tasks",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTasksCreateCmd(flags))
	cmd.AddCommand(newTasksDeleteCmd(flags))
	cmd.AddCommand(newTasksGetCmd(flags))
	cmd.AddCommand(newTasksListCmd(flags))
	cmd.AddCommand(newTasksUpdateCmd(flags))
	return cmd
}
