// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTeamsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "teams",
		Short:  "Manage teams",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTeamsCreateCmd(flags))
	cmd.AddCommand(newTeamsDeleteCmd(flags))
	cmd.AddCommand(newTeamsGetCmd(flags))
	cmd.AddCommand(newTeamsListCmd(flags))
	cmd.AddCommand(newTeamsUpdateCmd(flags))
	return cmd
}
