// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTextMessageTemplatesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "text-message-templates",
		Short:  "Manage text message templates",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTextMessageTemplatesCreateCmd(flags))
	cmd.AddCommand(newTextMessageTemplatesDeleteCmd(flags))
	cmd.AddCommand(newTextMessageTemplatesGetCmd(flags))
	cmd.AddCommand(newTextMessageTemplatesListCmd(flags))
	cmd.AddCommand(newTextMessageTemplatesMergeCreateCmd(flags))
	cmd.AddCommand(newTextMessageTemplatesUpdateCmd(flags))
	return cmd
}
