// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTextMessagesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "text-messages",
		Short:  "Manage text messages",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTextMessagesCreateCmd(flags))
	cmd.AddCommand(newTextMessagesGetCmd(flags))
	cmd.AddCommand(newTextMessagesListCmd(flags))
	return cmd
}
