// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUsersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "users",
		Short:  "Manage users",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newUsersDeleteCmd(flags))
	cmd.AddCommand(newUsersGetCmd(flags))
	cmd.AddCommand(newUsersListCmd(flags))
	return cmd
}
