// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newWebhooksCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "webhooks",
		Short:  "Manage webhooks",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newWebhooksCreateCmd(flags))
	cmd.AddCommand(newWebhooksDeleteCmd(flags))
	cmd.AddCommand(newWebhooksGetCmd(flags))
	cmd.AddCommand(newWebhooksListCmd(flags))
	cmd.AddCommand(newWebhooksUpdateCmd(flags))
	return cmd
}
