// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// whichEntry is one row of the curated capability index. The index is
// seeded at generation time from the same NovelFeature list that drives
// the SKILL.md feature section, so the command a `which` query returns
// is guaranteed to exist and to match what the skill advertises.
type whichEntry struct {
	Command      string `json:"command"`
	Description  string `json:"description"`
	Group        string `json:"group,omitempty"`
	WhyItMatters string `json:"why_it_matters,omitempty"`
}

// whichIndex is the curated list of capabilities this CLI advertises as
// its hero features. Endpoint-level commands are discoverable via
// `--help`; `which` exists to resolve a natural-language capability
// query to one of the commands the skill says matter most.
var whichIndex = []whichEntry{
	{Command: "action-plans list", Description: "Follow Up Boss GET /actionPlans. Source: https://docs.followupboss.com/reference/actionplans-get", Group: "action-plans"},
	{Command: "action-plans-people create", Description: "Follow Up Boss POST /actionPlansPeople. Source: https://docs.followupboss.com/reference/actionplanspeople-post", Group: "action-plans-people"},
	{Command: "action-plans-people list", Description: "Follow Up Boss GET /actionPlansPeople. Source: https://docs.followupboss.com/reference/actionplanspeople-get", Group: "action-plans-people"},
	{Command: "action-plans-people update", Description: "Follow Up Boss PUT /actionPlansPeople/{id}. Source: https://docs.followupboss.com/reference/actionplanspeople-id-put", Group: "action-plans-people"},
	{Command: "appointment-outcomes create", Description: "Follow Up Boss POST /appointmentOutcomes. Source: https://docs.followupboss.com/reference/appointmentoutcomes-post", Group: "appointment-outcomes"},
	{Command: "appointment-outcomes delete", Description: "Follow Up Boss DELETE /appointmentOutcomes/{id}. Source: https://docs.followupboss.com/reference/appointmentoutcomes-id-delete", Group: "appointment-outcomes"},
	{Command: "appointment-outcomes get", Description: "Follow Up Boss GET /appointmentOutcomes/{id}. Source: https://docs.followupboss.com/reference/appointmentoutcomes-id-get", Group: "appointment-outcomes"},
	{Command: "appointment-outcomes list", Description: "Follow Up Boss GET /appointmentOutcomes. Source: https://docs.followupboss.com/reference/appointmentoutcomes-get", Group: "appointment-outcomes"},
	{Command: "appointment-outcomes update", Description: "Follow Up Boss PUT /appointmentOutcomes/{id}. Source: https://docs.followupboss.com/reference/appointmentoutcomes-id-put", Group: "appointment-outcomes"},
	{Command: "appointment-types create", Description: "Follow Up Boss POST /appointmentTypes. Source: https://docs.followupboss.com/reference/appointmenttypes-post", Group: "appointment-types"},
	{Command: "appointment-types delete", Description: "Follow Up Boss DELETE /appointmentTypes/{id}. Source: https://docs.followupboss.com/reference/appointmenttypes-id-delete", Group: "appointment-types"},
	{Command: "appointment-types get", Description: "Follow Up Boss GET /appointmentTypes/{id}. Source: https://docs.followupboss.com/reference/appointmenttypes-id-get", Group: "appointment-types"},
	{Command: "appointment-types list", Description: "Follow Up Boss GET /appointmentTypes. Source: https://docs.followupboss.com/reference/appointmenttypes-get", Group: "appointment-types"},
	{Command: "appointment-types update", Description: "Follow Up Boss PUT /appointmentTypes/{id}. Source: https://docs.followupboss.com/reference/appointmenttypes-id-put", Group: "appointment-types"},
	{Command: "appointments create", Description: "Follow Up Boss POST /appointments. Source: https://docs.followupboss.com/reference/appointments-post", Group: "appointments"},
	{Command: "appointments delete", Description: "Follow Up Boss DELETE /appointments/{id}. Source: https://docs.followupboss.com/reference/appointments-id-delete", Group: "appointments"},
	{Command: "appointments get", Description: "Follow Up Boss GET /appointments/{id}. Source: https://docs.followupboss.com/reference/appointments-id-get", Group: "appointments"},
	{Command: "appointments list", Description: "Follow Up Boss GET /appointments. Source: https://docs.followupboss.com/reference/appointments-get", Group: "appointments"},
	{Command: "appointments update", Description: "Follow Up Boss PUT /appointments/{id}. Source: https://docs.followupboss.com/reference/appointments-id-put", Group: "appointments"},
	{Command: "automations get", Description: "Follow Up Boss GET /automations/{id}. Source: https://docs.followupboss.com/reference/automationsid", Group: "automations"},
	{Command: "automations list", Description: "Follow Up Boss GET /automations. Source: https://docs.followupboss.com/reference/automations", Group: "automations"},
	{Command: "automations-people create", Description: "Follow Up Boss POST /automationsPeople. Source: https://docs.followupboss.com/reference/automationspeople-1", Group: "automations-people"},
	{Command: "automations-people get", Description: "Follow Up Boss GET /automationsPeople/{id}. Source: https://docs.followupboss.com/reference/automationspeopleid-1", Group: "automations-people"},
	{Command: "automations-people list", Description: "Follow Up Boss GET /automationsPeople. Source: https://docs.followupboss.com/reference/automationspeople", Group: "automations-people"},
	{Command: "automations-people update", Description: "Follow Up Boss PUT /automationsPeople/{id}. Source: https://docs.followupboss.com/reference/automationspeopleid", Group: "automations-people"},
	{Command: "calls create", Description: "Follow Up Boss POST /calls. Source: https://docs.followupboss.com/reference/calls-post", Group: "calls"},
	{Command: "calls get", Description: "Follow Up Boss GET /calls/{id}. Source: https://docs.followupboss.com/reference/calls-id-get", Group: "calls"},
	{Command: "calls list", Description: "Follow Up Boss GET /calls. Source: https://docs.followupboss.com/reference/calls-get", Group: "calls"},
	{Command: "calls update", Description: "Follow Up Boss PUT /calls/{id}. Source: https://docs.followupboss.com/reference/calls-id-put", Group: "calls"},
	{Command: "custom-fields create", Description: "Follow Up Boss POST /customFields. Source: https://docs.followupboss.com/reference/customfields-post", Group: "custom-fields"},
	{Command: "custom-fields delete", Description: "Follow Up Boss DELETE /customFields/{id}. Source: https://docs.followupboss.com/reference/customfields-id-delete", Group: "custom-fields"},
	{Command: "custom-fields get", Description: "Follow Up Boss GET /customFields/{id}. Source: https://docs.followupboss.com/reference/customfields-id-get", Group: "custom-fields"},
	{Command: "custom-fields list", Description: "Follow Up Boss GET /customFields. Source: https://docs.followupboss.com/reference/customfields-get", Group: "custom-fields"},
	{Command: "custom-fields update", Description: "Follow Up Boss PUT /customFields/{id}. Source: https://docs.followupboss.com/reference/customfields-id-put", Group: "custom-fields"},
	{Command: "deal-attachments create", Description: "Follow Up Boss POST /dealAttachments. Source: https://docs.followupboss.com/reference/dealattachments-post", Group: "deal-attachments"},
	{Command: "deal-attachments delete", Description: "Follow Up Boss DELETE /dealAttachments/{id}. Source: https://docs.followupboss.com/reference/dealattachments-id-delete", Group: "deal-attachments"},
	{Command: "deal-attachments get", Description: "Follow Up Boss GET /dealAttachments/{id}. Source: https://docs.followupboss.com/reference/dealattachments-id-get", Group: "deal-attachments"},
	{Command: "deal-attachments update", Description: "Follow Up Boss PUT /dealAttachments/{id}. Source: https://docs.followupboss.com/reference/dealattachments-id-put", Group: "deal-attachments"},
	{Command: "deal-custom-fields create", Description: "Follow Up Boss POST /dealCustomFields. Source: https://docs.followupboss.com/reference/dealcustomfields-post", Group: "deal-custom-fields"},
	{Command: "deal-custom-fields delete", Description: "Follow Up Boss DELETE /dealCustomFields/{id}. Source: https://docs.followupboss.com/reference/dealcustomfields-id-delete", Group: "deal-custom-fields"},
	{Command: "deal-custom-fields get", Description: "Follow Up Boss GET /dealCustomFields/{id}. Source: https://docs.followupboss.com/reference/dealcustomfields-id-get", Group: "deal-custom-fields"},
	{Command: "deal-custom-fields list", Description: "Follow Up Boss GET /dealCustomFields. Source: https://docs.followupboss.com/reference/dealcustomfields-get", Group: "deal-custom-fields"},
	{Command: "deal-custom-fields update", Description: "Follow Up Boss PUT /dealCustomFields/{id}. Source: https://docs.followupboss.com/reference/dealcustomfields-id-put", Group: "deal-custom-fields"},
	{Command: "deals create", Description: "Follow Up Boss POST /deals. Source: https://docs.followupboss.com/reference/deals-post", Group: "deals"},
	{Command: "deals delete", Description: "Follow Up Boss DELETE /deals/{id}. Source: https://docs.followupboss.com/reference/deals-id-delete", Group: "deals"},
	{Command: "deals get", Description: "Follow Up Boss GET /deals/{id}. Source: https://docs.followupboss.com/reference/deals-id-get", Group: "deals"},
	{Command: "deals list", Description: "Follow Up Boss GET /deals. Source: https://docs.followupboss.com/reference/deals-get", Group: "deals"},
	{Command: "deals update", Description: "Follow Up Boss PUT /deals/{id}. Source: https://docs.followupboss.com/reference/deals-id-put", Group: "deals"},
	{Command: "em-campaigns create", Description: "Follow Up Boss POST /emCampaigns. Source: https://docs.followupboss.com/reference/emcampaigns-post", Group: "em-campaigns"},
	{Command: "em-campaigns list", Description: "Follow Up Boss GET /emCampaigns. Source: https://docs.followupboss.com/reference/emcampaigns-get", Group: "em-campaigns"},
	{Command: "em-campaigns update", Description: "Follow Up Boss PUT /emCampaigns/{id}. Source: https://docs.followupboss.com/reference/emcampaigns-id-put", Group: "em-campaigns"},
	{Command: "em-events create", Description: "Follow Up Boss POST /emEvents. Source: https://docs.followupboss.com/reference/emevents-post", Group: "em-events"},
	{Command: "em-events list", Description: "Follow Up Boss GET /emEvents. Source: https://docs.followupboss.com/reference/emevents-get", Group: "em-events"},
	{Command: "events create", Description: "Follow Up Boss POST /events. Source: https://docs.followupboss.com/reference/events-post", Group: "events"},
	{Command: "events get", Description: "Follow Up Boss GET /events/{id}. Source: https://docs.followupboss.com/reference/events-id-get", Group: "events"},
	{Command: "events list", Description: "Follow Up Boss GET /events. Source: https://docs.followupboss.com/reference/getting-started", Group: "events"},
	{Command: "groups create", Description: "Follow Up Boss POST /groups. Source: https://docs.followupboss.com/reference/groups-post", Group: "groups"},
	{Command: "groups delete", Description: "Follow Up Boss DELETE /groups/{id}. Source: https://docs.followupboss.com/reference/groups-id-delete", Group: "groups"},
	{Command: "groups get", Description: "Follow Up Boss GET /groups/{id}. Source: https://docs.followupboss.com/reference/groups-id-get", Group: "groups"},
	{Command: "groups list", Description: "Follow Up Boss GET /groups. Source: https://docs.followupboss.com/reference/groups-get", Group: "groups"},
	{Command: "groups round-robin-list", Description: "Follow Up Boss GET /groups/roundRobin. Source: https://docs.followupboss.com/reference/groups-roundrobin-get", Group: "groups"},
	{Command: "groups update", Description: "Follow Up Boss PUT /groups/{id}. Source: https://docs.followupboss.com/reference/groups-id-put", Group: "groups"},
	{Command: "identity list", Description: "Follow Up Boss GET /identity. Source: https://docs.followupboss.com/reference/identity", Group: "identity"},
	{Command: "me list", Description: "Follow Up Boss GET /me. Source: https://docs.followupboss.com/reference/me", Group: "me"},
	{Command: "notes create", Description: "Follow Up Boss POST /notes. Source: https://docs.followupboss.com/reference/notes-post", Group: "notes"},
	{Command: "notes delete", Description: "Follow Up Boss DELETE /notes/{id}. Source: https://docs.followupboss.com/reference/notes-id-delete", Group: "notes"},
	{Command: "notes get", Description: "Follow Up Boss GET /notes/{id}. Source: https://docs.followupboss.com/reference/notes-id-get", Group: "notes"},
	{Command: "notes update", Description: "Follow Up Boss PUT /notes/{id}. Source: https://docs.followupboss.com/reference/notes-id-put", Group: "notes"},
	{Command: "people check-duplicate-list", Description: "Follow Up Boss GET /people/checkDuplicate. Source: https://docs.followupboss.com/reference/people-checkduplicate", Group: "people"},
	{Command: "people claim-create", Description: "Follow Up Boss POST /people/claim. Source: https://docs.followupboss.com/reference/people-claim", Group: "people"},
	{Command: "people create", Description: "Follow Up Boss POST /people. Source: https://docs.followupboss.com/reference/people-post", Group: "people"},
	{Command: "people delete", Description: "Follow Up Boss DELETE /people/{id}. Source: https://docs.followupboss.com/reference/people-id-delete", Group: "people"},
	{Command: "people get", Description: "Follow Up Boss GET /people/{id}. Source: https://docs.followupboss.com/reference/people-id-get", Group: "people"},
	{Command: "people ignore-unclaimed-create", Description: "Follow Up Boss POST /people/ignoreUnclaimed. Source: https://docs.followupboss.com/reference/people-ignoreunclaimed", Group: "people"},
	{Command: "people list", Description: "Follow Up Boss GET /people. Source: https://docs.followupboss.com/reference/people-get", Group: "people"},
	{Command: "people unclaimed-list", Description: "Follow Up Boss GET /people/unclaimed. Source: https://docs.followupboss.com/reference/peopleunclaimed", Group: "people"},
	{Command: "people update", Description: "Follow Up Boss PUT /people/{id}. Source: https://docs.followupboss.com/reference/people-id-put", Group: "people"},
	{Command: "people-relationships create", Description: "Follow Up Boss POST /peopleRelationships. Source: https://docs.followupboss.com/reference/peoplerelationships-post", Group: "people-relationships"},
	{Command: "people-relationships delete", Description: "Follow Up Boss DELETE /peopleRelationships/{id}. Source: https://docs.followupboss.com/reference/peoplerelationships-id-delete", Group: "people-relationships"},
	{Command: "people-relationships get", Description: "Follow Up Boss GET /peopleRelationships/{id}. Source: https://docs.followupboss.com/reference/peoplerelationships-id-get", Group: "people-relationships"},
	{Command: "people-relationships list", Description: "Follow Up Boss GET /peopleRelationships. Source: https://docs.followupboss.com/reference/peoplerelationships", Group: "people-relationships"},
	{Command: "people-relationships update", Description: "Follow Up Boss PUT /peopleRelationships/{id}. Source: https://docs.followupboss.com/reference/peoplerelationships-id-put", Group: "people-relationships"},
	{Command: "person-attachments create", Description: "Follow Up Boss POST /personAttachments. Source: https://docs.followupboss.com/reference/personattachments-post", Group: "person-attachments"},
	{Command: "person-attachments delete", Description: "Follow Up Boss DELETE /personAttachments/{id}. Source: https://docs.followupboss.com/reference/personattachments-id-delete", Group: "person-attachments"},
	{Command: "person-attachments get", Description: "Follow Up Boss GET /personAttachments/{id}. Source: https://docs.followupboss.com/reference/personattachments-id-get", Group: "person-attachments"},
	{Command: "person-attachments update", Description: "Follow Up Boss PUT /personAttachments/{id}. Source: https://docs.followupboss.com/reference/personattachments-id-put", Group: "person-attachments"},
	{Command: "pipelines create", Description: "Follow Up Boss POST /pipelines. Source: https://docs.followupboss.com/reference/pipelines-post", Group: "pipelines"},
	{Command: "pipelines delete", Description: "Follow Up Boss DELETE /pipelines/{id}. Source: https://docs.followupboss.com/reference/pipelines-id-delete", Group: "pipelines"},
	{Command: "pipelines get", Description: "Follow Up Boss GET /pipelines/{id}. Source: https://docs.followupboss.com/reference/pipelines-id-get", Group: "pipelines"},
	{Command: "pipelines list", Description: "Follow Up Boss GET /pipelines. Source: https://docs.followupboss.com/reference/pipelines-get", Group: "pipelines"},
	{Command: "pipelines update", Description: "Follow Up Boss PUT /pipelines/{id}. Source: https://docs.followupboss.com/reference/pipelines-id-put", Group: "pipelines"},
	{Command: "ponds create", Description: "Follow Up Boss POST /ponds. Source: https://docs.followupboss.com/reference/ponds-post", Group: "ponds"},
	{Command: "ponds delete", Description: "Follow Up Boss DELETE /ponds/{id}. Source: https://docs.followupboss.com/reference/ponds-id-delete", Group: "ponds"},
	{Command: "ponds get", Description: "Follow Up Boss GET /ponds/{id}. Source: https://docs.followupboss.com/reference/ponds-id-get", Group: "ponds"},
	{Command: "ponds list", Description: "Follow Up Boss GET /ponds. Source: https://docs.followupboss.com/reference/ponds-get", Group: "ponds"},
	{Command: "ponds update", Description: "Follow Up Boss PUT /ponds/{id}. Source: https://docs.followupboss.com/reference/ponds-id-put", Group: "ponds"},
	{Command: "reactions get", Description: "Follow Up Boss GET /reactions/{id}. Source: https://docs.followupboss.com/reference/reactions", Group: "reactions"},
	{Command: "reactions ref-type-ref-id-create", Description: "Follow Up Boss POST /reactions/{refType}/{refId}. Source: https://docs.followupboss.com/reference/reactions-reftype-refid-post", Group: "reactions"},
	{Command: "reactions ref-type-ref-id-delete", Description: "Follow Up Boss DELETE /reactions/{refType}/{refId}. Source: https://docs.followupboss.com/reference/reactions-reftype-refid-delete", Group: "reactions"},
	{Command: "smart-lists get", Description: "Follow Up Boss GET /smartLists/{id}. Source: https://docs.followupboss.com/reference/smartlist-id-get", Group: "smart-lists"},
	{Command: "smart-lists list", Description: "Follow Up Boss GET /smartLists. Source: https://docs.followupboss.com/reference/smartlists-get", Group: "smart-lists"},
	{Command: "stages create", Description: "Follow Up Boss POST /stages. Source: https://docs.followupboss.com/reference/stages-post", Group: "stages"},
	{Command: "stages delete", Description: "Follow Up Boss DELETE /stages/{id}. Source: https://docs.followupboss.com/reference/stage-id-delete", Group: "stages"},
	{Command: "stages get", Description: "Follow Up Boss GET /stages/{id}. Source: https://docs.followupboss.com/reference/stages-id-get", Group: "stages"},
	{Command: "stages list", Description: "Follow Up Boss GET /stages. Source: https://docs.followupboss.com/reference/stages-get", Group: "stages"},
	{Command: "stages update", Description: "Follow Up Boss PUT /stages/{id}. Source: https://docs.followupboss.com/reference/stages-id-put", Group: "stages"},
	{Command: "tasks create", Description: "Follow Up Boss POST /tasks. Source: https://docs.followupboss.com/reference/tasks-post", Group: "tasks"},
	{Command: "tasks delete", Description: "Follow Up Boss DELETE /tasks/{id}. Source: https://docs.followupboss.com/reference/tasks-id-delete", Group: "tasks"},
	{Command: "tasks get", Description: "Follow Up Boss GET /tasks/{id}. Source: https://docs.followupboss.com/reference/tasks-id-get", Group: "tasks"},
	{Command: "tasks list", Description: "Follow Up Boss GET /tasks. Source: https://docs.followupboss.com/reference/tasks-get", Group: "tasks"},
	{Command: "tasks update", Description: "Follow Up Boss PUT /tasks/{id}. Source: https://docs.followupboss.com/reference/tasks-id-put", Group: "tasks"},
	{Command: "team-inboxes list", Description: "Follow Up Boss GET /teamInboxes. Source: https://docs.followupboss.com/reference/teaminboxes", Group: "team-inboxes"},
	{Command: "teams create", Description: "Follow Up Boss POST /teams. Source: https://docs.followupboss.com/reference/teams-post", Group: "teams"},
	{Command: "teams delete", Description: "Follow Up Boss DELETE /teams/{id}. Source: https://docs.followupboss.com/reference/teams-id-delete", Group: "teams"},
	{Command: "teams get", Description: "Follow Up Boss GET /teams/{id}. Source: https://docs.followupboss.com/reference/teams-id-get", Group: "teams"},
	{Command: "teams list", Description: "Follow Up Boss GET /teams. Source: https://docs.followupboss.com/reference/teams-get", Group: "teams"},
	{Command: "teams update", Description: "Follow Up Boss PUT /teams/{id}. Source: https://docs.followupboss.com/reference/teams-id-put", Group: "teams"},
	{Command: "templates create", Description: "Follow Up Boss POST /templates. Source: https://docs.followupboss.com/reference/templates-post", Group: "templates"},
	{Command: "templates delete", Description: "Follow Up Boss DELETE /templates/{id}. Source: https://docs.followupboss.com/reference/templates-id-delete", Group: "templates"},
	{Command: "templates get", Description: "Follow Up Boss GET /templates/{id}. Source: https://docs.followupboss.com/reference/templates-id-get", Group: "templates"},
	{Command: "templates list", Description: "Follow Up Boss GET /templates. Source: https://docs.followupboss.com/reference/templates-get", Group: "templates"},
	{Command: "templates merge-create", Description: "Follow Up Boss POST /templates/merge. Source: https://docs.followupboss.com/reference/templates-merge", Group: "templates"},
	{Command: "templates update", Description: "Follow Up Boss PUT /templates/{id}. Source: https://docs.followupboss.com/reference/templates-id-put", Group: "templates"},
	{Command: "text-message-templates create", Description: "Follow Up Boss POST /textMessageTemplates. Source: https://docs.followupboss.com/reference/textmessagetemplates-post", Group: "text-message-templates"},
	{Command: "text-message-templates delete", Description: "Follow Up Boss DELETE /textMessageTemplates/{id}. Source: https://docs.followupboss.com/reference/textmessagetemplates-id-delete", Group: "text-message-templates"},
	{Command: "text-message-templates get", Description: "Follow Up Boss GET /textMessageTemplates/{id}. Source: https://docs.followupboss.com/reference/textmessagetemplates-id-get", Group: "text-message-templates"},
	{Command: "text-message-templates list", Description: "Follow Up Boss GET /textMessageTemplates. Source: https://docs.followupboss.com/reference/textmessagetemplates-get", Group: "text-message-templates"},
	{Command: "text-message-templates merge-create", Description: "Follow Up Boss POST /textMessageTemplates/merge. Source: https://docs.followupboss.com/reference/textmessagetemplates-merge", Group: "text-message-templates"},
	{Command: "text-message-templates update", Description: "Follow Up Boss PUT /textMessageTemplates/{id}. Source: https://docs.followupboss.com/reference/textmessagetemplates-id-put", Group: "text-message-templates"},
	{Command: "text-messages create", Description: "Follow Up Boss POST /textMessages. Source: https://docs.followupboss.com/reference/textmessages-post", Group: "text-messages"},
	{Command: "text-messages get", Description: "Follow Up Boss GET /textMessages/{id}. Source: https://docs.followupboss.com/reference/textmessages-id-get", Group: "text-messages"},
	{Command: "text-messages list", Description: "Follow Up Boss GET /textMessages. Source: https://docs.followupboss.com/reference/textmessages-get", Group: "text-messages"},
	{Command: "threaded-replies get", Description: "Follow Up Boss GET /threadedReplies/{id}. Source: https://docs.followupboss.com/reference/threaded-replies", Group: "threaded-replies"},
	{Command: "timeframes list", Description: "Follow Up Boss GET /timeframes. Source: https://docs.followupboss.com/reference/timeframes-get", Group: "timeframes"},
	{Command: "users delete", Description: "Follow Up Boss DELETE /users/{id}. Source: https://docs.followupboss.com/reference/users-id-delete", Group: "users"},
	{Command: "users get", Description: "Follow Up Boss GET /users/{id}. Source: https://docs.followupboss.com/reference/users-id-get", Group: "users"},
	{Command: "users list", Description: "Follow Up Boss GET /users. Source: https://docs.followupboss.com/reference/users-get", Group: "users"},
	{Command: "webhook-events get", Description: "Follow Up Boss GET /webhookEvents/{id}. Source: https://docs.followupboss.com/reference/webhookevents-get", Group: "webhook-events"},
	{Command: "webhooks create", Description: "Follow Up Boss POST /webhooks. Source: https://docs.followupboss.com/reference/webhooks-post", Group: "webhooks"},
	{Command: "webhooks delete", Description: "Follow Up Boss DELETE /webhooks/{id}. Source: https://docs.followupboss.com/reference/webhooks-id-delete", Group: "webhooks"},
	{Command: "webhooks get", Description: "Follow Up Boss GET /webhooks/{id}. Source: https://docs.followupboss.com/reference/webhooks-id-get", Group: "webhooks"},
	{Command: "webhooks list", Description: "Follow Up Boss GET /webhooks. Source: https://docs.followupboss.com/reference/webhooks-get", Group: "webhooks"},
	{Command: "webhooks update", Description: "Follow Up Boss PUT /webhooks/{id}. Source: https://docs.followupboss.com/reference/webhooks-id-put", Group: "webhooks"},
}

// whichMatch pairs an index entry with its ranking score for a query.
// Higher score means stronger match. The ranker is naive (exact token
// then substring then group tag) because 20-40 entries do not need
// semantic retrieval - a ranker upgrade is a future change that would
// not break this contract.
type whichMatch struct {
	Entry whichEntry `json:"entry"`
	Score int        `json:"score"`
}

// rankWhich returns up to `limit` best matches for `query` against the
// index, sorted by descending score. Score breakdown:
//
//	+3  exact token match on the command's leaf or full path
//	+2  substring match on the command (any part)
//	+2  substring match on the description
//	+1  group tag contains the query as a word
//
// Ties break on declaration order in the index. An empty query returns
// every entry at score 0 in declaration order - this is the "list all"
// behavior the skill documents for broad agent discovery.
func rankWhich(index []whichEntry, query string, limit int) []whichMatch {
	if limit <= 0 {
		limit = 3
	}
	q := strings.ToLower(strings.TrimSpace(query))
	if q == "" {
		out := make([]whichMatch, 0, len(index))
		for _, e := range index {
			out = append(out, whichMatch{Entry: e, Score: 0})
		}
		return out
	}
	qTokens := strings.Fields(q)

	scored := make([]whichMatch, 0, len(index))
	for i, e := range index {
		score := whichScoreEntry(e, q, qTokens)
		scored = append(scored, whichMatch{Entry: e, Score: score})
		_ = i
	}

	sort.SliceStable(scored, func(i, j int) bool {
		return scored[i].Score > scored[j].Score
	})
	// Drop zero-score matches when the query was non-empty; agents
	// branching on exit code rely on "no match" meaning no confidence.
	filtered := scored[:0]
	for _, m := range scored {
		if m.Score > 0 {
			filtered = append(filtered, m)
		}
	}
	if len(filtered) > limit {
		filtered = filtered[:limit]
	}
	return filtered
}

func whichScoreEntry(e whichEntry, query string, qTokens []string) int {
	score := 0
	cmd := strings.ToLower(e.Command)
	cmdTokens := strings.Fields(cmd)
	desc := strings.ToLower(e.Description)
	group := strings.ToLower(e.Group)

	// Exact token match on the command path (any token).
	for _, qt := range qTokens {
		for _, ct := range cmdTokens {
			if qt == ct {
				score += 3
				break
			}
		}
	}
	// Substring match on the full command (covers hyphenated leaves).
	if strings.Contains(cmd, query) {
		score += 2
	}
	// Substring match on the description.
	if strings.Contains(desc, query) {
		score += 2
	}
	// Group tag match.
	if group != "" {
		for _, qt := range qTokens {
			if strings.Contains(group, qt) {
				score += 1
				break
			}
		}
	}
	return score
}

func newWhichCmd(flags *rootFlags) *cobra.Command {
	var limit int
	cmd := &cobra.Command{
		Use:   "which [query]",
		Short: "Find the command that implements a capability",
		Annotations: map[string]string{
			"pp:typed-exit-codes": "0,2",
		},
		Long: `which resolves a natural-language capability query (for example, "search messages" or "stale tickets") to the best matching command from this CLI's curated feature index.

Exit codes:
  0  at least one match found
  2  no confident match - the query did not score against any indexed capability; fall back to '--help' or 'search' if this CLI has one`,
		Example: `  follow-up-boss-pp-cli which "stale tickets"
  follow-up-boss-pp-cli which "bottleneck"
  follow-up-boss-pp-cli which --limit 1 "send message"
  follow-up-boss-pp-cli which                                # list the full capability index`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(whichIndex) == 0 {
				return usageErr(fmt.Errorf("this CLI has no curated capability index; run '--help' to see every command"))
			}
			query := strings.Join(args, " ")
			matches := rankWhich(whichIndex, query, limit)

			// Empty query returns the whole index at score 0 (listing mode).
			if strings.TrimSpace(query) == "" {
				return renderWhich(cmd, flags, rankWhichAll(whichIndex))
			}

			if len(matches) == 0 {
				// Under --json, return an empty matches envelope at exit 0
				// so agents can branch on `matches.length == 0` instead of
				// parsing a usage error message. Non-JSON keeps the typed
				// exit-2 path so terminal users see the help hint.
				if flags.asJSON {
					return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"matches": []whichMatch{},
					}, flags)
				}
				return usageErr(fmt.Errorf("no match for %q; try '%s --help' for the full command list", query, cmd.Root().Name()))
			}
			return renderWhich(cmd, flags, matches)
		},
	}
	cmd.Flags().IntVar(&limit, "limit", 3, "Maximum number of matches to return")
	return cmd
}

// rankWhichAll is a narrow helper used by the "empty query lists the
// index" path. It returns every entry in declaration order at score 0
// so the render path treats them uniformly.
func rankWhichAll(index []whichEntry) []whichMatch {
	out := make([]whichMatch, 0, len(index))
	for _, e := range index {
		out = append(out, whichMatch{Entry: e, Score: 0})
	}
	return out
}

func renderWhich(cmd *cobra.Command, flags *rootFlags, matches []whichMatch) error {
	w := cmd.OutOrStdout()
	// Output shape follows the same rule as every other generated
	// command: JSON when the caller asked for it OR when stdout is not
	// a terminal; table when a human is looking.
	asJSON := flags.asJSON
	if !asJSON && !isTerminal(w) {
		asJSON = true
	}
	if asJSON {
		// JSON envelope: {matches: [...]}. The wrap is critical:
		// printJSONFiltered's --compact path uses compactListFields
		// (allowlist) for top-level arrays, which would strip
		// entry/score keys; routing through compactObjectFields
		// (blocklist) via an object envelope preserves them.
		if matches == nil {
			matches = []whichMatch{}
		}
		return printJSONFiltered(w, map[string]any{"matches": matches}, flags)
	}
	fmt.Fprintf(w, "%-24s  %-8s  %s\n", "COMMAND", "SCORE", "DESCRIPTION")
	for _, m := range matches {
		fmt.Fprintf(w, "%-24s  %-8d  %s\n", m.Entry.Command, m.Score, m.Entry.Description)
	}
	return nil
}
