// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cliutil

import (
	"os"
	"strings"
)

const (
	MCPProfileAgent    = "agent"
	MCPProfileOperator = "operator"

	MCPProfileEnvVar = "PP_MCP_PROFILE"
)

// MCPToolSafety is the profile-relevant safety envelope for one MCP tool.
type MCPToolSafety struct {
	Name             string
	Destructive      bool
	PrivacySensitive bool
}

// CurrentMCPProfile returns the active MCP profile. The default is the safer
// agent profile; operators and connector runners must opt into the full
// surface with PP_MCP_PROFILE=operator.
func CurrentMCPProfile() string {
	switch strings.ToLower(strings.TrimSpace(os.Getenv(MCPProfileEnvVar))) {
	case MCPProfileOperator:
		return MCPProfileOperator
	default:
		return MCPProfileAgent
	}
}

func MCPToolAvailableInProfile(safety MCPToolSafety) bool {
	if CurrentMCPProfile() == MCPProfileOperator {
		return true
	}
	if ProposeNamespaceTool(safety.Name) {
		return true
	}
	return !safety.Destructive && !safety.PrivacySensitive
}

func ProposeNamespaceTool(name string) bool {
	normalized := strings.ToLower(strings.TrimSpace(name))
	normalized = strings.ReplaceAll(normalized, "-", "_")
	return strings.HasPrefix(normalized, "propose_") ||
		strings.Contains(normalized, "_propose_")
}

func MCPProfileUnavailableMessage(cliName string) string {
	return "tool not available in agent profile; propose via " + cliName
}
