// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cliutil

import "testing"

func TestMCPToolAvailableInProfile_AgentOmitsDestructiveAndPrivacy(t *testing.T) {
	t.Setenv(MCPProfileEnvVar, MCPProfileAgent)

	cases := []MCPToolSafety{
		{Name: "people_delete", Destructive: true},
		{Name: "mail_bodies_get", PrivacySensitive: true},
		{Name: "deals_delete", Destructive: true, PrivacySensitive: true},
	}
	for _, tc := range cases {
		if MCPToolAvailableInProfile(tc) {
			t.Fatalf("MCPToolAvailableInProfile(%+v) = true, want false", tc)
		}
	}
}

func TestMCPToolAvailableInProfile_AgentAllowsProposeNamespace(t *testing.T) {
	t.Setenv(MCPProfileEnvVar, MCPProfileAgent)

	if !MCPToolAvailableInProfile(MCPToolSafety{Name: "fub_propose_contact_upsert", Destructive: true}) {
		t.Fatal("agent profile should allow destructive tools in a propose namespace")
	}
}

func TestMCPToolAvailableInProfile_OperatorExposesFullSurface(t *testing.T) {
	t.Setenv(MCPProfileEnvVar, MCPProfileOperator)

	if !MCPToolAvailableInProfile(MCPToolSafety{Name: "people_delete", Destructive: true, PrivacySensitive: true}) {
		t.Fatal("operator profile should expose destructive and privacy-sensitive tools")
	}
}
