// Copyright 2026 openclaw. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cliutil

import (
	"context"
	"database/sql"
	"fmt"
	"math"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"
	"sync"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib"
)

// AdaptiveLimiter paces outbound requests with adaptive ceiling discovery.
// Starts at a floor rate, ramps up after consecutive successes, halves on 429
// and records a ceiling. Per-session only — not persisted. Methods are safe
// to call on a nil receiver.
type AdaptiveLimiter struct {
	mu          sync.Mutex
	key         rateLimitKey
	backend     rateLimitBackend
	rate        float64
	floor       float64
	ceiling     float64
	successes   int
	rampAfter   int
	lastRequest time.Time // zero-value: first Wait() returns immediately
	limit       int
	remaining   int
	window      string
	context     string
}

// NewAdaptiveLimiter returns a limiter starting at ratePerSec, or nil when
// rate-limiting should be disabled. Methods on the nil limiter no-op.
func NewAdaptiveLimiter(ratePerSec float64) *AdaptiveLimiter {
	return NewAdaptiveLimiterForHost(ratePerSec, "")
}

// NewAdaptiveLimiterForHost returns a limiter scoped to a provider host. When
// PP_RATELIMIT_BACKEND=postgres, state is shared through
// connector_rate_limit_state using (host, tenant_id) as the row key.
func NewAdaptiveLimiterForHost(ratePerSec float64, baseURL string) *AdaptiveLimiter {
	if ratePerSec <= 0 {
		return nil
	}
	return &AdaptiveLimiter{
		key:       newRateLimitKey(baseURL),
		backend:   newRateLimitBackendFromEnv(),
		rate:      ratePerSec,
		floor:     ratePerSec,
		rampAfter: 10,
	}
}

func (l *AdaptiveLimiter) Wait() {
	if l == nil {
		return
	}
	var wait time.Duration
	l.updateState(func(state *rateLimitState) {
		rate := state.Rate
		if rate <= 0 {
			rate = state.Floor
		}
		if rate <= 0 {
			return
		}
		delay := time.Duration(float64(time.Second) / rate)
		now := time.Now()
		nextRequest := now
		if !state.LastRequest.IsZero() {
			minNext := state.LastRequest.Add(delay)
			if minNext.After(now) {
				nextRequest = minNext
			}
		}
		wait = time.Until(nextRequest)
		state.LastRequest = nextRequest
	})
	if wait > 0 {
		time.Sleep(wait)
	}
}

func (l *AdaptiveLimiter) OnSuccess() {
	if l == nil {
		return
	}
	l.updateState(func(state *rateLimitState) {
		state.Successes++
		if state.Successes >= l.rampAfter {
			newRate := state.Rate * 1.25
			if state.Ceiling > 0 && newRate > state.Ceiling*0.9 {
				newRate = state.Ceiling * 0.9
			}
			state.Rate = newRate
			state.Successes = 0
		}
	})
}

// OnResponse reads provider rate-limit response headers on every response and
// adjusts pacing before the provider returns a hard 429. Missing or malformed
// headers are ignored so existing Retry-After/429 behavior remains the fallback.
func (l *AdaptiveLimiter) OnResponse(resp *http.Response) {
	if l == nil || resp == nil {
		return
	}
	limit, remaining, window, context, ok := parseRateLimitHeaders(resp.Header)
	if !ok {
		return
	}

	l.updateState(func(state *rateLimitState) {
		windowTransition := window != "" && state.Window != "" && window != state.Window
		if windowTransition {
			state.Ceiling = 0
			if state.Rate < state.Floor {
				state.Rate = state.Floor
			} else {
				state.Rate *= 1.25
			}
			state.Successes = 0
		}

		previousRemaining := state.Remaining
		state.Limit = limit
		state.Remaining = remaining
		state.Window = window
		state.Context = context

		if limit <= 0 {
			return
		}
		lowWatermark := float64(limit) * 0.10
		remainingDropped := previousRemaining == 0 || remaining < previousRemaining
		if float64(remaining) < lowWatermark && remainingDropped {
			state.Ceiling = state.Rate
			state.Rate = state.Rate / 2
			if state.Rate < 0.5 {
				state.Rate = 0.5
			}
			state.Successes = 0
		}
	})
}

func (l *AdaptiveLimiter) OnRateLimit() {
	if l == nil {
		return
	}
	l.updateState(func(state *rateLimitState) {
		state.Ceiling = state.Rate
		state.Rate = state.Rate / 2
		if state.Rate < 0.5 {
			state.Rate = 0.5
		}
		state.Successes = 0
	})
}

func (l *AdaptiveLimiter) Rate() float64 {
	if l == nil {
		return 0
	}
	l.mu.Lock()
	defer l.mu.Unlock()
	return l.rate
}

func (l *AdaptiveLimiter) updateState(mutate func(*rateLimitState)) {
	if l == nil || mutate == nil {
		return
	}
	l.mu.Lock()
	state := l.snapshotLocked()
	l.mu.Unlock()

	updated, err := l.backend.Update(context.Background(), l.key, state, mutate)
	if err != nil {
		l.mu.Lock()
		state = l.snapshotLocked()
		mutate(&state)
		l.applyStateLocked(state)
		l.mu.Unlock()
		return
	}

	l.mu.Lock()
	l.applyStateLocked(updated)
	l.mu.Unlock()
}

func (l *AdaptiveLimiter) snapshotLocked() rateLimitState {
	return rateLimitState{
		Rate:        l.rate,
		Floor:       l.floor,
		Ceiling:     l.ceiling,
		Successes:   l.successes,
		LastRequest: l.lastRequest,
		Limit:       l.limit,
		Remaining:   l.remaining,
		Window:      l.window,
		Context:     l.context,
	}
}

func (l *AdaptiveLimiter) applyStateLocked(state rateLimitState) {
	l.rate = state.Rate
	l.floor = state.Floor
	l.ceiling = state.Ceiling
	l.successes = state.Successes
	l.lastRequest = state.LastRequest
	l.limit = state.Limit
	l.remaining = state.Remaining
	l.window = state.Window
	l.context = state.Context
}

type rateLimitKey struct {
	Host     string
	TenantID string
}

type rateLimitState struct {
	Rate        float64
	Floor       float64
	Ceiling     float64
	Successes   int
	LastRequest time.Time
	Limit       int
	Remaining   int
	Window      string
	Context     string
}

type rateLimitBackend interface {
	Update(ctx context.Context, key rateLimitKey, state rateLimitState, mutate func(*rateLimitState)) (rateLimitState, error)
}

type memoryRateLimitBackend struct {
	mu     sync.Mutex
	states map[rateLimitKey]rateLimitState
}

func newMemoryRateLimitBackend() *memoryRateLimitBackend {
	return &memoryRateLimitBackend{states: map[rateLimitKey]rateLimitState{}}
}

func (b *memoryRateLimitBackend) Update(_ context.Context, key rateLimitKey, state rateLimitState, mutate func(*rateLimitState)) (rateLimitState, error) {
	b.mu.Lock()
	defer b.mu.Unlock()
	if stored, ok := b.states[key]; ok {
		state = stored
	}
	mutate(&state)
	b.states[key] = state
	return state, nil
}

type postgresRateLimitBackend struct {
	db *sql.DB
}

const (
	ppRateLimitBackendEnv = "PP_RATELIMIT_BACKEND"
	ppRateLimitPGURLEnv   = "PP_RATELIMIT_PG_URL"
	ppRateLimitTenantEnv  = "PP_RATELIMIT_TENANT_ID"

	insertRateLimitStateSQL = `INSERT INTO connector_rate_limit_state
	(host, tenant_id, rate, floor, ceiling, successes, last_request_at, limit_value, remaining, window, context, updated_at)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW())
	ON CONFLICT (host, tenant_id) DO NOTHING`
	selectRateLimitStateForUpdateSQL = `SELECT rate, floor, ceiling, successes, last_request_at, limit_value, remaining, window, context
	FROM connector_rate_limit_state
	WHERE host = $1 AND tenant_id = $2
	FOR UPDATE`
	updateRateLimitStateSQL = `UPDATE connector_rate_limit_state
	SET rate = $3, floor = $4, ceiling = $5, successes = $6, last_request_at = $7,
		limit_value = $8, remaining = $9, window = $10, context = $11, updated_at = NOW()
	WHERE host = $1 AND tenant_id = $2`
)

func newRateLimitBackendFromEnv() rateLimitBackend {
	if strings.EqualFold(strings.TrimSpace(os.Getenv(ppRateLimitBackendEnv)), "postgres") {
		if pgURL := strings.TrimSpace(os.Getenv(ppRateLimitPGURLEnv)); pgURL != "" {
			if db, err := sql.Open("pgx", pgURL); err == nil {
				return &postgresRateLimitBackend{db: db}
			}
		}
	}
	return newMemoryRateLimitBackend()
}

func (b *postgresRateLimitBackend) Update(ctx context.Context, key rateLimitKey, state rateLimitState, mutate func(*rateLimitState)) (rateLimitState, error) {
	if b == nil || b.db == nil {
		mutate(&state)
		return state, nil
	}
	tx, err := b.db.BeginTx(ctx, nil)
	if err != nil {
		return state, err
	}
	defer tx.Rollback()

	if _, err := tx.ExecContext(ctx, insertRateLimitStateSQL, key.Host, key.TenantID, state.Rate, state.Floor, state.Ceiling, state.Successes, nullableTime(state.LastRequest), state.Limit, state.Remaining, state.Window, state.Context); err != nil {
		return state, err
	}
	row := tx.QueryRowContext(ctx, selectRateLimitStateForUpdateSQL, key.Host, key.TenantID)
	if scanned, err := scanRateLimitState(row); err == nil {
		state = mergeRateLimitDefaults(state, scanned)
	} else if err != sql.ErrNoRows {
		return state, err
	}

	mutate(&state)

	if _, err := tx.ExecContext(ctx, updateRateLimitStateSQL, key.Host, key.TenantID, state.Rate, state.Floor, state.Ceiling, state.Successes, nullableTime(state.LastRequest), state.Limit, state.Remaining, state.Window, state.Context); err != nil {
		return state, err
	}
	if err := tx.Commit(); err != nil {
		return state, err
	}
	return state, nil
}

type rateLimitScanner interface {
	Scan(dest ...any) error
}

func scanRateLimitState(row rateLimitScanner) (rateLimitState, error) {
	var state rateLimitState
	var lastRequest sql.NullTime
	var window, context sql.NullString
	err := row.Scan(&state.Rate, &state.Floor, &state.Ceiling, &state.Successes, &lastRequest, &state.Limit, &state.Remaining, &window, &context)
	if err != nil {
		return state, err
	}
	if lastRequest.Valid {
		state.LastRequest = lastRequest.Time
	}
	if window.Valid {
		state.Window = window.String
	}
	if context.Valid {
		state.Context = context.String
	}
	return state, nil
}

func mergeRateLimitDefaults(initial, stored rateLimitState) rateLimitState {
	if stored.Rate <= 0 {
		stored.Rate = initial.Rate
	}
	if stored.Floor <= 0 {
		stored.Floor = initial.Floor
	}
	return stored
}

func nullableTime(t time.Time) any {
	if t.IsZero() {
		return nil
	}
	return t.UTC()
}

func newRateLimitKey(baseURL string) rateLimitKey {
	host := normalizeRateLimitHost(baseURL)
	if host == "" {
		host = "local"
	}
	tenantID := strings.TrimSpace(os.Getenv(ppRateLimitTenantEnv))
	if tenantID == "" {
		tenantID = "default"
	}
	return rateLimitKey{Host: host, TenantID: tenantID}
}

func normalizeRateLimitHost(raw string) string {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return ""
	}
	if u, err := url.Parse(raw); err == nil && u.Host != "" {
		return strings.ToLower(u.Host)
	}
	if u, err := url.Parse("https://" + raw); err == nil && u.Host != "" {
		return strings.ToLower(u.Host)
	}
	return strings.ToLower(raw)
}

func parseRateLimitHeaders(header http.Header) (limit int, remaining int, window string, context string, ok bool) {
	if header == nil {
		return 0, 0, "", "", false
	}
	limitValue, err := strconv.Atoi(strings.TrimSpace(header.Get("X-RateLimit-Limit")))
	if err != nil || limitValue <= 0 {
		return 0, 0, "", "", false
	}
	remainingValue, err := strconv.Atoi(strings.TrimSpace(header.Get("X-RateLimit-Remaining")))
	if err != nil || remainingValue < 0 {
		return 0, 0, "", "", false
	}
	return limitValue, remainingValue, strings.TrimSpace(header.Get("X-RateLimit-Window")), strings.TrimSpace(header.Get("X-RateLimit-Context")), true
}

// RateLimitError signals an upstream returned 429 after retries were
// exhausted. Callers must surface this as a hard error rather than empty
// results — empty-on-throttle is indistinguishable from "no data exists"
// and silently corrupts downstream queries.
type RateLimitError struct {
	URL        string
	RetryAfter time.Duration
	Body       string
}

func (e *RateLimitError) Error() string {
	msg := fmt.Sprintf("rate limited: HTTP 429 for %s", e.URL)
	if e.RetryAfter > 0 {
		msg += fmt.Sprintf("; retry after %s", e.RetryAfter)
	}
	if body := strings.TrimSpace(e.Body); body != "" {
		msg += ": " + body
	}
	return msg
}

// MaxRetryWait caps the wait derived from a Retry-After header so a buggy
// or hostile upstream cannot pin a CLI for hours.
const MaxRetryWait = 60 * time.Second

const (
	defaultRetryWait               = 5 * time.Second
	unixEpochSecondsThreshold      = 1_000_000_000
	unixEpochMillisecondsThreshold = 1_000_000_000_000
)

// RetryAfter parses an HTTP Retry-After header (RFC 7231: delta-seconds or
// HTTP-date), plus common Unix epoch seconds/milliseconds variants emitted by
// some APIs. Waits are capped at MaxRetryWait. Returns 5s when missing or
// unparseable.
func RetryAfter(resp *http.Response) time.Duration {
	if resp == nil {
		return defaultRetryWait
	}
	header := strings.TrimSpace(resp.Header.Get("Retry-After"))
	if header == "" {
		return defaultRetryWait
	}
	if value, err := strconv.ParseInt(header, 10, 64); err == nil {
		return retryAfterFromNumber(value)
	}
	if t, err := http.ParseTime(header); err == nil {
		wait := time.Until(t)
		if wait > MaxRetryWait {
			return MaxRetryWait
		}
		if wait > 0 {
			return wait
		}
	}
	return defaultRetryWait
}

func retryAfterFromNumber(value int64) time.Duration {
	if value <= 0 {
		return defaultRetryWait
	}
	if value > int64(MaxRetryWait/time.Second) {
		if wait := retryAfterEpochWait(value); wait > 0 {
			if wait > MaxRetryWait {
				return MaxRetryWait
			}
			return wait
		}
		return MaxRetryWait
	}
	return time.Duration(value) * time.Second
}

func retryAfterEpochWait(value int64) time.Duration {
	switch {
	case value >= unixEpochMillisecondsThreshold:
		return time.Until(time.UnixMilli(value))
	case value >= unixEpochSecondsThreshold:
		return time.Until(time.Unix(value, 0))
	default:
		return 0
	}
}

// MaxBackoff caps Backoff so tests stay bounded. Callers needing jitter
// add their own; the bare exponential keeps the contract deterministic.
const MaxBackoff = 30 * time.Second

// Backoff returns 2^attempt seconds capped at MaxBackoff.
func Backoff(attempt int) time.Duration {
	if attempt < 0 {
		attempt = 0
	}
	wait := time.Duration(math.Pow(2, float64(attempt))) * time.Second
	if wait > MaxBackoff {
		return MaxBackoff
	}
	return wait
}
