// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package config

import (
	"encoding/base64"
	"testing"
)

func TestAuthHeader_FollowUpBossBasicAPIKey(t *testing.T) {
	cfg := &Config{FubApiKey: "abc123"}
	want := "Basic " + base64.StdEncoding.EncodeToString([]byte("abc123:"))
	if got := cfg.AuthHeader(); got != want {
		t.Fatalf("AuthHeader() = %q, want %q", got, want)
	}
}

func TestAuthHeader_PrefersOAuthBearerToken(t *testing.T) {
	cfg := &Config{AccessToken: "oauth-token", FubApiKey: "api-key"}
	if got := cfg.AuthHeader(); got != "Bearer oauth-token" {
		t.Fatalf("AuthHeader() = %q, want bearer token", got)
	}
}

func TestRequestHeaders_AddsFollowUpBossSystemHeaders(t *testing.T) {
	cfg := &Config{
		Headers:      map[string]string{"Accept-Language": "en"},
		FubSystem:    "agent-system",
		FubSystemKey: "system-key",
	}
	got := cfg.RequestHeaders()
	if got["X-System"] != "agent-system" {
		t.Fatalf("X-System = %q, want agent-system", got["X-System"])
	}
	if got["X-System-Key"] != "system-key" {
		t.Fatalf("X-System-Key = %q, want system-key", got["X-System-Key"])
	}
	if got["Accept-Language"] != "en" {
		t.Fatalf("generic header was not preserved: %#v", got)
	}
}
