// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cobratree

import (
	"fmt"
	"follow-up-boss-pp-cli/internal/cliutil"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/spf13/cobra"
	"os"
)

type RegisterToolFunc func(*server.MCPServer, mcplib.Tool, cliutil.MCPToolSafety, server.ToolHandlerFunc)

// RegisterAll walks root's user-facing Cobra commands and registers shell-out
// MCP tools for commands that are not already covered by typed endpoint tools.
func RegisterAll(s *server.MCPServer, root *cobra.Command, cliPath func() (string, error), register RegisterToolFunc) {
	if root == nil {
		return
	}
	if register == nil {
		register = func(s *server.MCPServer, tool mcplib.Tool, safety cliutil.MCPToolSafety, handler server.ToolHandlerFunc) {
			s.AddTool(tool, handler)
		}
	}
	walk(root, nil, func(cmd *cobra.Command, path []string) {
		switch classify(cmd) {
		case commandHidden:
			return
		case commandEndpoint, commandFramework:
			return
		}
		if !cmd.Runnable() {
			return
		}

		toolName := toolNameForPath(path)
		if toolName == "" {
			return
		}
		options := []mcplib.ToolOption{mcplib.WithDescription(descriptionFor(cmd))}
		options = append(options, toolOptionsForFlags(cmd)...)
		if commandTakesArgs(cmd) {
			options = append(options, mcplib.WithString("args", mcplib.Description("Additional positional arguments or raw CLI flags to append to the command.")))
		}
		options = append(options, safetyToolOptions(cmd, path)...)
		register(s, mcplib.NewTool(toolName, options...), toolSafety(cmd, path, toolName), shellOutToCLI(cliPath, path))
	})
}

func toolSafety(cmd *cobra.Command, path []string, toolName string) cliutil.MCPToolSafety {
	safety := cliutil.MCPToolSafety{Name: toolName, PrivacySensitive: isMCPPrivacySensitive(cmd)}
	if isMCPDestructive(cmd) {
		safety.Destructive = true
		return safety
	}
	if method(cmd) == "DELETE" {
		safety.Destructive = true
	}
	return safety
}

func safetyToolOptions(cmd *cobra.Command, path []string) []mcplib.ToolOption {
	if isMCPReadOnly(cmd) {
		return []mcplib.ToolOption{mcplib.WithReadOnlyHintAnnotation(true), mcplib.WithDestructiveHintAnnotation(false)}
	}
	if isMCPDestructive(cmd) {
		return []mcplib.ToolOption{mcplib.WithDestructiveHintAnnotation(true), mcplib.WithOpenWorldHintAnnotation(true)}
	}
	switch method(cmd) {
	case "GET", "HEAD", "OPTIONS":
		return []mcplib.ToolOption{mcplib.WithReadOnlyHintAnnotation(true), mcplib.WithDestructiveHintAnnotation(false), mcplib.WithOpenWorldHintAnnotation(true)}
	case "DELETE":
		return []mcplib.ToolOption{mcplib.WithDestructiveHintAnnotation(true), mcplib.WithOpenWorldHintAnnotation(true)}
	case "POST", "PUT", "PATCH":
		fmt.Fprintf(os.Stderr, "warning: command %s is an unannotated mutation; agents will not see destructive signal - annotate explicitly\n", commandPath(path))
	}
	return nil
}

func walk(cmd *cobra.Command, path []string, visit func(*cobra.Command, []string)) {
	for _, child := range cmd.Commands() {
		if child.Hidden || isMCPHidden(child) {
			continue
		}
		childPath := append(append([]string{}, path...), child.Name())
		visit(child, childPath)
		if kind := classify(child); kind != commandHidden && kind != commandFramework {
			walk(child, childPath, visit)
		}
	}
}

func descriptionFor(cmd *cobra.Command) string {
	prefix := ""
	if isMCPPrivacySensitive(cmd) {
		prefix = "Privacy-sensitive: may expose PII or financial data. "
	}
	if cmd.Long != "" {
		return prefix + cmd.Long
	}
	if cmd.Short != "" {
		return prefix + cmd.Short
	}
	return prefix + "Run `" + cmd.CommandPath() + "` through the companion CLI binary."
}

func commandPath(path []string) string {
	if len(path) == 0 {
		return "<root>"
	}
	out := path[0]
	for _, part := range path[1:] {
		out += " " + part
	}
	return out
}
